---
apiVersion: v1
kind: Service
metadata:
  name: loki-ts
  annotations:
    tailscale.com/hostname: loki
    tailscale.com/tags: "tag:k8s,tag:ottawa"
    tailscale.com/proxy-group: "common-ingress"
spec:
  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: gateway
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
