# ClusterPropagationPolicy for workloads pinned to Ottawa
---
apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: pinned-ottawa
spec:
  resourceSelectors:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      labelSelector:
        matchLabels:
          karmada.io/scheduling: pinned-ottawa
    - apiVersion: postgresql.cnpg.io/v1
      kind: ScheduledBackup
      labelSelector:
        matchLabels:
          karmada.io/scheduling: pinned-ottawa

  placement:
    clusterAffinity:
      clusterNames:
        - talos-ottawa
---
# ClusterPropagationPolicy for workloads pinned to Robbinsdale
apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: pinned-robbinsdale
spec:
  resourceSelectors:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      labelSelector:
        matchLabels:
          karmada.io/scheduling: pinned-robbinsdale

  placement:
    clusterAffinity:
      clusterNames:
        - talos-robbinsdale
