---
apiVersion: network.keiretsu.ts.net/v1alpha1
kind: ServiceEgress
metadata:
  name: mimir
spec:
  endpoints:
    - name: mimir
      fqdn: mimir.keiretsu.ts.net
      ports:
        - name: http
          port: 8080
