---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission-books
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission-books
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: transmission-books
    spec:
      containers:
      - name: transmission-books
        image: linuxserver/transmission
        ports:
        - name: http
          containerPort: 9091
          protocol: TCP
        volumeMounts:
        - name: data-volume
          mountPath: /data
        - name: config-volume
          mountPath: /config
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: transmission-books-data-unas
      - name: config-volume
        persistentVolumeClaim:
          claimName: transmission-books-config-unas
