apiVersion: v1
kind: Secret
metadata:
    name: hermes-team-a-secrets
type: Opaque
stringData:
    API_SERVER_KEY: ENC[AES256_GCM,data:Z0ltyNTwbUNdE55ZUB7+0anRUWHyx9aKNN2h/8vR3i8Avzpe0/Z2za7/zQ9lpv4m,iv:SJtQfUQRaSBcMiX2aJi8AI2UTBjQEKV7pVh3hlMTqzU=,tag:KYyUAEdjWG0g9U08qCvP/g==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-07T20:26:07Z"
    mac: ENC[AES256_GCM,data:5L8CX94w+eQBjWBSiZmeFDhgaFThM0CIv9MoF3ziLA1dfyBVsong9G6/T3TBLJ4C2/mFFQxSmTnzF5kgkZhviKetSqXIIJejhWt0QS+N0q3Sq1Czk5y8MUFpVqe9GFJvWlxn3yZRcjCUWQgujpKTwgoC5nFHufkTm8D8P7yvcFE=,iv:zUEBXiCvv6G7pgQ/ofllaNXXTL0ePe35DQvJ/8HqmGc=,tag:lT1z6P4u5HP7NzvsEFpbqg==,type:str]
    pgp:
        - created_at: "2026-06-07T20:26:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveAQ//YyLWtJ530IBj8anAq2L9zA/7FoqTNKzUSYoeYVD/Ndoj
            axCGkbVsiKebjdOF39VoF7tjKt6U6xX9WVmvxajd/08ZE0auwoi6xC39fAEDutoE
            LCpKoF7MVOFJedIj1qpqj+Prj15OAKiKfUAxLohiyDWrzb0Q+ROOepFV4U2Giswc
            0pBQryfk0T2t6ny8JuwaZzjfWTvBQRD2q3tPmsNlmlAtjxqApVIt3FzfyunVSs+A
            pRK6d4okdl6EhqrmHNcl3apogiq537OqFtSSHxuWW77UZ3N3tGqZ8y7sphuXe/6q
            9oY+JQ2aGF2dFaAG3eIT9CzGl9lyZbceFSHFLMqjcrCfH2kwRCaNjDa7NhbsrTGE
            guk/Pym8+MaylVm3x0ms85ohrGWUgO1vf5bpNr8yXk6SsLpK/zrESeEoNbin/ytn
            56BA7m9oQvBbCAMj0tkKSdmrftZktHqrmffi98kqsIQhC8LoplxZ4HbKvpYabrK0
            ULrbshWD6vf6qKJQhmDiya7N+CV3VkmeYoHz7XWtxe+c7qwFx+J8U1/gERa8gklc
            EhCyMo3LqXLJwYVS/iDAnO0an6yudTQT6SpoHENILvSk/VdsxGiIw0jM0eBuBICi
            kSZVshx5uav3vALJhRzFiPuwZRPYOrNMTC90yWGGUqs6XlXKi3FgNOcsOSzrljTU
            aAEJAhDxRXWc7VyVsp7Y3hwNvYK9tIudA6YUDygvbB2MSHSP4v98XhNyrQag8OYc
            S94YIv6x5KqH/VktecXNXjhMHUNWPMaH3wLL4xGGxHkjfePTnwtmwTMwMq5d1Tco
            h12Xy2cCxwFc
            =LgUj
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: hermes-team-a-oidc
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:bjT41R2Zbg0FiRPB1De+yrd7gGJd6VAIP87Sf5cf13Y=,iv:BryOn+F3CXee+EaflNYApz+mX86EPry4hEDFUcDFRHw=,tag:0YTj62sB+/6CTpa0gdX7+g==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-07T20:26:07Z"
    mac: ENC[AES256_GCM,data:5L8CX94w+eQBjWBSiZmeFDhgaFThM0CIv9MoF3ziLA1dfyBVsong9G6/T3TBLJ4C2/mFFQxSmTnzF5kgkZhviKetSqXIIJejhWt0QS+N0q3Sq1Czk5y8MUFpVqe9GFJvWlxn3yZRcjCUWQgujpKTwgoC5nFHufkTm8D8P7yvcFE=,iv:zUEBXiCvv6G7pgQ/ofllaNXXTL0ePe35DQvJ/8HqmGc=,tag:lT1z6P4u5HP7NzvsEFpbqg==,type:str]
    pgp:
        - created_at: "2026-06-07T20:26:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveAQ//YyLWtJ530IBj8anAq2L9zA/7FoqTNKzUSYoeYVD/Ndoj
            axCGkbVsiKebjdOF39VoF7tjKt6U6xX9WVmvxajd/08ZE0auwoi6xC39fAEDutoE
            LCpKoF7MVOFJedIj1qpqj+Prj15OAKiKfUAxLohiyDWrzb0Q+ROOepFV4U2Giswc
            0pBQryfk0T2t6ny8JuwaZzjfWTvBQRD2q3tPmsNlmlAtjxqApVIt3FzfyunVSs+A
            pRK6d4okdl6EhqrmHNcl3apogiq537OqFtSSHxuWW77UZ3N3tGqZ8y7sphuXe/6q
            9oY+JQ2aGF2dFaAG3eIT9CzGl9lyZbceFSHFLMqjcrCfH2kwRCaNjDa7NhbsrTGE
            guk/Pym8+MaylVm3x0ms85ohrGWUgO1vf5bpNr8yXk6SsLpK/zrESeEoNbin/ytn
            56BA7m9oQvBbCAMj0tkKSdmrftZktHqrmffi98kqsIQhC8LoplxZ4HbKvpYabrK0
            ULrbshWD6vf6qKJQhmDiya7N+CV3VkmeYoHz7XWtxe+c7qwFx+J8U1/gERa8gklc
            EhCyMo3LqXLJwYVS/iDAnO0an6yudTQT6SpoHENILvSk/VdsxGiIw0jM0eBuBICi
            kSZVshx5uav3vALJhRzFiPuwZRPYOrNMTC90yWGGUqs6XlXKi3FgNOcsOSzrljTU
            aAEJAhDxRXWc7VyVsp7Y3hwNvYK9tIudA6YUDygvbB2MSHSP4v98XhNyrQag8OYc
            S94YIv6x5KqH/VktecXNXjhMHUNWPMaH3wLL4xGGxHkjfePTnwtmwTMwMq5d1Tco
            h12Xy2cCxwFc
            =LgUj
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    version: 3.13.1
