---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: karmada-qbittorrent-downloads
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: keiretsu-top
    name: qbittorrent-downloads
  csi:
    driver: ru.yandex.s3.csi
    volumeHandle: "csi-s3/qbittorrent-downloads"
    volumeAttributes:
      mounter: geesefs
      options: "--memory-limit 1000 --dir-mode 0777 --file-mode 0666"
    controllerPublishSecretRef:
      name: csi-s3-secret
      namespace: csi-s3
    nodePublishSecretRef:
      name: csi-s3-secret
      namespace: csi-s3
    nodeStageSecretRef:
      name: csi-s3-secret
      namespace: csi-s3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-downloads
  namespace: keiretsu-top
  labels:
    app: qbittorrent
    karmada.io/app: qbittorrent
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: karmada-qbittorrent-config
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: keiretsu-top
    name: qbittorrent-config
  csi:
    driver: ru.yandex.s3.csi
    volumeHandle: "csi-s3/qbittorrent-config"
    volumeAttributes:
      mounter: geesefs
      options: "--memory-limit 1000 --dir-mode 0777 --file-mode 0666"
    controllerPublishSecretRef:
      name: csi-s3-secret
      namespace: csi-s3
    nodePublishSecretRef:
      name: csi-s3-secret
      namespace: csi-s3
    nodeStageSecretRef:
      name: csi-s3-secret
      namespace: csi-s3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  namespace: keiretsu-top
  labels:
    app: qbittorrent
    karmada.io/app: qbittorrent
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
