---
apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent-vpn
  namespace: keiretsu-top
  labels:
    app: qbittorrent
type: Opaque
stringData:
  WIREGUARD_PRIVATE_KEY: ${QB_WIREGUARD_PRIVATE_KEY}
  UPDATER_PROTONVPN_EMAIL: ${QB_PROTONVPN_EMAIL}
  UPDATER_PROTONVPN_PASSWORD: ${QB_PROTONVPN_PASSWORD}
---
apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent-ts
  namespace: keiretsu-top
  labels:
    app: qbittorrent
type: Opaque
stringData:
  client_id: ${TS_OAUTH_CLIENT_ID}
  client_secret: ${TS_OAUTH_CLIENT_SECRET}
