---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: irqbalance
  namespace: kube-system
  labels:
    app: irqbalance
spec:
  selector:
    matchLabels:
      app: irqbalance
  template:
    metadata:
      labels:
        app: irqbalance
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      containers:
      - name: irqbalance
        image: ghcr.io/home-operations/irqbalance:1.9.5@sha256:a6d8c6f69c56f653022861ae7b1813cf41751dc5289a35d99075c9d113c29817
        command: ["/usr/sbin/irqbalance"]
        args: ["--foreground", "--journal"]
        env:
        - name: IRQBALANCE_BANNED_CPULIST
          value: "12-19"
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            memory: 128Mi
        securityContext:
          privileged: true
        volumeMounts:
        - name: run
          mountPath: /run/irqbalance
      volumes:
      - name: run
        emptyDir: {}
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
