apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./monitoring
  - ./auth
  - ./agent-sandbox-system
  - ./ai
  - ./border0
  - ./clickhouse-operator-system
  - ./clickhouse
  - ./cloudflare
  - ./cnpg-system
  - ./dragonfly-operator-system
  - ./fluent-bit
  - ./garage-operator-system
  - ./garage
  - ./gatus
  - ./gvisor
  - ./home-assistant
  - ./jellyswarrm
  - ./kube-system
  - ./loki
  - ./mimir
  - ./spegel
  - ./tailbench
  - ./volsync
  - ./zot