apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: teslamate-postgres
  namespace: teslamate
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  bootstrap:
    initdb:
      database: teslamate
      owner: teslamate
      dataChecksums: true
  monitoring:
    enablePodMonitor: true
  storage:
    size: 8Gi
