---
apiVersion: storage.keiretsu.ts.net/v1alpha1
kind: StorageStack
metadata:
  name: tautulli-config
  labels:
    keiretsu.ts.net/location: robbinsdale
spec:
  name: tautulli-config
  size: 5Gi
  storageClass: ceph-block-replicated-nvme
  s3Path: media/tautulli-config
  schedule: 0 4 * * *
  restoreMode: restore
  restorePaused: true
  copyMethod: Snapshot
