apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: garage
resources:
  - ottawa-garage-smb.yaml
  - ottawa-garage-localpath-shiro.yaml
  - ottawa-garage-localpath-kaji.yaml
  - ottawa-garage-localpath-asuka.yaml
  - ottawa-garage-localpath-rei.yaml
  - service-ts-storage.yaml
  - garage-rpc-dns.yaml