apiVersion: v1
kind: Secret
metadata:
    name: komga-scan-secret
    namespace: media
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:X/BuA+LVrzSLC8Yn6GWpSeJoXE0Cq6mpf4Zz3FB4Dlw=,iv:dazlfu6f047qj/a0eY1MT765DjGo6lIytxrQbY7wEF8=,tag:I6JQiEtdM0RrMuA4D9jXRQ==,type:str]
    comics-library-id: ENC[AES256_GCM,data:jHZ/ljowQc40oMtReA==,iv:FLEyxCb0zCGnZLd4OvGHCLqEyPPBFnYzi/+41tjmr7g=,tag:FemWd9YgoFyy0vVhxkSSsA==,type:str]
    manga-library-id: ENC[AES256_GCM,data:0sCRzYM2CQsR+r18Mw==,iv:CrqiBQDjzI1N5QBsG9txmKvgYIoAELOFJK565MwuwpE=,tag:qXDVvXbmBIVLboK6Cmvs9w==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T09:56:35Z"
    mac: ENC[AES256_GCM,data:MkDl9sYUmTCT6l+vHNUJ0QKJAtZleYUvErOwbmj64IPPXO+nMbXuxEuAauGcMy0XBZ17Igz6CGMmUXOxpZ591AewiHbJ6xnXGf6OlLJLDO0wAqo0hoG33M+fgs1NKHuhdjdIFWIBz98E2RqTrYTanaQ9O7G0NqA1bMA2/iM6qS8=,iv:V9qc2hng4JkRIRMkrH7htnBF0IvW9Dc5hY+dItNFcP8=,tag:eitcGyjIkzY0gdt4tkPEkg==,type:str]
    pgp:
        - created_at: "2026-08-03T09:56:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveAQ/+OpNqzXnMv6VlDFcigej/rNCb30T07FYkDojOPmb11apJ
            +AG2HFQohZmqlMx6AYf8K+/MZn6SiTEROgOXYObGdLug6JMQ5geNksZa96GgB6Yw
            0eFJmH+Hb60eUfYahrrybqydTTcVB/ZXUfekjChUOvcK21RcylETGFI18BPEqhrQ
            jFgkSqd4KEKLMLafyAufmybBtInwaw+5COBDDz/AwF8XCOqMmfgjOyhizt975QWI
            VHT+sMQ7rfqkEbSVXdbW6DV5X9TIXgd+3UHv+ptNb5dhF0j7Ev26DVFnV0pFgSo9
            nMdDTBxmbhzkhTDMAoEEVJDOmfCOl79VkEth373ODC+pkErSdSvW8X1C1NJGiNgv
            rrqasALNFHZbAxspmolnYe/NiMMN3jRF2WZwJyAZW9fE6f3LFdsJ/xdS/l6D4e29
            Lnax7WapQBMBiKX1Z2wWZOQQhL/p40rtASPWpjFj4Ohx6ftFc42rJ51YiRoWGJW/
            MgnWWHG+YibCVAXc3PK90GPK8K+b1z3Hp5DF1gCehcRCGuI6udoNbuJ2VkwK6nmt
            AlYRswdvmjaQ7CLRIsPBE88d1/MUX+/AAoO456n8W/M/cpqBiMMQixQFpqr0fISv
            ljJmjRPMaTVyKBk6AGFmbYhPz0s5lmX05oGdvh/0QkAv/9mmrUKDZ/uv8X5xeuzS
            XgFtvxGhguRaoxfou8UuZrP9JW5ybYZPO2Q00x3TAbaCfzSez+JPl71c8nsfrOBV
            ou/B+k7pVAkPjBg9X3E3Onc/YVRh5Ipc6W1jdBq/VFkH8+vXSZX7iEinmFHgw08=
            =ISE6
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    version: 3.13.3
