apiVersion: v1
kind: Secret
metadata:
    name: bookorbit-oidc-secret
    namespace: media
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:9JeBZvAWqh071P6ps3WThdno+UpH/WYfGbcpQkRV/1GCcGWK,iv:i3JmLo4agU9yJrr2qv3wJl20ZVC9QBNWAYF0NyZxTCk=,tag:rSIL+gGBhFxcyrqbfKxtVA==,type:str]
    client-secret: ENC[AES256_GCM,data:1vBfynPVfgoYMoH3q+YMCqHjypjxVk2S+EU+2dd3JKZJfnbQYZ330oVnYTDaO7Q=,iv:ieqvIuVAIBZayCMYVtU4FzBzzOevaRkPxS2/JqfWmJU=,tag:83zNPIIlXDZhDoNwrKrEYg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T03:49:09Z"
    mac: ENC[AES256_GCM,data:aZHfUUL2+zK+NY3pyT/MvNcCFrnjxMDKx1LPll3kxKCeee4P0XTZo6uZQjRHTH7j/hNcXUlANevLuRp470f5oczq/lnb4kpT9VDX8QkaK2sUOzch3736UqJKI2adaQt+yAKJtEfHT2DvEG5LEmo3BIS14Pex7uVJ+Db4MReNE2s=,iv:4MC4QuC9u3PY+fTg4/+bPXvzx5aPrZwipMXBZBOn4wI=,tag:29NlA5qco7/QERq6pvF0QQ==,type:str]
    pgp:
        - created_at: "2026-08-03T03:49:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveAQ/9HQmc9zCAv5Nyfk+kkmhY2dDewdZGGyrQ0VBAAwztFfaK
            8WqrxeO8fT1+kQbfmwAvP29H7Lp8MgcsaF4eJyEm735h6Cfc/sesPLahMvxP1luv
            ZT3+4VYeTBBcsRgmIMSL9Enlzrp+Dk0i4TMoXHR3GX/SMqNc2rYo3dmKKk7WfDRc
            3H5VF35wign/1RNJrrccxy77oB718bRvnfVvDhQYynlvnKDvD9A+vgE/pxUZNpfG
            50ueBDuVTIkPX22ZiZyr9MHy/FC72k33hNMTpkUpw9j2wHLyNHUV6xQUamUtHfz0
            ZFg7wtMG5YXpWzC7/GhsP0baO0WPhKVn4KC6dtVGY4w+ltgkfARp3QkFvhuKglKO
            zSHXQB6R18BN85Irxa6UlKwd/58gdx2Pj/4wDVK1lb2QicR3rNEAGUzlpStJ4WvW
            e+8//1xe95jsMZ7zOQgAqF4QnTfwo7jHKCfv9Xm8O6KPpaN+jZh73n9h8urAT/wY
            gCcWV+TvPHNR6Qitgf900t9StPlCuJfCowwkY2eJb0O3OhP9gk/YvjMbYE7++CL8
            vDqUCSxIEGLv9ss/IFhKPOREU/VxtRTkZuKUxRwxgMo9c2nc63FUT9/PAEpySVOZ
            d11D7M+x631EGzGRF9vDapHM1mjyQ0sT8tWRYOpWOOiDGjz+WLewBTQB6VoK8ibS
            XAHJjoY1IDjgkKUtd8b3ceC+/Zp4rF3LTKcm8CefpmCYVgpbqOoIfb7oqVkmmabi
            tR2eE6xpFoPhnq33em6oQc7ayu3wsrR3xmT6Zkk/t3lMQzhUxau4qk12nllE
            =MfbQ
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: omnibus-oidc-secret
    namespace: media
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:znHNYnzfFEQf1SkteMnTQ3Q4qrwWzNM0wWbzMhKaOQxY0KMv,iv:KtDiZeCoAtWx/2RpY9Fw7km+OpLy2Wz3nJsSHNmECKs=,tag:AfRwfkrYhrkv1MMz7mseeA==,type:str]
    client-secret: ENC[AES256_GCM,data:OzrgOsPE0zxMycZGMfXE7/j5d3czUUyarnLtLdZ5FwKW8NI4bmeXPSw9Omna2VU=,iv:lHqjhiwCYu9GHEK4GpN14CESGKh/h90g+DW0O8Ir6nM=,tag:0FF2nWTDqrUXqwMa6cVOWw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T03:49:09Z"
    mac: ENC[AES256_GCM,data:aZHfUUL2+zK+NY3pyT/MvNcCFrnjxMDKx1LPll3kxKCeee4P0XTZo6uZQjRHTH7j/hNcXUlANevLuRp470f5oczq/lnb4kpT9VDX8QkaK2sUOzch3736UqJKI2adaQt+yAKJtEfHT2DvEG5LEmo3BIS14Pex7uVJ+Db4MReNE2s=,iv:4MC4QuC9u3PY+fTg4/+bPXvzx5aPrZwipMXBZBOn4wI=,tag:29NlA5qco7/QERq6pvF0QQ==,type:str]
    pgp:
        - created_at: "2026-08-03T03:49:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveAQ/9HQmc9zCAv5Nyfk+kkmhY2dDewdZGGyrQ0VBAAwztFfaK
            8WqrxeO8fT1+kQbfmwAvP29H7Lp8MgcsaF4eJyEm735h6Cfc/sesPLahMvxP1luv
            ZT3+4VYeTBBcsRgmIMSL9Enlzrp+Dk0i4TMoXHR3GX/SMqNc2rYo3dmKKk7WfDRc
            3H5VF35wign/1RNJrrccxy77oB718bRvnfVvDhQYynlvnKDvD9A+vgE/pxUZNpfG
            50ueBDuVTIkPX22ZiZyr9MHy/FC72k33hNMTpkUpw9j2wHLyNHUV6xQUamUtHfz0
            ZFg7wtMG5YXpWzC7/GhsP0baO0WPhKVn4KC6dtVGY4w+ltgkfARp3QkFvhuKglKO
            zSHXQB6R18BN85Irxa6UlKwd/58gdx2Pj/4wDVK1lb2QicR3rNEAGUzlpStJ4WvW
            e+8//1xe95jsMZ7zOQgAqF4QnTfwo7jHKCfv9Xm8O6KPpaN+jZh73n9h8urAT/wY
            gCcWV+TvPHNR6Qitgf900t9StPlCuJfCowwkY2eJb0O3OhP9gk/YvjMbYE7++CL8
            vDqUCSxIEGLv9ss/IFhKPOREU/VxtRTkZuKUxRwxgMo9c2nc63FUT9/PAEpySVOZ
            d11D7M+x631EGzGRF9vDapHM1mjyQ0sT8tWRYOpWOOiDGjz+WLewBTQB6VoK8ibS
            XAHJjoY1IDjgkKUtd8b3ceC+/Zp4rF3LTKcm8CefpmCYVgpbqOoIfb7oqVkmmabi
            tR2eE6xpFoPhnq33em6oQc7ayu3wsrR3xmT6Zkk/t3lMQzhUxau4qk12nllE
            =MfbQ
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: shelfmark-oidc-secret
    namespace: media
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:gZ7nLTvl2T3G4j0m1SjS8Mqho9Wz6q22QHcVzktu12LCw5OB,iv:CAokC+jmKQnVQ0X3bt9MTJAuW8YQyTSCdFKJk0lw040=,tag:4iTqkvoNxoFeZ00Yw3fj0g==,type:str]
    client-secret: ENC[AES256_GCM,data:qWovXaE87fnSAQ646/wUDbKNkDSO6QdIGXTRCSN2uhGnXnjretz8tVyGXea0dwg=,iv:eR9mw9G+EZSsy+RdVCehVS/ogt7jHWaeQlKvXi8rx68=,tag:WVPXuLmFjehdBnslWNHceg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T03:49:09Z"
    mac: ENC[AES256_GCM,data:aZHfUUL2+zK+NY3pyT/MvNcCFrnjxMDKx1LPll3kxKCeee4P0XTZo6uZQjRHTH7j/hNcXUlANevLuRp470f5oczq/lnb4kpT9VDX8QkaK2sUOzch3736UqJKI2adaQt+yAKJtEfHT2DvEG5LEmo3BIS14Pex7uVJ+Db4MReNE2s=,iv:4MC4QuC9u3PY+fTg4/+bPXvzx5aPrZwipMXBZBOn4wI=,tag:29NlA5qco7/QERq6pvF0QQ==,type:str]
    pgp:
        - created_at: "2026-08-03T03:49:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveAQ/9HQmc9zCAv5Nyfk+kkmhY2dDewdZGGyrQ0VBAAwztFfaK
            8WqrxeO8fT1+kQbfmwAvP29H7Lp8MgcsaF4eJyEm735h6Cfc/sesPLahMvxP1luv
            ZT3+4VYeTBBcsRgmIMSL9Enlzrp+Dk0i4TMoXHR3GX/SMqNc2rYo3dmKKk7WfDRc
            3H5VF35wign/1RNJrrccxy77oB718bRvnfVvDhQYynlvnKDvD9A+vgE/pxUZNpfG
            50ueBDuVTIkPX22ZiZyr9MHy/FC72k33hNMTpkUpw9j2wHLyNHUV6xQUamUtHfz0
            ZFg7wtMG5YXpWzC7/GhsP0baO0WPhKVn4KC6dtVGY4w+ltgkfARp3QkFvhuKglKO
            zSHXQB6R18BN85Irxa6UlKwd/58gdx2Pj/4wDVK1lb2QicR3rNEAGUzlpStJ4WvW
            e+8//1xe95jsMZ7zOQgAqF4QnTfwo7jHKCfv9Xm8O6KPpaN+jZh73n9h8urAT/wY
            gCcWV+TvPHNR6Qitgf900t9StPlCuJfCowwkY2eJb0O3OhP9gk/YvjMbYE7++CL8
            vDqUCSxIEGLv9ss/IFhKPOREU/VxtRTkZuKUxRwxgMo9c2nc63FUT9/PAEpySVOZ
            d11D7M+x631EGzGRF9vDapHM1mjyQ0sT8tWRYOpWOOiDGjz+WLewBTQB6VoK8ibS
            XAHJjoY1IDjgkKUtd8b3ceC+/Zp4rF3LTKcm8CefpmCYVgpbqOoIfb7oqVkmmabi
            tR2eE6xpFoPhnq33em6oQc7ayu3wsrR3xmT6Zkk/t3lMQzhUxau4qk12nllE
            =MfbQ
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: komga-oidc-secret
    namespace: media
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:DVctc4UlJat9fh2FSZBC+vu5qvIDasD7OSmpQcbj5vliclQk,iv:EXKP+db5Na4YGyOe3ovwOeAzC7gYGf98Go2NClizn4E=,tag:Kj8pwkbOOd2Tp4u/PTS7/A==,type:str]
    client-secret: ENC[AES256_GCM,data:R4hj2XymK3NDVLf2tgZ6Qa0kP59y5YMfELLS5C0DNZ57Ktz9m1+NBVKbko2KDFc=,iv:1Kn/5P/fa+42jwM41bxuFnVRMlTY9kRlwfWv+7ZUQ7M=,tag:kCLtHjClayGhwAy2Qvv5Xw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T03:49:09Z"
    mac: ENC[AES256_GCM,data:aZHfUUL2+zK+NY3pyT/MvNcCFrnjxMDKx1LPll3kxKCeee4P0XTZo6uZQjRHTH7j/hNcXUlANevLuRp470f5oczq/lnb4kpT9VDX8QkaK2sUOzch3736UqJKI2adaQt+yAKJtEfHT2DvEG5LEmo3BIS14Pex7uVJ+Db4MReNE2s=,iv:4MC4QuC9u3PY+fTg4/+bPXvzx5aPrZwipMXBZBOn4wI=,tag:29NlA5qco7/QERq6pvF0QQ==,type:str]
    pgp:
        - created_at: "2026-08-03T03:49:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveAQ/9HQmc9zCAv5Nyfk+kkmhY2dDewdZGGyrQ0VBAAwztFfaK
            8WqrxeO8fT1+kQbfmwAvP29H7Lp8MgcsaF4eJyEm735h6Cfc/sesPLahMvxP1luv
            ZT3+4VYeTBBcsRgmIMSL9Enlzrp+Dk0i4TMoXHR3GX/SMqNc2rYo3dmKKk7WfDRc
            3H5VF35wign/1RNJrrccxy77oB718bRvnfVvDhQYynlvnKDvD9A+vgE/pxUZNpfG
            50ueBDuVTIkPX22ZiZyr9MHy/FC72k33hNMTpkUpw9j2wHLyNHUV6xQUamUtHfz0
            ZFg7wtMG5YXpWzC7/GhsP0baO0WPhKVn4KC6dtVGY4w+ltgkfARp3QkFvhuKglKO
            zSHXQB6R18BN85Irxa6UlKwd/58gdx2Pj/4wDVK1lb2QicR3rNEAGUzlpStJ4WvW
            e+8//1xe95jsMZ7zOQgAqF4QnTfwo7jHKCfv9Xm8O6KPpaN+jZh73n9h8urAT/wY
            gCcWV+TvPHNR6Qitgf900t9StPlCuJfCowwkY2eJb0O3OhP9gk/YvjMbYE7++CL8
            vDqUCSxIEGLv9ss/IFhKPOREU/VxtRTkZuKUxRwxgMo9c2nc63FUT9/PAEpySVOZ
            d11D7M+x631EGzGRF9vDapHM1mjyQ0sT8tWRYOpWOOiDGjz+WLewBTQB6VoK8ibS
            XAHJjoY1IDjgkKUtd8b3ceC+/Zp4rF3LTKcm8CefpmCYVgpbqOoIfb7oqVkmmabi
            tR2eE6xpFoPhnq33em6oQc7ayu3wsrR3xmT6Zkk/t3lMQzhUxau4qk12nllE
            =MfbQ
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: audiobookshelf-oidc-secret
    namespace: media
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:dRzy7NzMr7oQtVgaagfEfes1RiDFf5AGvJzAQoy/rP0eF9ES,iv:dxoHqor0l5B0VdZscySu0Ow4j5iJhiRKrAyG1um8Lkc=,tag:dTZJHQ6fKo/BagDxGq5fFw==,type:str]
    client-secret: ENC[AES256_GCM,data:ZP05GU79q/7LdKjed3JaFh9LLVX1HSZPm1zbuEHzr8E+YxpeHaK6bLJqyQ/8fUE=,iv:nWHHqIG4/bfDIBDrnhOyNCCnFUV0lseNoWpW+qDvBco=,tag:LqC5XLtobm0J0ndfGY/KKw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T03:49:09Z"
    mac: ENC[AES256_GCM,data:aZHfUUL2+zK+NY3pyT/MvNcCFrnjxMDKx1LPll3kxKCeee4P0XTZo6uZQjRHTH7j/hNcXUlANevLuRp470f5oczq/lnb4kpT9VDX8QkaK2sUOzch3736UqJKI2adaQt+yAKJtEfHT2DvEG5LEmo3BIS14Pex7uVJ+Db4MReNE2s=,iv:4MC4QuC9u3PY+fTg4/+bPXvzx5aPrZwipMXBZBOn4wI=,tag:29NlA5qco7/QERq6pvF0QQ==,type:str]
    pgp:
        - created_at: "2026-08-03T03:49:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveAQ/9HQmc9zCAv5Nyfk+kkmhY2dDewdZGGyrQ0VBAAwztFfaK
            8WqrxeO8fT1+kQbfmwAvP29H7Lp8MgcsaF4eJyEm735h6Cfc/sesPLahMvxP1luv
            ZT3+4VYeTBBcsRgmIMSL9Enlzrp+Dk0i4TMoXHR3GX/SMqNc2rYo3dmKKk7WfDRc
            3H5VF35wign/1RNJrrccxy77oB718bRvnfVvDhQYynlvnKDvD9A+vgE/pxUZNpfG
            50ueBDuVTIkPX22ZiZyr9MHy/FC72k33hNMTpkUpw9j2wHLyNHUV6xQUamUtHfz0
            ZFg7wtMG5YXpWzC7/GhsP0baO0WPhKVn4KC6dtVGY4w+ltgkfARp3QkFvhuKglKO
            zSHXQB6R18BN85Irxa6UlKwd/58gdx2Pj/4wDVK1lb2QicR3rNEAGUzlpStJ4WvW
            e+8//1xe95jsMZ7zOQgAqF4QnTfwo7jHKCfv9Xm8O6KPpaN+jZh73n9h8urAT/wY
            gCcWV+TvPHNR6Qitgf900t9StPlCuJfCowwkY2eJb0O3OhP9gk/YvjMbYE7++CL8
            vDqUCSxIEGLv9ss/IFhKPOREU/VxtRTkZuKUxRwxgMo9c2nc63FUT9/PAEpySVOZ
            d11D7M+x631EGzGRF9vDapHM1mjyQ0sT8tWRYOpWOOiDGjz+WLewBTQB6VoK8ibS
            XAHJjoY1IDjgkKUtd8b3ceC+/Zp4rF3LTKcm8CefpmCYVgpbqOoIfb7oqVkmmabi
            tR2eE6xpFoPhnq33em6oQc7ayu3wsrR3xmT6Zkk/t3lMQzhUxau4qk12nllE
            =MfbQ
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: bookorbit-app-secret
    namespace: media
type: Opaque
stringData:
    jwt-secret: ENC[AES256_GCM,data:9z0sER7j+Y8Ck0NorO2qMD9sAxApNYs26CIN/ABQoN4fn0hh5vOXylj35g==,iv:3B8XJvk5DCjQb/bheqRukSo14q37gKAzgZbwuBTeSUY=,tag:oUE+LbQZz+R8dajK1gLjXA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T03:49:09Z"
    mac: ENC[AES256_GCM,data:aZHfUUL2+zK+NY3pyT/MvNcCFrnjxMDKx1LPll3kxKCeee4P0XTZo6uZQjRHTH7j/hNcXUlANevLuRp470f5oczq/lnb4kpT9VDX8QkaK2sUOzch3736UqJKI2adaQt+yAKJtEfHT2DvEG5LEmo3BIS14Pex7uVJ+Db4MReNE2s=,iv:4MC4QuC9u3PY+fTg4/+bPXvzx5aPrZwipMXBZBOn4wI=,tag:29NlA5qco7/QERq6pvF0QQ==,type:str]
    pgp:
        - created_at: "2026-08-03T03:49:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveAQ/9HQmc9zCAv5Nyfk+kkmhY2dDewdZGGyrQ0VBAAwztFfaK
            8WqrxeO8fT1+kQbfmwAvP29H7Lp8MgcsaF4eJyEm735h6Cfc/sesPLahMvxP1luv
            ZT3+4VYeTBBcsRgmIMSL9Enlzrp+Dk0i4TMoXHR3GX/SMqNc2rYo3dmKKk7WfDRc
            3H5VF35wign/1RNJrrccxy77oB718bRvnfVvDhQYynlvnKDvD9A+vgE/pxUZNpfG
            50ueBDuVTIkPX22ZiZyr9MHy/FC72k33hNMTpkUpw9j2wHLyNHUV6xQUamUtHfz0
            ZFg7wtMG5YXpWzC7/GhsP0baO0WPhKVn4KC6dtVGY4w+ltgkfARp3QkFvhuKglKO
            zSHXQB6R18BN85Irxa6UlKwd/58gdx2Pj/4wDVK1lb2QicR3rNEAGUzlpStJ4WvW
            e+8//1xe95jsMZ7zOQgAqF4QnTfwo7jHKCfv9Xm8O6KPpaN+jZh73n9h8urAT/wY
            gCcWV+TvPHNR6Qitgf900t9StPlCuJfCowwkY2eJb0O3OhP9gk/YvjMbYE7++CL8
            vDqUCSxIEGLv9ss/IFhKPOREU/VxtRTkZuKUxRwxgMo9c2nc63FUT9/PAEpySVOZ
            d11D7M+x631EGzGRF9vDapHM1mjyQ0sT8tWRYOpWOOiDGjz+WLewBTQB6VoK8ibS
            XAHJjoY1IDjgkKUtd8b3ceC+/Zp4rF3LTKcm8CefpmCYVgpbqOoIfb7oqVkmmabi
            tR2eE6xpFoPhnq33em6oQc7ayu3wsrR3xmT6Zkk/t3lMQzhUxau4qk12nllE
            =MfbQ
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    version: 3.13.3
