apiVersion: ENC[AES256_GCM,data:MoQ=,iv:qHb2zmFOobIBXw1PeRlTpHMiHW6o7BR9avDQ73diU5Q=,tag:Mdc5pF9AZMFzmpQR3nRQxA==,type:str]
kind: ENC[AES256_GCM,data:pkfLfXBd,iv:+05D37koLq59Qhd65OfwIt5DbQvHGq90JkprHuZHjTo=,tag:DUVs6SBk25tWykM7y0oy6g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+litUQ65IgR1N98RXQOZ8ApncWHr,iv:eNCkMtbXzMFby0RVzQD+MSnO0zL6tvdov/QrbWPnzr4=,tag:WRmW73jguuEb7UfCSVqAkg==,type:str]
    namespace: ENC[AES256_GCM,data:/L51pRQ=,iv:BRVh6fCebREVVC7dOY56BktpS5FAiOpqubOsrZHIdc8=,tag:r/JMK9epznwPF9SS6yNSDA==,type:str]
type: ENC[AES256_GCM,data:7kB4W2cX,iv:CmNWIYyqQpSY8cQGleCkroua464FZA1wegFLN+Ei4c4=,tag:fox5aH/laat7PxVr23HaxA==,type:str]
stringData:
    client-id: ENC[AES256_GCM,data:moS7cMnMbWRg+yA65eWMY0bIcpXqx4DcgQm2Xz2AP76Gg3Wh,iv:qx2o4Q5owgH8wDSztiym4QWFexkydpWQrBbJg0aAY7Q=,tag:QsvNGvpDlT+nfkdxidW6zA==,type:str]
    client-secret: ENC[AES256_GCM,data:P3DxSQy3JhwRBst1mYDq7Px6hx1AwxMvta21at7/QylXLc6aW2kxnVtTqAzjqXk=,iv:y/4o6n1LhphmOmiBmQpO+373mEsgAdut7sKDZdOEelo=,tag:3WlrejKzhWXGjzXLo+I5sw==,type:str]
sops:
    lastmodified: "2026-08-03T03:23:27Z"
    mac: ENC[AES256_GCM,data:eZ1vOgHVgQTn4y1Fm2DEq/SCBEkedoneaO2l1LOu8wW4fC72ShX39UqH2QDi+NOEXbkb1Wms3toqQCqSneDvXGQ5sCjcor9MDp+Dd5umlVwahDVxzjiIWOmHwWoHawMGXOlOCsKUyPUk4yhuUtlgA924UJmbAbRk1B0Nmw1sRD8=,iv:9N/SdemBOpxSl1m5EVjfBkpnbehM8C71Lm2R1hp4Clc=,tag:fCRiWttqdQ5OPPZPP5cgPA==,type:str]
    pgp:
        - created_at: "2026-08-03T03:23:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveAQ//fwOiRk6bjhc4YiMGE19aYyi0DYdmhcK7+nAthRFSEiBH
            tDmwNI1lpF9h9BJqdQuoxeDrubvq9ZkA5Ly8U6oftb/ix2Nm9nn1zD1n6Mje3rsB
            K55m6Upf1AlyUFaWN8sHzxqvXX1zdy7CK4LY3/Le0XPh8kH1ZmwtC6Kg0rGlsnrA
            Lk0OwRNM2DSW4nimYe5Jr5wtPe3tBwpQgWKOMMozqUvHn7PcFcKsyARNbfkaG/ln
            VCIBrRlTSGyKsR/s5qc27djKFWsIETSfDNhoWL47cumudhPl5WYQ2Yqy+E3mbuBz
            L/NQJQ/DnEogc7gXSeMvjtnm+cG+Ps4lpEDVlughtvifPiF831XlIp12MFKi/zJw
            yfav4/z7yGKu/gnKYGL4LCiOuBQ1o/SUTd0+K0AyItmjIdt9MQ0/WqmLz+Ivsx9x
            NsYNtm3bsgV5SrEMb9ih6OfbYryR8gQ7Zqu/LppUTT0J0pGZHXQ6WkdzbY4cVtDZ
            OuE80iab0feevwcZYzzSlYZ4GMwzc2wxhs/h2xJK+BWM8wZcgMhDxaK6gGU0Mk9U
            WBSulRPghm4ae89eB4CV98tqBvUSjzyNAD49zdWR+P0+m5+rWQdMqrE4gghtEEqY
            gux1SAunFUYzBl99ZXYpXoIuHsI5mAPNZZD9vlnXCj1zPrl8OnPim91PNCe9EE/S
            XAE/+m7gRaZjE72GSyLHxeDRfmvNrOlXMHonLzptRiA9JKxHiebhcI9LhUL80swf
            aHCuSHwTAm2fjCuSV7HoWELTEi0eImMD4S4AP+qaEEIlsMtOJxDAO3WZBsFO
            =0UZj
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    unencrypted_suffix: _unencrypted
    version: 3.13.3
---
apiVersion: ENC[AES256_GCM,data:QIg=,iv:OP33arXeVJq5v9j6YUkq3Jbg6wxU04PyDLFf3QtWONU=,tag:c4ze7MUXuPrkh2qSu8vSmg==,type:str]
kind: ENC[AES256_GCM,data:zmpAECya,iv:jC7FWYUBHd93eJt2EBuIzXwLwzv6vcaiI6uPgy1wcA8=,tag:xxsb4DNoWM6Z7LKIE5J4Rw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:bvfswD1WPnV9kICX6+C3QGxETA==,iv:1X/9KoVnOSY4vdSdWSOi8Md0+Ao2NbGf5czDEcGya/4=,tag:jwqFPZ/5fMZyFwH7Nv0BTg==,type:str]
    namespace: ENC[AES256_GCM,data:kdCZ5oQ=,iv:MmyUO0WWvMQ+SQ7DoTsHzwTE35tlKLHwMFCa2zxxU0c=,tag:03CRYnE8qtM5tPhOaImgqw==,type:str]
type: ENC[AES256_GCM,data:2J3xI9Ej,iv:lyDzuIsf8dyC1pnpzo+TSpJJBkJ7/rANIxb9mB3aWTs=,tag:sYxFDbxbq89vjRYAOnFfsA==,type:str]
stringData:
    client-id: ENC[AES256_GCM,data:d2SHl2ijG03ZkOuKc29tGNHlh5e/KdftD8mx6OAwtmPNWaBc,iv:fGwF2mpuYGtDmV0CNUjzCZJ2QVpF8lFy8U9R7X+5xZQ=,tag:3jDmM2n6VLjdHH0HfOwjZw==,type:str]
    client-secret: ENC[AES256_GCM,data:kQhyDz5PCE1L3tNGlYYQPXsUuiEgT5kBJV20wmew2eiJGbxrgirCqSGSCurbUwo=,iv:No9EknQjU2byXhMNDVz6t99fCv5s6K1/QnohcKXLIt0=,tag:LG9A5M/JzQ/ky81MaiPrzg==,type:str]
sops:
    lastmodified: "2026-08-03T03:23:27Z"
    mac: ENC[AES256_GCM,data:eZ1vOgHVgQTn4y1Fm2DEq/SCBEkedoneaO2l1LOu8wW4fC72ShX39UqH2QDi+NOEXbkb1Wms3toqQCqSneDvXGQ5sCjcor9MDp+Dd5umlVwahDVxzjiIWOmHwWoHawMGXOlOCsKUyPUk4yhuUtlgA924UJmbAbRk1B0Nmw1sRD8=,iv:9N/SdemBOpxSl1m5EVjfBkpnbehM8C71Lm2R1hp4Clc=,tag:fCRiWttqdQ5OPPZPP5cgPA==,type:str]
    pgp:
        - created_at: "2026-08-03T03:23:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveAQ//fwOiRk6bjhc4YiMGE19aYyi0DYdmhcK7+nAthRFSEiBH
            tDmwNI1lpF9h9BJqdQuoxeDrubvq9ZkA5Ly8U6oftb/ix2Nm9nn1zD1n6Mje3rsB
            K55m6Upf1AlyUFaWN8sHzxqvXX1zdy7CK4LY3/Le0XPh8kH1ZmwtC6Kg0rGlsnrA
            Lk0OwRNM2DSW4nimYe5Jr5wtPe3tBwpQgWKOMMozqUvHn7PcFcKsyARNbfkaG/ln
            VCIBrRlTSGyKsR/s5qc27djKFWsIETSfDNhoWL47cumudhPl5WYQ2Yqy+E3mbuBz
            L/NQJQ/DnEogc7gXSeMvjtnm+cG+Ps4lpEDVlughtvifPiF831XlIp12MFKi/zJw
            yfav4/z7yGKu/gnKYGL4LCiOuBQ1o/SUTd0+K0AyItmjIdt9MQ0/WqmLz+Ivsx9x
            NsYNtm3bsgV5SrEMb9ih6OfbYryR8gQ7Zqu/LppUTT0J0pGZHXQ6WkdzbY4cVtDZ
            OuE80iab0feevwcZYzzSlYZ4GMwzc2wxhs/h2xJK+BWM8wZcgMhDxaK6gGU0Mk9U
            WBSulRPghm4ae89eB4CV98tqBvUSjzyNAD49zdWR+P0+m5+rWQdMqrE4gghtEEqY
            gux1SAunFUYzBl99ZXYpXoIuHsI5mAPNZZD9vlnXCj1zPrl8OnPim91PNCe9EE/S
            XAE/+m7gRaZjE72GSyLHxeDRfmvNrOlXMHonLzptRiA9JKxHiebhcI9LhUL80swf
            aHCuSHwTAm2fjCuSV7HoWELTEi0eImMD4S4AP+qaEEIlsMtOJxDAO3WZBsFO
            =0UZj
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    unencrypted_suffix: _unencrypted
    version: 3.13.3
---
apiVersion: ENC[AES256_GCM,data:liE=,iv:zbkJEjaguru9aBqP7n9PZFGddUmp7lknkDdQCqNpntE=,tag:3Zb4bED3i3X1Hfu9tcAU8w==,type:str]
kind: ENC[AES256_GCM,data:78yMHZs1,iv:hnSehpO9kaGAgZaWUxLdWfkb8sGVg/zbJsann7CfOiY=,tag:HO9Q/geNuS7FMzi6W95+pQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:jHs39TNkwIHWi/pDt4C0JAJWwH+I,iv:eJrufPVRw48BCcvBiwuKiYUYLGkbrfHA6Jjw64NHeBA=,tag:85qcwkTAUoOE7PaWIv/pjw==,type:str]
    namespace: ENC[AES256_GCM,data:m62T8ow=,iv:LkaMkQ3APtOzeWcgYfIQDugz3OPgnOTvd771nrZfLXM=,tag:QorN421kh5JDKOeryGZKpg==,type:str]
type: ENC[AES256_GCM,data:G0wIoRhh,iv:cNg00R+/fjSS2kEWIrtSsBiBUOuKWbpL0x15+4PcpX0=,tag:VDa2lbwW2n9yWqbZ0xbgTw==,type:str]
stringData:
    client-id: ENC[AES256_GCM,data:hl195d4kibcXqiOg8O6Y59K9cSYHGgmSyYcV3ydOJvUe9dqS,iv:itpMLcfLOm93b9iT3F9zrpGlRoMZU7I2DCo4mm4SK9E=,tag:qmr3NXY//c0kyhOtsldDYA==,type:str]
    client-secret: ENC[AES256_GCM,data:ib6DvAM7yx21f1L0Ngw0Wg48im81LPO+NL7rsX52lTiU+dKtQSDqxFFwzrHc5mY=,iv:u31LQuIJfK4Ost446KUuW/9Lvxsb/MnsQ3qBWWEWEhA=,tag:uXhN0IgkrrFW1B/hcLaJLQ==,type:str]
sops:
    lastmodified: "2026-08-03T03:23:27Z"
    mac: ENC[AES256_GCM,data:eZ1vOgHVgQTn4y1Fm2DEq/SCBEkedoneaO2l1LOu8wW4fC72ShX39UqH2QDi+NOEXbkb1Wms3toqQCqSneDvXGQ5sCjcor9MDp+Dd5umlVwahDVxzjiIWOmHwWoHawMGXOlOCsKUyPUk4yhuUtlgA924UJmbAbRk1B0Nmw1sRD8=,iv:9N/SdemBOpxSl1m5EVjfBkpnbehM8C71Lm2R1hp4Clc=,tag:fCRiWttqdQ5OPPZPP5cgPA==,type:str]
    pgp:
        - created_at: "2026-08-03T03:23:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveAQ//fwOiRk6bjhc4YiMGE19aYyi0DYdmhcK7+nAthRFSEiBH
            tDmwNI1lpF9h9BJqdQuoxeDrubvq9ZkA5Ly8U6oftb/ix2Nm9nn1zD1n6Mje3rsB
            K55m6Upf1AlyUFaWN8sHzxqvXX1zdy7CK4LY3/Le0XPh8kH1ZmwtC6Kg0rGlsnrA
            Lk0OwRNM2DSW4nimYe5Jr5wtPe3tBwpQgWKOMMozqUvHn7PcFcKsyARNbfkaG/ln
            VCIBrRlTSGyKsR/s5qc27djKFWsIETSfDNhoWL47cumudhPl5WYQ2Yqy+E3mbuBz
            L/NQJQ/DnEogc7gXSeMvjtnm+cG+Ps4lpEDVlughtvifPiF831XlIp12MFKi/zJw
            yfav4/z7yGKu/gnKYGL4LCiOuBQ1o/SUTd0+K0AyItmjIdt9MQ0/WqmLz+Ivsx9x
            NsYNtm3bsgV5SrEMb9ih6OfbYryR8gQ7Zqu/LppUTT0J0pGZHXQ6WkdzbY4cVtDZ
            OuE80iab0feevwcZYzzSlYZ4GMwzc2wxhs/h2xJK+BWM8wZcgMhDxaK6gGU0Mk9U
            WBSulRPghm4ae89eB4CV98tqBvUSjzyNAD49zdWR+P0+m5+rWQdMqrE4gghtEEqY
            gux1SAunFUYzBl99ZXYpXoIuHsI5mAPNZZD9vlnXCj1zPrl8OnPim91PNCe9EE/S
            XAE/+m7gRaZjE72GSyLHxeDRfmvNrOlXMHonLzptRiA9JKxHiebhcI9LhUL80swf
            aHCuSHwTAm2fjCuSV7HoWELTEi0eImMD4S4AP+qaEEIlsMtOJxDAO3WZBsFO
            =0UZj
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    unencrypted_suffix: _unencrypted
    version: 3.13.3
---
apiVersion: ENC[AES256_GCM,data:2jE=,iv:gu+3lUgazjySS3BGjG8Ln4XZgYB/XlP8ozOFzZhZw8Y=,tag:ah5bkVGw2Nx75s84SmTf3A==,type:str]
kind: ENC[AES256_GCM,data:SepPFaZi,iv:cEehXxjgP4t8zDCyo3j4R3shOAQ63rlZD/4Dy/irNDY=,tag:Vw6DOQo8/hxKPLrsJfgiwg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:FxZGgsZUpIiPitjrMIrwWyk=,iv:WbrFFJky+w4K1lt72yYtcq9UbOFGoP+5h4WEUXVsTsg=,tag:vTsBlfanrdz2cVQUC2zj9Q==,type:str]
    namespace: ENC[AES256_GCM,data:Jbn1GxM=,iv:Vr/lL/75HKQjsVmsSkRLzt3bkgt07GOqYTrrN5mgQo0=,tag:27+cU6kRTSiVAAumgT9tyw==,type:str]
type: ENC[AES256_GCM,data:90yPvOh5,iv:A2ZROGBYrSHs/Nwo4l29o84bHIuPI8L7YwYiMGp2fbE=,tag:RY0uRVCIQcaRiwA5dWIu/w==,type:str]
stringData:
    client-id: ENC[AES256_GCM,data:BtRQr/tjlGmsWkaElK/3mUdpdpY3SIt8wf390u+u7Qg/oy5T,iv:u3csExRkTYsIcYgxeX2gytUEq2H9+Ql3HLgc4tBq1kA=,tag:21CwjBz6lHD/cYwNUVr/Kw==,type:str]
    client-secret: ENC[AES256_GCM,data:Cs45fK2RSD17TnFyp28pBHPcnFkdcB3HyUnKiTksI4IoYRgkyZM9brx8w80g8/k=,iv:BhHU0ZOPZZLg77pefkRxNxyaowh0ArTwZzAXW/sFhaw=,tag:yO8IFVQQcs3JdMvhoqiaQg==,type:str]
sops:
    lastmodified: "2026-08-03T03:23:27Z"
    mac: ENC[AES256_GCM,data:eZ1vOgHVgQTn4y1Fm2DEq/SCBEkedoneaO2l1LOu8wW4fC72ShX39UqH2QDi+NOEXbkb1Wms3toqQCqSneDvXGQ5sCjcor9MDp+Dd5umlVwahDVxzjiIWOmHwWoHawMGXOlOCsKUyPUk4yhuUtlgA924UJmbAbRk1B0Nmw1sRD8=,iv:9N/SdemBOpxSl1m5EVjfBkpnbehM8C71Lm2R1hp4Clc=,tag:fCRiWttqdQ5OPPZPP5cgPA==,type:str]
    pgp:
        - created_at: "2026-08-03T03:23:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveAQ//fwOiRk6bjhc4YiMGE19aYyi0DYdmhcK7+nAthRFSEiBH
            tDmwNI1lpF9h9BJqdQuoxeDrubvq9ZkA5Ly8U6oftb/ix2Nm9nn1zD1n6Mje3rsB
            K55m6Upf1AlyUFaWN8sHzxqvXX1zdy7CK4LY3/Le0XPh8kH1ZmwtC6Kg0rGlsnrA
            Lk0OwRNM2DSW4nimYe5Jr5wtPe3tBwpQgWKOMMozqUvHn7PcFcKsyARNbfkaG/ln
            VCIBrRlTSGyKsR/s5qc27djKFWsIETSfDNhoWL47cumudhPl5WYQ2Yqy+E3mbuBz
            L/NQJQ/DnEogc7gXSeMvjtnm+cG+Ps4lpEDVlughtvifPiF831XlIp12MFKi/zJw
            yfav4/z7yGKu/gnKYGL4LCiOuBQ1o/SUTd0+K0AyItmjIdt9MQ0/WqmLz+Ivsx9x
            NsYNtm3bsgV5SrEMb9ih6OfbYryR8gQ7Zqu/LppUTT0J0pGZHXQ6WkdzbY4cVtDZ
            OuE80iab0feevwcZYzzSlYZ4GMwzc2wxhs/h2xJK+BWM8wZcgMhDxaK6gGU0Mk9U
            WBSulRPghm4ae89eB4CV98tqBvUSjzyNAD49zdWR+P0+m5+rWQdMqrE4gghtEEqY
            gux1SAunFUYzBl99ZXYpXoIuHsI5mAPNZZD9vlnXCj1zPrl8OnPim91PNCe9EE/S
            XAE/+m7gRaZjE72GSyLHxeDRfmvNrOlXMHonLzptRiA9JKxHiebhcI9LhUL80swf
            aHCuSHwTAm2fjCuSV7HoWELTEi0eImMD4S4AP+qaEEIlsMtOJxDAO3WZBsFO
            =0UZj
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    unencrypted_suffix: _unencrypted
    version: 3.13.3
---
apiVersion: ENC[AES256_GCM,data:NHM=,iv:T2IOad+CLPg2Vo51a6lzRPtMrFmQQTfRPTKx6Tlj2dk=,tag:CUbndr+rHNVpQqvG6AirSw==,type:str]
kind: ENC[AES256_GCM,data:VkToBypS,iv:TdnDCMbROunVfXYtExWvWTPDpZE76dWvcaN0Ix/a9Pg=,tag:nIrv/nm0duP3u80GjLU3WQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:exOMFsq3aihTjFHIdT8bPDryKX+I+c4xH88=,iv:xLR4DVc3Dl24c0zyK/DfpxdiXyBSKYC6WfCMhDvMk7I=,tag:iM8MZvL7GAnsNN0VBVuCjw==,type:str]
    namespace: ENC[AES256_GCM,data:zAuOEMI=,iv:n0eqvdPFZHl0PFTIcqUQ4lixOcz0IUJbvBCYb1b0RxQ=,tag:ukb6TA6iVVXT7kqW/yIYJA==,type:str]
type: ENC[AES256_GCM,data:vVr97oTW,iv:SNzENoGDH9LkS4h7/NQa79el+P2DXjI/jJEIEJRlEDA=,tag:8FFDKgmcmxK4530UTfeTcw==,type:str]
stringData:
    client-id: ENC[AES256_GCM,data:7bf8XbcyMS580shZqYT+CrP5icYTZa/UtBmUqjrDVu20L/bu,iv:mxvlL0tdRXvkjJV42RKh/Ddk02FmbBsUCPupPIIn9/k=,tag:vzjVtTOAIYjRakSvt+FgZw==,type:str]
    client-secret: ENC[AES256_GCM,data:Xos+4hMUPrFVDKDlsXIa6ATFNIQpyt7M49fk0zVQePlAODNlBLA7pRps1EHbliY=,iv:T8bpO/I90J6778eQSzyKVl3/H9u6zIVuS/5xiQSfZ+0=,tag:G1JpTj8aReZWmbLDrScFgA==,type:str]
sops:
    lastmodified: "2026-08-03T03:23:27Z"
    mac: ENC[AES256_GCM,data:eZ1vOgHVgQTn4y1Fm2DEq/SCBEkedoneaO2l1LOu8wW4fC72ShX39UqH2QDi+NOEXbkb1Wms3toqQCqSneDvXGQ5sCjcor9MDp+Dd5umlVwahDVxzjiIWOmHwWoHawMGXOlOCsKUyPUk4yhuUtlgA924UJmbAbRk1B0Nmw1sRD8=,iv:9N/SdemBOpxSl1m5EVjfBkpnbehM8C71Lm2R1hp4Clc=,tag:fCRiWttqdQ5OPPZPP5cgPA==,type:str]
    pgp:
        - created_at: "2026-08-03T03:23:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveAQ//fwOiRk6bjhc4YiMGE19aYyi0DYdmhcK7+nAthRFSEiBH
            tDmwNI1lpF9h9BJqdQuoxeDrubvq9ZkA5Ly8U6oftb/ix2Nm9nn1zD1n6Mje3rsB
            K55m6Upf1AlyUFaWN8sHzxqvXX1zdy7CK4LY3/Le0XPh8kH1ZmwtC6Kg0rGlsnrA
            Lk0OwRNM2DSW4nimYe5Jr5wtPe3tBwpQgWKOMMozqUvHn7PcFcKsyARNbfkaG/ln
            VCIBrRlTSGyKsR/s5qc27djKFWsIETSfDNhoWL47cumudhPl5WYQ2Yqy+E3mbuBz
            L/NQJQ/DnEogc7gXSeMvjtnm+cG+Ps4lpEDVlughtvifPiF831XlIp12MFKi/zJw
            yfav4/z7yGKu/gnKYGL4LCiOuBQ1o/SUTd0+K0AyItmjIdt9MQ0/WqmLz+Ivsx9x
            NsYNtm3bsgV5SrEMb9ih6OfbYryR8gQ7Zqu/LppUTT0J0pGZHXQ6WkdzbY4cVtDZ
            OuE80iab0feevwcZYzzSlYZ4GMwzc2wxhs/h2xJK+BWM8wZcgMhDxaK6gGU0Mk9U
            WBSulRPghm4ae89eB4CV98tqBvUSjzyNAD49zdWR+P0+m5+rWQdMqrE4gghtEEqY
            gux1SAunFUYzBl99ZXYpXoIuHsI5mAPNZZD9vlnXCj1zPrl8OnPim91PNCe9EE/S
            XAE/+m7gRaZjE72GSyLHxeDRfmvNrOlXMHonLzptRiA9JKxHiebhcI9LhUL80swf
            aHCuSHwTAm2fjCuSV7HoWELTEi0eImMD4S4AP+qaEEIlsMtOJxDAO3WZBsFO
            =0UZj
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    unencrypted_suffix: _unencrypted
    version: 3.13.3
