---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../tailscale-examples-sandbox
  - ../tailscale-examples-sandbox/sidecar/rbac.yaml
  - ../tailscale-examples-sandbox/sidecar/ts-exit-node.yaml
