---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kagent-resources
  namespace: flux-system
spec:
  targetNamespace: kagent
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: kagent
    - name: k8sgpt-mcp
  path: ./kubernetes/apps/base/kagent/resources/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubernetes-manifests
  interval: 30m
  retryInterval: 1m
  timeout: 10m
