---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: keiretsu-top-cnames
  namespace: cloudflare
  labels:
    dns-target: cloudflare
spec:
  endpoints:
    - dnsName: "${COMMON_DOMAIN}"
      recordType: CNAME
      targets:
        - "keiretsu.cdn.${COMMON_DOMAIN}"
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "true"
    - dnsName: "www.${COMMON_DOMAIN}"
      recordType: CNAME
      targets:
        - "keiretsu.cdn.${COMMON_DOMAIN}"
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "true"
    - dnsName: "hello.${COMMON_DOMAIN}"
      recordType: CNAME
      targets:
        - "hello.cdn.${COMMON_DOMAIN}"
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "false"
    - dnsName: "home.${COMMON_DOMAIN}"
      recordType: CNAME
      targets:
        - "home.cdn.${COMMON_DOMAIN}"
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "false"
    - dnsName: "status.${COMMON_DOMAIN}"
      recordType: CNAME
      targets:
        - "status.cdn.${COMMON_DOMAIN}"
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "false"
    - dnsName: "s3.${COMMON_DOMAIN}"
      recordType: CNAME
      targets:
        - "s3.cdn.${COMMON_DOMAIN}"
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "false"
    - dnsName: "*.s3.${COMMON_DOMAIN}"
      recordType: CNAME
      targets:
        - "s3.cdn.${COMMON_DOMAIN}"
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "false"
