---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./gslb.yaml
  - ./gslb-gatus.yaml
  - ./gslb-prometheus.yaml
  - ./gslb-ts-gateway.yaml
  - ./garage-keiretsu-top.yaml
  - ./volsync-prometheus.yaml
  - ./cnpg-test.yaml
  - ./dashboard-cdn.yaml
  - ./cnames.yaml
  - ./prometheusrules.yaml
