---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./gslb.yaml
  - ./gslb-gatus.yaml

  - ./gslb-ts-gateway.yaml
  - ./garage-keiretsu-top.yaml

  - ./cnpg-test.yaml
  - ./dashboard-cdn.yaml
  - ./dashboard-ts.yaml
  - ./cnames.yaml
  - ./prometheusrules.yaml
  - ./gslb-zot-public.yaml
  - ./gslb-qbittorrent.yaml
  - ./gslb-garage-s3.yaml
