---
apiVersion: storage.keiretsu.ts.net/v1alpha1
kind: StorageStack
metadata:
  name: karthik-data
  labels:
    keiretsu.ts.net/location: ottawa
spec:
  name: karthik-data
  size: 20Gi
  storageClass: ceph-block-replicated
  s3Path: agents/karthik/data
  schedule: 0 4 * * *
  copyMethod: Snapshot
