apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./monitoring
  - ./auth
  - ./authtest
  - ./agent-sandbox-system
  - ./agents
  - ./arc-systems
  - ./argocd
  - ./border0
  - ./cartography
  - ./clickhouse-operator-system
  - ./clickhouse
  - ./cloudflare
  - ./cnpg-system
  - ./dragonfly-operator-system
  - ./firecrawl
  - ./fluent-bit
  - ./forgejo
  - ./garage-operator-system
  - ./garage
  - ./gatus
  - ./gvisor
  - ./hermes
  - ./homer-operator
  - ./immich
  - ./k6-operator-system
  - ./kener
  - ./kro-system
  - ./kube-system
  - ./searxng
  - ./spegel
  - ./volsync
  - ./zot
  - ./external-secrets
  - ./hubble-ui
  - ./open-cluster-management-agent
  - ./snapshot-controller
