apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./monitoring
  - ./auth
  - ./agent-sandbox-system
  - ./agents
  - ./arc-systems
  - ./argocd
  - ./bhaiya
  - ./border0
  - ./clickhouse-operator-system
  - ./clickhouse
  - ./cloudflare
  - ./cnpg-system
  - ./dragonfly-operator-system
  - ./firecrawl
  - ./fluent-bit
  - ./forgejo
  - ./garage-operator-system
  - ./garage
  - ./gatus
  - ./gvisor
  - ./hermes
  - ./home
  - ./homer-operator
  - ./hubble-ui
  - ./immich
  - ./infisical
  - ./k8gb
  - ./kener
  - ./kro-system
  - ./kube-system
  - ./lan
  - ./teslamate
  - ./mimir
  - ./media
  - ./open-cluster-management
  - ./open-cluster-management-agent
  - ./opencost
  - ./searxng
  - ./snapshot-controller
  - ./spegel
  - ./tailscale-examples
  - ./zot
  - ./external-secrets
  - ./tailscale-system
  - ./cert-manager
  - ./default
  - ./envoy-ai-gateway-system
  - ./envoy-gateway-system
  - ./flux-system
  - ./node-feature-discovery
  - ./tailscale
  - ./local-path-storage
  - ./tempo-operator-system
  - ./tempo
  - ./csi-addons
  - ./csi-driver-smb
  - ./tuppr
  - ./k8s-gpu-dra-driver
  - ./rook-ceph
  - ./velero
  - ./victoria-logs
  - ./victoria-logs/victoria-logs.yaml
  - ./woodpecker
