---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tracearr-backup
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ceph-block-replicated
  resources:
    requests:
      storage: 5Gi
