apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: bhaiya
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: kubernetes-manifests
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: flux@keiretsu.top
        name: Flux
      messageTemplate: 'auto: update bhaiya image to {{ .Images | join ", " }}'
    push:
      branch: main
  update:
    path: ./kubernetes/apps/base/bhaiya/bhaiya/app
    strategy: Setters
