apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: bhaiya
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  update:
    path: ./kubernetes/apps/base/bhaiya/bhaiya/app
    strategy: Setters
