---
apiVersion: v1
kind: Service
metadata:
  name: ddup
  labels:
    app: ddup
spec:
  selector:
    app: ddup
  ports:
    - name: http
      port: 7401
      targetPort: http
      protocol: TCP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ddup
  annotations:
    item.homer.rajsingh.info/name: "ddup"
    item.homer.rajsingh.info/subtitle: "DNS Health Checker"
    item.homer.rajsingh.info/logo: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/refs/heads/main/svg/cloudflare.svg"
    item.homer.rajsingh.info/keywords: "dns, health, cloudflare, failover"
    service.homer.rajsingh.info/name: "Infrastructure"
    service.homer.rajsingh.info/icon: "fas fa-server"
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: ts
      namespace: home
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: private
      namespace: home
  hostnames:
    - "ddup.${CLUSTER_DOMAIN}"
  rules:
    - backendRefs:
        - name: ddup
          port: 7401
      matches:
        - path:
            type: PathPrefix
            value: /
