apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: garage-operator-crd-patches
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 3m
  path: ./clusters/common/apps/garage-operator-system/patches
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: garage-operator-system-install
  patches:
    - target:
        group: apiextensions.k8s.io
        version: v1
        kind: CustomResourceDefinition
        name: garagekeys.garage.rajsingh.info
      patch: |
        - op: replace
          path: /spec/versions/0/served
          value: true