---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: app-home-services
spec:
  jobName: blackbox
  module: http_2xx
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - http://frigate.home:5000
        - http://homeassistant.home:8123
      labels:
        service: home-automation
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: app-home-k8gb-dns
spec:
  jobName: blackbox
  module: dns_a
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - k8gb-coredns.k8gb.svc.cluster.local:53
      labels:
        service: k8gb
        target: dns
