---
apiVersion: v1
kind: Service
metadata:
  name: raj-assistant-ts
  annotations:
    tailscale.com/hostname: raj-assistant
    tailscale.com/tags: "tag:k8s,tag:ottawa"
    tailscale.com/proxy-group: "common-ingress"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app.kubernetes.io/name: openclaw
    app.kubernetes.io/instance: raj
  ports:
    - name: http
      port: 80
      targetPort: 18790
      protocol: TCP
