---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zot
resources:
  - backendtrafficpolicy.yaml
  - probes.yaml
  - bucket.yaml
  - grafana-dashboard.yaml
  - helmrelease.yaml
  - httproute-internal.yaml
  - httproute-public.yaml
  - ingress-internal.yaml
  - servicemonitor.yaml
configMapGenerator:
  - name: zot-grafana-dashboard
    files:
      - dashboard.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: Registry
generatorOptions:
  disableNameSuffixHash: true
