apiVersion: v1
kind: Service
metadata:
  name: tinyauth
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: Override
spec:
  type: ExternalName
  externalName: tinyauth.tinyauth.svc.clusterset.local
  ports:
    - name: http
      port: 3000
      protocol: TCP
