apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bhaiya
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - velero-role.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - referencegrant.yaml
  - pvc.yaml
  - limitrange.yaml
  - resourcequota.yaml
  - image-repository.yaml
  - image-policy.yaml
  - receiver.yaml
  - webhook-secret.yaml
