---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bhaiya-data
  namespace: bhaiya
  labels:
    app.kubernetes.io/name: bhaiya
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ${STORAGECLASS_DEFAULT}
