---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bhaiya
  namespace: bhaiya
  labels:
    app.kubernetes.io/name: bhaiya
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bhaiya
subjects:
  - kind: ServiceAccount
    name: bhaiya
    namespace: bhaiya
