apiVersion: v1
kind: Secret
metadata:
    name: bhaiya-forgejo-token
    namespace: bhaiya
    labels:
        app.kubernetes.io/name: bhaiya
type: Opaque
stringData:
    BHAIYA_FORGEJO_TOKEN: ENC[AES256_GCM,data:Ef46318A36jFh8KpFlQAysZrw+zBZ10xuxMr9I7i56gZr1pAkU7nDg==,iv:FteZERX/gImtRQvpWVYL60DcSy7qef0HM0sp1asNAaQ=,tag:BsuYcQrttUlRBjb/f22tlA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T21:17:40Z"
    mac: ENC[AES256_GCM,data:fpbNuBOPIndlyD1m0OBhSyvwR6H4LbpBcSmRj3HpSIqCZ3XSwUxpuuF2Q31KxkWZ/9onWgxKRF4vqqsOZdrcMVT4kZ8XmQG4muvFlBE+7auvyC/hlTSym4L4uptjJHDIBNpfIOYyNpscZfW5nWqZWdEAW9Vu5W8W3+CglTZ89H0=,iv:uqDKQ2oTDHrGBw3wa1njF47DCDEV046Qi9gGZuhlpZ8=,tag:8tVPGZ8a6F/XSzBmlB5GtA==,type:str]
    pgp:
        - created_at: "2026-06-13T21:17:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveARAAnq/O+2+6EJfTCuZJFgUhMXzefWoZeHJ9VuYe4jy6irJZ
            0J++3RdLUHlgkN4bNcu1+6UM5+E1aFCC4TNCcR/oju19/JEe5BxlMrxgnJ/Ul/nS
            H4YEQ6zM84Y2mF4BKk1TmCYJRWziHijL5+MkrZ7ZgUx7xBOfztkdpFNMne4aDNeC
            9v6efA10dHI42rVkBkTM+kC9X9oVA6W90EyJJM62uSBFSVl6RPrXAsF39vq4nf0f
            t0kqYQQtY2KXs/kWOZkXxmMLwkys3ae9Sh3BTqkxOto+LFQvHvLCYI3au0QC+L5T
            13FHwZNlEgZWnIBz7x+mFWfLJ748OwDbi+zdq9NqMDnbjHfRcQOWNXyo5o86sGzQ
            Rv9V0gWwRQcBPytg5FC5Fgl3rzdWnJSK6dbzhqIf55XonGm63AVC6dqkb7dd6x09
            9o6UIbnOELBjtcH0uLJvjHE9ld+z/qa3fFs5Jvhq0/askqjt3fDBvT39evGzF0xm
            3d9fiY4e/9JgSjE7VOKkDeWOjdCw+cL0HRNJ8CaecSmqXbAAuk2cwEIxXgF4arud
            0x3IGuvM48ZgIOvrpZ4CLnz+uzhTBVqbDOUL+farknD8B1+XyCAh3p3aTtin2Odn
            M7rAv9l/eo8HMJxuJZzp5BXaGOp3RtXpp9WMb0Ex/We1hFoOxyFtlQINUBHk1rTS
            XgGF1peOCwAe9slkq8h9ViS75eIqInQolABx8bFOgKv6aynPpguN+m9Ds1Tu6UPr
            9xbnScW8lePz7ePEkEeaypRZPJfiSKgWwewMa19E1sc6oNCNneKQ1LmNrb3AEQ0=
            =xFMS
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    version: 3.13.1
