---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageBucket
metadata:
  name: litellm-postgres
  namespace: garage
spec:
  clusterRef:
    name: garage
  globalAlias: litellm-postgres
  quotas:
    maxSize: 100Gi
    maxObjects: 1000000
  keyPermissions:
    - keyRef:
        name: litellm-postgres-key
        namespace: litellm
      read: true
      write: true
      owner: true
