apiVersion: v1
kind: Secret
metadata:
    name: hermes-secrets
type: Opaque
stringData:
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:bXiI3gbhLfoFLtf0zpd8mwntUSX0obdfTnaJXn1ULGpCXdNy28MZmXF9YjWSifxckwkd3y0SAs6y1a7XOWjT0e8dn+ExFvJT,iv:MfQd/fvDhKilfJ2E81jbFHWPfSvefX1eAUHLTnuZ3Ck=,tag:ofzUETLz0k6o+yygpn/dIQ==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:MJ5jsKU9MMorigh3TQjsieIFk1oyzCbkeA9OzH2K99yY1tOwQ9oPcQ==,iv:Re0AdXJYGrxCS+DX4pUxhXm8WcWgBhwOxn+/DEcTDTU=,tag:/tLzhrw2DA2/rM336r7kNg==,type:str]
sops:
    lastmodified: "2026-04-18T07:01:18Z"
    mac: ENC[AES256_GCM,data:jkR+p4KcUiQZ2OfM6RM/3RR3nFuDW5HC047zyNR90A1fUdsRG6z0Eqg1IGoItYBMB3ZqXvtccpDlU9OtQr0NmtIDic+97N+C++GFTtAKaFHvAbU6brBZBahXxYnVHk4t0HRbUUoJFC735HAWgIy41L4/Q4dlHK0l3B/O4EwRFM0=,iv:o5B+8/lSHA45LO8nU2toZBA+HO32m0g4Mr8aP1Dr9II=,tag:OCxZ4qz3A4J2VkQ8bPZEVQ==,type:str]
    pgp:
        - created_at: "2026-04-18T07:01:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveAQ//eh0k452AnmKwy0dAn0BWRUOfloZL2x0I2tkao0Q2s5ot
            YIblyhZIiPC7ZWhiPwWTkc7H3+nyYUmRuuKffhoTsImsB48qSz7D505jDTzRzj3p
            GrI363S7V3atqpyVtCjbac/Aqhlf+D2GjSOkbMuDsBr+yVIf2BU9oxo+Yhk4j/y+
            PG9TSz/qxD0cn2mlJUoWO/stYsnF/cZT3iZuG28UCWwxHarGCi8fFjjJDVUQMO3h
            RgdoG+ysocTjx4917ZzP4UKU8JafHVq/tdd2SqScY0uxoqUrhLo+nYTzsv+chsg1
            yvXu+awS/mWmM1M5fqWQzcDXyrl1UZFnBT1dZNx8UIt2sWTUTJkf+iK+ON/7gkdj
            TB36SY/b9+B//hubSPagha2NJDAZzzvrd3zjONBEUcBYviRV5OBOEFQTPr/rW1vc
            tzh9B0QcjLxtr2upM2YClLAQhzpabJHvGTpYS37jaARMEaUICiIAQXfEBhbzUGNL
            AWJGgq20u2TxkX6q6jAkwG/h5gb0UFL2zV2gavUyMaHdjIDi5R9FvSdP3uZ5ZPZ8
            jcK3Z0bMH25Kv55dGJ+s/KswJ7RqkzdJUUhMtUcaixcw+CvY763C1RRAQOtUkZ0L
            RjUdNG0LAxU0lpJd0wCepoxcFDguYD5LVwHZU+PBkyE5EfFuiw4K2lIjFmXaZ3nU
            ZgEJAhB0WeP2UGu15rDlRiVtGsKJg3Vd1sB4bP4p5Q+K088i4tn/ximUxOci4Exl
            1UlHyVQoWFJ1kc4jTmuPFYKpPMla3ESe99VJ+ASPuyfhYfDU6T4ZdEqUlBWoGGGp
            MP+nVbbO9g==
            =+YyP
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
