apiVersion: v1
kind: Secret
metadata:
    name: hermes-secrets
type: Opaque
stringData:
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:AduFigVpFYMQGwJ6tnF2DGaikpN8BqdGdhtj0mmN1cur93+v4fE1c9qtw7w/iE935dw96JClswPppLnFhiEms98tS/779y+6,iv:YmyCtsBgHbBkybyiTmYp2o/FAb7Cn3uPG5ClVbTj/bE=,tag:8gLd69wWXLOYbXbeydHf3w==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:C0OlpVBezri0tZOAq9JSOANL47ez7a588T8sF8bVTFL9T+axz/BGpQ==,iv:Qab7ePXGsAfZ6/lYkMsIguYxMdgf0hLkW7YjxS6wHx8=,tag:Nq78K2Gzp1EKly519P1ojw==,type:str]
    API_SERVER_KEY: ENC[AES256_GCM,data:ZHQRqGMfxFh5JiYVHSz1jx6bwE8bXbtaoZcC7z8kzyNX9z7ycAWLauBOdgNxUI0pTZLyH2dXJUf9PPK/Ibw1wg==,iv:lI9JdxjqHNUEbvdgHTubdqEZUnBZzA4dOo6xQl3+omM=,tag:RGzAIzujqzVBa8mTFdoKWw==,type:str]
sops:
    lastmodified: "2026-04-18T07:39:58Z"
    mac: ENC[AES256_GCM,data:89f4XZ8mxr2mCNc/UmUs1MSKUMsGciOANAZsM2b/KJIe50szUJinnQYMXWlSAcaenMV17IAoxya6OWShikozE3cTHtq8tFrHcP+RMyALeWZ9i1YG+4LDnnkFLudRAkVa8KDU5drQGz95bwMd6j2z7v4PR7afykeChW/aYyXEY1Y=,iv:QMbEFjeyToZdwLCX2ZsKJk3xWWRpoDhw8RGjbevqTEw=,tag:0QRsS/Ymybw+d2XarOLkpQ==,type:str]
    pgp:
        - created_at: "2026-04-18T07:39:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveAQ//Xu03xXrW65sEia9aJgfSAeZ3oRQdQMqSof+y3+nN39Pq
            AXinIkPh/gc86Owm+FsMu0O7ZRmqIAwocqQusRNghs7uz4zrnkwptp+8HJJEv+aV
            T0Oo0QmIG3+6MaeY9BbTLjXfEAltBl4Mukgui60RztdS/1v7bJ4U9Ml5JLRyxUUK
            BG9WjbTnQY13nhpsB5kklOUlOyhenFj9cmSu+Q8TGJMC359YqTXZT0YTgoAyIL6x
            LfFNm5MBeMOQDA3EPoYLYyiVqYvexn5NJeryJmOdgzfE1eNj8H7NWc8VCmmRbdW3
            zhVjBAtWvNHfb8cVbZ9isihHAXu3OVgEvIUfqi0AEb0uDZwpGJav4j8F0e7W48zW
            2TVHfsp/szh+ZNv8hAGhnu9gGKBjpsPMbdTQsgLj23jFJu0lGNjpKq6+7aSrdbp0
            uWBVpZEvxWXl/MmY7DF+UyeagFjhDnCGd+qbnRtP0EnS5nO8sfd4i0FqiWs5VwGe
            B7LaOAZCIy2FlufjLCrgZA8W3R14BeRqjjh5xadbZlEorV8p8l/Kl9dXZEwZTA8/
            hlGaFjfQcL88S24V0wJn/u6wmzR3u5SzF6bJFctro8K/5HiG5xOtLldIDhBDOeNr
            JtNMyYlYijz8hthbkuvLMDDYIB5znFEyt16bEvgV5MxDlxSiSJ/Z1OmDwSPYedrU
            aAEJAhDNUsNwT5ce/7XZqEgSw/Yd8LUypiVc2i6D+QNGKkIUGcDI3ick0PWN8PpL
            UVkRs2iNz+VgO/SsAWhPsWG1eHK96YFKG+mQSV13U6VnlCSBUhcClyaSbUIPhdCD
            SPn/tCE3RAUO
            =6XKA
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
