---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cliproxy
resources:
  - namespace.yaml
  - secret.sops.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - service-ts.yaml
  - httproute-ui.yaml
  - httproute-api.yaml
  - securitypolicy.yaml
