---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: code
  namespace: code-server
  annotations:
    item.homer.rajsingh.info/name: "Code Server"
    item.homer.rajsingh.info/subtitle: "Web-based VS Code"
    item.homer.rajsingh.info/logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/code-server.png"
    item.homer.rajsingh.info/keywords: "code, development, editor"

    service.homer.rajsingh.info/name: "Home"
    service.homer.rajsingh.info/icon: "fas fa-home"
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: public
      namespace: home
  hostnames:
    - "code.${COMMON_DOMAIN}"
    - "code.${LOCATION}.${COMMON_DOMAIN}"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: code-server
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: code-ts
  annotations:
    item.homer.rajsingh.info/name: "Code Server"
    item.homer.rajsingh.info/subtitle: "Web-based VS Code"
    item.homer.rajsingh.info/logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/code-server.png"
    item.homer.rajsingh.info/keywords: "code, development, editor"

    service.homer.rajsingh.info/name: "Home"
    service.homer.rajsingh.info/icon: "fas fa-home"
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: ts
      namespace: home
  hostnames:
    - "code.${CLUSTER_DOMAIN}"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: code-server
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
---
# code-server access control via tinyauth.
# raj + kartik.
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: code
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: code
  extAuth:
    headersToExtAuth:
      - cookie
      - x-forwarded-proto
      - x-forwarded-for
      - user-agent
    http:
      backendRefs:
        - name: tinyauth
          namespace: tinyauth
          port: 3000
      path: "/api/auth/envoy?path="
      headersToBackend:
        - remote-user
        - remote-email
        - remote-name
        - remote-groups
  authorization:
    defaultAction: Deny
    rules:
      - name: allow-shared
        action: Allow
        principal:
          headers:
            - name: Remote-Email
              values:
                - rajsinghcpre@gmail.com
                - kartikbharath@gmail.com
