---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: ts
spec:
  telemetry:
    metrics:
      prometheus:
        compression:
          type: Gzip
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 2
        pod:
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  gateway.envoyproxy.io/owning-gateway-name: ts
      envoyService:
        annotations:
          tailscale.com/hostname: ${LOCATION}-home-envoy-gateway
          tailscale.com/proxy-group: common-ingress
        loadBalancerClass: tailscale