---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ocm-config.yaml
  - floating-apps.yaml
  - mesh-egress.yaml
  - keiretsu-apps.yaml
  - keiretsu-egress.yaml
  - keiretsu-gslb.yaml
