apiVersion: v1
kind: Secret
metadata:
    name: bhaiya-payments
    namespace: external-secrets
type: Opaque
data:
    BHAIYA_PAYMENTS_SERVICE_TOKEN: ENC[AES256_GCM,data:qEkTVYzEhrsdr8r53jxw9LnC8JB8b5WZFnhTVpGHF0c31vRul+7SQ7of5lSN/Gl4o+vG4Sf79EJlRMS33QtBVHo3SwoWrg1FrrBZZ4OEV7HmJBKsYZzcag==,iv:L6Z+dc/ySmwlMDZV+axN8CBnTxCCkQzApX874aG5pe8=,tag:fuX9V9RHWbYT2O6le4u3NA==,type:str]
    BHAIYA_PAYMENTS_IDENTITY_KEY: ENC[AES256_GCM,data:8gfMN9nRS+oTeSeTadhZObSmYxQOdkuutikTUlfeMmxotadRtrFAXIkd4qbyM1vYW1vnpLQ0j9IP8Ca+zygCy6OxAb50jlz3t443DtYHCVRJG9sdqY91Ug==,iv:mI4Eq+gLpRLeIHQncQZ/2B4BKVEXQT2fDl5o3Uzn+jI=,tag:OxlzESgSZpkUqBHs1tZxCQ==,type:str]
    POSTGRES_USERNAME: ENC[AES256_GCM,data:1sWJy5+w3eifa3Ah,iv:YS26MGexGcFw89x0Omby98DOAkXex77S6RVb7Zd6HaQ=,tag:4qi2e8LQQ46ArRoWhoz1Jw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:vjkWg24gUD9+3sxkdq0zZJnkVP2fltYY+gFjjYomoe5C7lqqzd2ZN3k+eetSrh4+uIYgJU3X00s=,iv:XtnQewIqXcn28eArAkh0i5BRmogZ6XL2YNzkcqM2xZk=,tag:1a8HHfjPhB8ziFFZB4q8cQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T17:37:27Z"
    mac: ENC[AES256_GCM,data:Q7POi72fhZxBLfYNVEMsSQbvXZFryU1WkTejozG677PNjYKc6eMYSi0J41IzgwpbdYHGABob01Xz77N7zqnH1eTuwACjhBGlDTf8HI8aekuHJSnMIkyTp8J1QdyKcdPVBlSIMXdz3sopUHuqAjKy8NYgGRKHb+IJqRLiskzHNk8=,iv:209yVotB6jdxlT8JT/m90ySLqRAB2/Vg88d7VufVCFg=,tag:GHuuB7Ts8kDuLTlkoagUSw==,type:str]
    pgp:
        - created_at: "2026-08-26T17:37:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveARAAlSYdhwKVfcdxPdgwxWV3boT2xYmhRqyTww1Sf6mNJrQ9
            deLjDuL9fPaXFhF1fqtpwAdchqiQRNDuk4PgWTFQYBRtiEGPvJ5IreuCAS3HZc5+
            uN6aR11AL/ffGB4ETUFZLnFIGkci0PjFmdSjAjZdIdVQca+WbjEsTMO7g9lv6YL0
            qoHTrUThEqIMZqUOmp6coj117Vr7ad+HKKPC0Cnufep5ldXf5CYi71ZqZT/Io8rW
            zUq/eu1RcpidxPfyRg65yhMNTu5FoU/6r3hpKgHIcR6nRyIgXrI4GCgekFT41ysu
            eiJ35J3fQq62xgNV8Ybndui69KwKca5MNjAiIMphoX086Icl6CXn3ojlyxYgTv++
            rjyfjqgkNDIMbHEtwVeyr1oG96VqWQMOG4k57gZSn9lCVTBa5OWTgslmfz/HNpBk
            YuXZkIBRmJk37Jf91xq+QFnt3ZzTijgFO3DIFLVjLF54Uqc/WKX4mgUssufEM5Ff
            g0ga/gveNgjy1BJEgqw9MEzgc9UuRNPJRJt1z+IaTHvwItsz4/AQhcAf+wr22Lx0
            9CnC0zXgEumsusskkhUBEjNIKIQkoRXlhbLv8Xp4XSP1ImnXwUYFyrvjuG4i4R+O
            +VowDiib1Yn0a1bOuvPUYpWU/h67dSd8rEGUltg1x9OjvJlZZ+u4iUkc2AhE0PXS
            XgG4j4KDmksFoja2HN/FzCuy2w99nEJCKsZhSHSy6DHuhwmBryrFG9OhL2Olgm7q
            v51J6iwj2Mfa5mBiAPoY9ykgd4BF1/1T1TFqiNzqYTP5L2h916e6HsU/J7qMqMw=
            =ff7s
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    version: 3.13.3
