apiVersion: v1
kind: Secret
metadata:
    name: stripe-payments
    namespace: external-secrets
type: Opaque
data:
    STRIPE_SECRET_KEY: ENC[AES256_GCM,data:5ui86mYiCt9EUDLXsVs940JwSe1OsPYGQdxqbjzjEA+rbnPAdx5aQ6+d4IG+j5bkGFPo1nhYB7myGJPvFTWp997gE5tELaylS40Xa5IoksjHu4dovqzPV+SFplSAffOp6XGGNdTtj2eFphLpaUgqEoCcUWRESMBW//OjzStTT0lLziwNH9Xn8pe4dw9qs6RY,iv:zRbgUgS9UvxyAGlDohu6LIToN8h2yLj4XaMzKfeyh6s=,tag:aGrEsxuaIAH29GpMV0PVhA==,type:str]
    STRIPE_ACCOUNT_ID: ENC[AES256_GCM,data:GwV2mwVkh58pkDlBjNaQ0+uy/mQUUoId02LYkQ==,iv:UGL8oc2m+T4NQJQMpAq1kO2i/e6jXjiBjyzB7uoLh1I=,tag:oiS98C/f8dqfkDtAR+Cjqw==,type:str]
    STRIPE_PUBLISHABLE_KEY: ENC[AES256_GCM,data:841B6ZQfEBkR6Bii1S4ywAULDVRCP/dbK14UNBJry+Bd30i1orafNn6gx13S5YqF1lnPZaDqQfNkL3QYBS6vN+Kjpk55CfNHXh+3ET3/4KGVceJYp41l34m4cl3MJQWqL9o/KGGfEa9ZxufEX1tsgo7hKW0wHy+rqrJ9mr/doxg8oQ0tjcT34RSG+eYthl5a,iv:36VjmtdJXSP1i+9DadsV7Ez0aJi6w/m9mmqgD1i2UdU=,tag:OTlhJovYbQaacytvMgY8sw==,type:str]
    STRIPE_WEBHOOK_SECRET: ENC[AES256_GCM,data:kJANTGHCqbeowykyU7pHVDzNqH4Rn/v88ypU8tcyyi4xFrnUqQuMRlRX7cAbFlJjGebZUQ==,iv:Uut/HTY6Gf8vuSdv8FeagZS2TtoqxlXRbOE+rVJCaL4=,tag:5YBXL5/VvWOnXwmYuZ6l7w==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T17:37:27Z"
    mac: ENC[AES256_GCM,data:/ZgzajLBnLDFglsOkzFWZsTrkLWWMTU8gYiaDJuBGAq5RCwn/3icPcf9ZdeD5nOSiS8sLT0M8yjkJpvomr5wtgvKXS4v18NWhKntY8pujIHxP/NiAp0mGAdErXuXbbI1E0NGcP/mPhdH08+1rA2ApSvP0iwNrOXPjaeKSruapOw=,iv:jt2LF7LBoXwPN/tk4nlsoMPtED+aOxQRVEptLG0TWjU=,tag:Hu8wZEpNxQzR+KhnuLOL8A==,type:str]
    pgp:
        - created_at: "2026-08-26T17:37:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveAQ/+MrRpQB0wPM2bCiWObsV/MuDmn5NiVgwAClwkImoq1MXU
            cCSaSss0KigFz+cAVl9oSOx9a6OM2NUudxnryGUbCA2i4c+FrnB1gXDYybK+99Xk
            uz0b+f+FkXyeNZomfflqW/QeabFeuAVB0WHQaMm1ESw1P0aghBEkISW7fA2Oey8y
            hoV570hkkD0BEgNFDyOxdUGMas7a5K7g4RQWiDS92zhvxpWoVU1Z7oPxnxCetSTK
            zASlxK3kBK+WrPw6utHz6BpNWgWsi2uN9HoQQ/Bs1hGVj7uKy6eHRC0frB/w9T/U
            pxdw2nzRmF09y4jKKmwqi7nm8aHOd/NmFEryhmQwHB0dbRUhfTb0yIhLiH/lPcI0
            /ri/JXXghu7EmTCLcxutJuFUYD/oyJZKK7ye33kVLROwGxNb2gqBkfijUSTyb8yW
            roEAICUkb+lb+eKd4hhxvXZQXJjpcwoIrf/sAHojYGdMt1vjhdG0HERVOnuElRcK
            OJS2frEULrVfFbke+EQzlqcxfZD4wxUZsVXn1bfG3dPtrvKCt8XfAM/7N2SklHgF
            9qkehzyP3IhcKocidxhrOHpl6Yfeys2xc3+XvgnhLKU/bnCjm1AMKyJvOO3C0xDy
            WOBA82oxvWd4khRLlq3pLxvZvJHbfBIBvrKWcXUe7Jm+gHgdo9Ms54xvqY8ziKvS
            XgFEU/SdAjlZhX+42PjeIw2/+TSnrUhppIUHab1CNj9hGH+duYdl64gudfZ4Pb9f
            nMaU7DMs0zTYTFXX8NqK+PlbSOnKWYvF3lrU5/jTaEdmHGf7zbckDiXRLXbl74A=
            =4m+F
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    version: 3.13.3
