apiVersion: v1
kind: Secret
metadata:
    name: stripe-payments
    namespace: external-secrets
type: Opaque
stringData:
    STRIPE_SECRET_KEY: ENC[AES256_GCM,data:8yKoOAFLq0ai4ajPGe4hwc8cvKC5UQ+LMsRlNofmHrdj68Y8aDXg7JXP9oU1eQR64E3mLu5QxO+IpLcaEZ3P66SBXGJHPKtcms4iqAlbNdqv4DG0BsSqarVrUpifBhyE20ZYX8iVyUwVTxA=,iv:gMD+0cEiFFPQ4mgimp43WAjvshNDPffwmMZOVFvB8cc=,tag:i/Cx4tcp+9eNb5zOpJaoyA==,type:str]
    STRIPE_ACCOUNT_ID: ENC[AES256_GCM,data:5xGK3R+x64sJrTKz6laWLSqWv1rG,iv:gdCEJ5gMNG0m9rtZJU7ZpdDNvh1ZU/B97+9WjtCIIog=,tag:/28WLI9DScg87fGO15lICQ==,type:str]
    STRIPE_PUBLISHABLE_KEY: ENC[AES256_GCM,data:Av9ptmK/wH3Rgw4iRfgGkR/sVL7gNZnMlubsSoSKRrSnlsCntt8zdYCC+Ii7U+uFZX+E/YCNxQpyajJLv8oxbFeUa92DL0QFmANb+Ril9L+S/wd2+NYv0H+Cq6WijN0gxVgiL8zZLOe0nYg=,iv:BdlRhVwYvJ1rezR3maMOySRL7zXpGshUEqxyumWcHiI=,tag:D80N9l2WofJiO8fHiWS2BA==,type:str]
    STRIPE_WEBHOOK_SECRET: ENC[AES256_GCM,data:FXyj1h0HoSiGP2/2PKzzKp7ppR+7cWLnSdXAiv23so/dZDh1o9c=,iv:YDuYyretE93bePcKlEJ7tGCwjNBiYL0lTVTvJC5kbKU=,tag:UtbCCLSYU7/bZC4IKH7O4A==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T17:34:13Z"
    mac: ENC[AES256_GCM,data:k/Jgtd4b37M/f1cR0T++3w3XsfnVjWwQEtRMIKUtrSdC5bxjXXrIf7Ql8U/xzujb3NkqfW/g5nwzMQ8ZRWvRGu0mwpiB7avdghSWadWo2RdGpjs0zNrQCIMBsDcMsEDKq8f0WoLOFILIuMAlqY1h0otoBOppWn0gdhgm3N1yk3g=,iv:TC6JBBws2x/mlur+YrvCmNpKxcODwyQdImMmjGmj3Sg=,tag:eiCB56eosbfnLMVGAhGS1A==,type:str]
    pgp:
        - created_at: "2026-08-26T17:34:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveARAAkLiau9n0KGPbzqmncUmMQHGnjgRrJwW4pYB28MD/AXkp
            CXzxTc3WCm6hxwN09ipvfFNZexN1OIvAgYkidnweyyazQJJnMZVQ8MM8UD+uam+h
            HSnef/VdVrlSm1B0e670yVcnSdUNNUdYZJiCeZXqB5MmU+d1/k9EDTC0R+lxK236
            GIFx01jNo5jjuZJtS5c+3VD4gHI7eP/gnCOo+yNOQyzgll+57XHQhMjilDbzBR6h
            XmgWM9esO/j0Wwj9bMXb19pbAWbG5SFchQZro9E+KDrweDfejSmf0jFD/v1m3IWx
            AMckaI6kF5A9isekS+d/Y0paiw0INhxEDcCoUHddEG1MVnu1+1QfGcv5lU4lBbXE
            AcpROlxDCbcZm5buMZdj6lu1bkfjnHK9t30cDoCSvO/aM020d7w+shSJ0tKQ5YC5
            8FExAQmF56Nrrn479g2fChNcKRxjdnLQXPoR9rXlxKDddwzy89/ZWUfK9fu0NsoN
            8288cTBI5Ah1pQfbSXV2hfuI26XcNWetz+vNrz7GeGkSzGVmwMPtmIOPQfz3Xa+U
            KdRQQRJH0HDXxxFMyxbYiKm17MuyJCGdw4ORyJcidE8/HP9DXNoE5cIYyhep6Xzg
            ALRb6iP20pMlZcx9xkey/BGJGqJirqWJ92HNROVz3oDu0Si7eFaetDhp+Dr5/pvS
            XgEQA2cFRd4H2r7aQSu/7jonKFylHCvTWtxLipCNyycTPkr+4YBdJCfZXgQhnKPa
            vIJXFt9WM0ZvZxuGPvWFiQ8gmm49fcemXmQ5HnNamnxhqdXrwmYc1Wg1EN2hGlc=
            =24ZS
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    version: 3.13.3
