---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agents
resources:
  - bucket.yaml
  - egress.yaml
  - litellm.yaml
  - litellm-expose.yaml
  - assistant-raj
  - abtar
  - kartik
  - teaspoon
  - camofox
  - hermes-auth-securitypolicy.yaml
