apiVersion: v1
kind: Secret
metadata:
    name: kopiur-ottawa-kopia-password
    namespace: kopiur-system
type: Opaque
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:HAkwQ+adDAKBBoQqBuMquEhIq60MSmgFkVEiN2jId77C2a0y84RyEUrOE40c6FFxGvBF8llS3r970AkrANB/XAA8LEaWWGeXKRMDSH3Oz9VVt0aSoTslgI/bOcBjiApv,iv:7qKU+LDuauQPf/WlNZUUrz5zBR1pVnUwNS1i3dsARzg=,tag:DpPWT6WVZE0EmKyLHGDugA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T02:35:52Z"
    mac: ENC[AES256_GCM,data:Y7aYMWRdvJ3uHH2re7DZRA+18IO+YTOrQnURPLcggKBLy6ZkeMijpH7U+g7gXDVcXQJ83nEGTonL9O2bB82P1WZcjW3cIRLQzJfTMyZv/6+C6h6eUclMcBxtoMuxDmLA7cGtRyH1zji0x2grloLHFg/rXLN4/Xc+9bf8Lm0yzqY=,iv:RZyue2tgk3EcllxLXrdxoY+my/dSNKtR3dmbLn+FEZc=,tag:Il/R6JsHHT7hdncuPaVX0w==,type:str]
    pgp:
        - created_at: "2026-09-17T02:35:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveAQ/9H0yuPOyVOC4VLjXxEaoFVoRfgyX9zUxG8OoMJWVi7hCP
            vgdUGmvWOT57TUJdHJkqLXBOqq7nrC+JThw2VOCQxLjbspI3rWqkZk/dYmNulRC5
            AB7lpxehUHltaKA/prO2URwj3RxWgeOjAC8GAxiEyrck9lye6NbyT1HjsFP6T/vl
            mKJQ4X/RdgvYJnC3PjOwNPW6R/FpOANPINs1YCcRR3g2FUn4albVRQooS3Z1oyjt
            h6nE8KcXAFlf56IBS+Wh52/l3X60/Y3iRtNxq+4t7Oe1o4S5ouVbeOecLMBO5/6o
            X1S/QBEEqOTQXwgta9dv8d5GVNjU7j8YNTHKbJ3CaIHHGbcJXntfdS5+fZdzRh1y
            eEfAzqt28hdXn1YSJ866LhywsI1tWbpfEoFqEzilWzyG0RrG3BmHByvT4jfdg0FX
            h6j/YKdh42L5hCM9TO3vLCI6EtAEKQAneEaEHPLB/CrYXvgyYf8zP+DKtrwFPd6D
            8dDjhf/PWkrJdzY/Kztc88FI34rwrxg9TZS5SaGwME7O/AQZ1limHZP7via5EzFK
            AOGdpg6X9Ieef3Ax5X4DtYGWhknxOznwOiqOAduSkt95Mo0o0Oj+h9zTmcTeqKBP
            HhRhS9mm25LNEth1d4TBx2jjKDgNhuSUYnUkQlUJTefIi3tNSjOxEtKTn5HH/dvU
            ZgEJAhBgvYJksfv9eIllE5fSkjM/RbtK5Gu1SNPeC55zCS+LPqJinkQiKbR0Bsa1
            KZQppgsEDIpsim/7gwxsAhD9ocw9z/XGqxInu+d9OY6yLHuInpFbvUL6MyT7pRHm
            wXu+7bpltg==
            =gy+g
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    version: 3.13.3

