---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: app-rook-ceph
spec:
  module: http_2xx
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - http://rook-ceph-mgr.rook-ceph:9283
      labels:
        service: rook-ceph
        target: mgr-metrics
