apiVersion: v1
kind: Secret
metadata:
    name: manga-bridge-secret
    namespace: media
type: Opaque
stringData:
    discord-webhook: ENC[AES256_GCM,data:YGi4Zu7BaYt9T9Gw35hAbOt3DU8EaCa4AuJ3OFlEW6m1uCZIxomteD80a+/7NydYx9sITFRH1HyFUaU4P4oBG1Os2/NGBcy65akirTt5i6mHea9UYaE1BNUZvzu0Z/xabOAf83LYaRYeBrwO618noCTZLLjqlXNsEA==,iv:KIKpQzMx9mAZc5F2oysRP4NglKbC7L4e11rK9LJLa0w=,tag:ZS1QJHchlnI7Gzn7+m+7Uw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T16:54:55Z"
    mac: ENC[AES256_GCM,data:no4sMUyHOs5Rrag5mVfN2DKfHhhpWnI4NaO26b8f+t8TXsjz3OV98I06eZ+NLv5MJiFxqaf/wouGt87Q+bdgLK8cdAqhlWt/S5XIR9xQXaakUp35BR6luHMyMP8W0tYwP1Jmu+1TJ/VbVhikTyNpbdB1BaFNlO+QaYPkLJf8NnQ=,iv:oOuM+hCVQBVRI5VtFazwLsnL43VBxvq2DCjVhebMPu4=,tag:O+qFAeJ/ziva+fkGdmYPJQ==,type:str]
    pgp:
        - created_at: "2026-08-04T16:54:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveAQ//TsPjnbMMVvZ/F/O5kHraHiPzJ8C81DyeCATZnd9F2XC/
            CT8gLWvhM9z/3QEL8auik5JhXN+AXBn0Dmqwg4EgnC2JzDhdgNd6p4iF5vdYOjlu
            1L0JCAL/WOlZUZ4v3Mb7MIIs77LJooD5wW7LF6IpbuoMpFr7+O5s6S+JtJXrstUj
            5ElRZ0biJrtmqxiW06aD7p8zck3E3J5NB27WRqyemPW2Isszhdn6iX4+fmG4lACf
            HH+LkynMdZ06nky37/n2KQrxdRuE6FAQ6vfHOJNQe3Gb+kg7oCO33eWg8u0O98Yf
            P/nGooIYOPs5YSJLYNcIbFroqWaB4hyqRQNfY4HXeQAjVRKnpk5xbi5QQ/c3tiym
            d58QC+uigNNkKZCvima7KAsOtLUBZiLc5I4zU9QHasoIhAx66M69GNhXFqaXplIs
            2TjBMs7yw592nmPXgEF+ZHP3f1JMbXlE9YgEN3i7M35m7AXjxMwa8oDK261290Cg
            n8fA6eaB4blztX72MeTEQgKwndjrdXWWwZLn96yjQfLvxHo+AH8yfSBx/e9AwBtZ
            5ICMJXAlUmaj9ckpUlzQU4zJiRfwJ5NRasxli3xIUc8x657HNlBQpBla110l+XkI
            QCJBczEoYa1L8bOl3OGDzC9Gbp/NCUSsBkIvYNKJeK04MtYSeQOqPFtqNP+aJOfS
            XgHDrlTrUtgOfwqUIxhvRh1XD0eEyPEHaDXHobY29FjmYrmdSkF8ObeO/V4fDlN3
            lPeXGtiw7Efg67rB+miI4tF50afxbhrnzdeJTSXkd6N9z5IjOzOE49YB1E2VS8g=
            =Ayr+
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    version: 3.13.3
