apiVersion: v1
kind: Secret
metadata:
    name: lobby-ts-oauth
    namespace: tailscale-pam
type: Opaque
stringData:
    TS_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:4dWPWIk8fRbot+CHDjAlR1Y=,iv:uAtaE/n7wmlD37VXxCy2BolVLXdhZzm9Nad3X1s28lc=,tag:wLL5E2olcqi71QYgnEoHsg==,type:str]
    TS_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:c1sBnEvVkKfQn92jtHJXRtmAPUD1yZzuGzvGF/Xa+LtglEBk5wNM51+2ZslFsz6K/FR+UiCbU1aGhFzaE3+Xfg==,iv:lQOnnAjysbTtHPqD2UaV8H4Ckdl5hxdhMyakNCksxuc=,tag:i6oxerJalgZdBPUTi9LTyg==,type:str]
    TS_API_KEY: ENC[AES256_GCM,data:Iz/3gIF4XAi+ZvupF1P2YPkJj5rlTCpFrxVajFpVfLvaPQgfMWfKGIUkO0o0ScXDsLw2r39qpY+G/wK6,iv:gEnqwwIClUGltpXKMGE6wIWcJZjFAW+CoUKNZNbBytw=,tag:2XTNnAXIElk4/UOML4TKgw==,type:str]
    TS_AUTHKEY: ENC[AES256_GCM,data:n+lRf2B7SQ+QJOMTjxMsHyBFn//wyNjdD75Xeb0tkyn27T72Ky+K+//ZBVG2VYusph76yWZeC694a32I0Q==,iv:TSoS8WucHii8/qgxJXMbtWixbBHE5GkfGtpPSIm4LZQ=,tag:Wv8LVXoR9ko87eQYCOW68A==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T02:44:34Z"
    mac: ENC[AES256_GCM,data:uccORkkyfmokVnxFcZDBPdFS1LaxMJE1ueyYNcgN2O0LTyHI5ohrAQU4QCJb2M19lan/YxmDvMSCNOT7Fp/kmN9rkeBjwPtXzMZOnvOoIA46XsI7yT32gibNuNbt8tt0bKdk4xi+bFLlJ0ze1gXjZRd2iBe1TN6crxs9sUbl/2U=,iv:pjXtDOXwrUMgOzjhaU9R8lkUlHsXQTuq2mmeqgnSrVs=,tag:hELBl26Bu4w6zOfeochRhg==,type:str]
    pgp:
        - created_at: "2026-09-16T02:44:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveAQ//XiK2xfWL0GY0215SWIkih9difo/20/AMuL0le+C9hqGC
            fMz+IIPkpsGQkjRCERfgOI0HOM/6+nt4eaVwWYyXKHwyw1fTu/rP05vNAWxY6ujW
            +0uhwRX1pwjAMsHCmh9xY4xlej3q5dvqiNYUSi53CTdXumQ64OXuUdCINfy/Wsrh
            sNhjPia87u6uh+glbiDoLJhTGmc9ZD7wBv/RPHUCJNTjgzQgYiHzTYr+hWseCeOR
            CwaAUxt05/6STbPmB+oZfnrNv0Wt/dBG7MEkOM5h7qn1KUKg0FIdYb6h56Tw9yRm
            rghXr1GvXpWtiF5eOkMDEKoIoxGOfTfSHCRdKX9KVr2fUvGub9vqUeX7UZO9mvwz
            3ytEFdGKjteEIB3k3xHlLlI5rDEFrg+injlFbjSH1Qhl1mE4TWjDX5sjN3JEZleD
            AwPdSV+P6vkLY3IcgiW/LBDgmQnyEXgNzdoFTJsOxPVpTRgQ3e4sKajhdwlenmxJ
            c3nLh3mQ8KD5cCUZCXQeWRuOI4NeNRiQOMgE5PNFi9SyWycehJttXlJm1deLgPFr
            g/iN1dB87ww/goZ36vkJQ9fIhpkE6BvyK/MMpHfu3i0zMh0MMcCYEjyQli/tSUsP
            hNMtZ6Vt9iB9iNUMvpQr1Ca/2+DuTtLDt3X+TRrzVSH/gJKuBoefogkzofwXm67U
            aAEJAhBijQURfs//QsOaDOeA1xQroz0DkNMSucdLIzyG/u+vDyJ9Ac3sk/Uiew0j
            03ZocDaceXnauhE1JYOmzJMPymtXR2aafQUj9bv2N88E5grPdzXf1lEaVZTiKCLI
            GOnfKjP6Ct5t
            =3NNX
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    version: 3.13.3
