---
apiVersion: v1
kind: Service
metadata:
  name: monz-vm-ts
  namespace: monz
  annotations:
    tailscale.com/hostname: monz-vm
    tailscale.com/tags: "tag:k8s,tag:ottawa"
    tailscale.com/proxy-group: "common-ingress"
spec:
  selector:
    app.kubernetes.io/instance: victoria-metrics
    app.kubernetes.io/name: victoria-metrics-single
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - name: http
      port: 8428
      targetPort: 8428
      protocol: TCP