---
apiVersion: storage.keiretsu.ts.net/v1alpha1
kind: StorageStack
metadata:
  name: transmission-music-config
  namespace: media
  labels:
    keiretsu.ts.net/location: robbinsdale
spec:
  name: transmission-music-config
  size: 5Gi
  storageClass: ceph-block-replicated-nvme
  s3Path: media/transmission-music-config
  schedule: "0 4 * * *"
  restoreMode: restore
  restorePaused: true
  restorePrevious: 4
  copyMethod: Snapshot
