apiVersion: v1
kind: Secret
metadata:
    name: firefly-secret
    namespace: firefly
type: Opaque
stringData:
    APP_KEY: ENC[AES256_GCM,data:qSDdeJCdAsJHc+q/CD+BbY5XEzB9jPNMfBtOWaj9SII=,iv:lL59vJr+6RGkATY/jQ74TZlrygOSW2alHjijHSyWebY=,tag:3HXiTGTJLI+6Noq10wzdPw==,type:str]

    STATIC_CRON_TOKEN: ENC[AES256_GCM,data:OLRG/wIQwA/2Jm6AxhIF1fpN32v2eQnPAMReC+bh8oc=,iv:2uFQbuwuKLBa/VC7vo+SRYEWu/HB1I6/lrkketgUH1s=,tag:+4TeavtplNzJ7GXIJm1ZYQ==,type:str]
    SITE_OWNER: ENC[AES256_GCM,data:PquC1+I6R1Tr67zvR4oIEnlxDw==,iv:F53f0u9wF0ePivq8ZWlAaGe7T2NOpLP06B+3RM7rq1E=,tag:pRzngbb1fvhiMAjNN+EMqQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T01:19:31Z"
    mac: ENC[AES256_GCM,data:Ovvds0m1/y0ORezSGOVH4ZA2vSf9c7kYijZ+nP6aIp/vOxd96U1YuBhBH0ihktOoaIj2nK48Hpto2OeGFpRJ0o5VuOAF17gkEzm0oY4JtQ8AK4n0OGEX8oSOfWX227ZiVY2OqtwyA/eVvOyhhkt5htFS5xcCkS1btNnss5QbMW4=,iv:yyrTc4PB7dIqZzF/1L/1rrBVbNz9JhJlclenfdgm094=,tag:4lLL57TBywa+jN85m+oS7A==,type:str]
    pgp:
        - created_at: "2026-08-24T01:19:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveAQ/+Kp4DhkTC5QXDKaVV7J4ruzVaaNQBA65wSCHZz0r6Z96g
            ww1sfKw/HDkEyYJK94UpwkKXKahegB5rbM29m1QLCQ6KrZXeYQ7KdxKiVijrg5qD
            pIDX2e8A6z8PqgjvJ/MuZrMUVBGC4o95eUcI4r+49c1oqp1nnmXslSmYf2s7jTGR
            NqMGeEWpto5Ii66h8QHeSmFW+oY3JcUecrJj0nDV84rpWA4baLb6yhKsQMJLR0JX
            ra2+Shp6Xf7giGaNQUuTVFYHqg78y4FuzOGLLe3hneuuk7iCnXNurT6jAhUteOZd
            3YZoKZC27pigTDcCizZDj3RJAEfMfgcAJ2d7ETA2/DT62Rjsor7bL2gpgPRbmMmH
            JRGSF+xAhzJ2V7wqt7AUE1lLekEPv5nYWcRB9XdngYR20SQQmGlrPN39m+XZOtbX
            TJfnfJe8+9t1HTOp0vMse4hyYTsFHE0CGqKW2THJfBnTarwkEXLGwQPsQww00Blv
            6jJZ6PXHF9yO+jGLSfUwBBKdnsYdfm0ybgXLSmZrRYalBYyb57bZci/WZlnRcUaa
            bH5yZohJRnoozOlhVqhmGNwtjysbW/8piW7CvP7aUgd+OQuVKKyik8UtBZgkxs0a
            Y+PnuCdgMu6tUEn3dOKHoUVAoF3dTO2uDhikM14HN3j4N8i8FhZTh/PAr4+kfRvS
            XgG4Bu7cEP0x9olF12PjbBa6JhUPWpy6ly70v41z4nt1DOcTsvPkTgMCeUnLP2gr
            7jQnoX38pFHz/cajPUjTmD9hdgDdIUOg3HTfK+eWMmF/ud35B3LvvSYrRZMBRNI=
            =XrA2
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    version: 3.13.3
