apiVersion: v1
kind: PersistentVolume
metadata:
  name: teaspoon-data-migration-source
  labels:
    app.kubernetes.io/name: teaspoon-data-migration
    app.kubernetes.io/part-of: bhaiya-migration
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
  claimRef:
    namespace: bhaiya
    name: teaspoon-data-migration-source
  csi:
    driver: rook-ceph.rbd.csi.ceph.com
    fsType: ext4
    volumeHandle: 0001-0009-rook-ceph-0000000000000001-5f08927d-6808-4f52-888d-f4bd7dc315b3
    nodeStageSecretRef:
      name: rook-csi-rbd-node
      namespace: rook-ceph
    controllerExpandSecretRef:
      name: rook-csi-rbd-provisioner
      namespace: rook-ceph
    volumeAttributes:
      clusterID: rook-ceph
      compression_algorithm: zstd
      compression_mode: aggressive
      imageFeatures: layering,fast-diff,object-map,deep-flatten,exclusive-lock
      imageFormat: "2"
      imageName: csi-vol-5f08927d-6808-4f52-888d-f4bd7dc315b3
      journalPool: ceph-blockpool-replicated
      pool: ceph-blockpool-replicated
      storage.kubernetes.io/csiProvisionerIdentity: 1780280393363-4114-rook-ceph.rbd.csi.ceph.com
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teaspoon-data-migration-source
  namespace: bhaiya
  labels:
    app.kubernetes.io/name: teaspoon-data-migration
    app.kubernetes.io/part-of: bhaiya-migration
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: teaspoon-data-migration-source
