---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: app-media-services
spec:
  jobName: blackbox
  module: http_2xx
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - http://jellyfin.media:8096/health
        - http://jellystat.media:3000
        - http://jellyseerr.media:5055
      labels:
        service: media
