apiVersion: v1
kind: Secret
metadata:
    name: immich-dragonfly-secret
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:eZCGQUd8EDG4E6DuvH0pN+/BjF2YsMeuL5yv5FDZqri9c8WTSWdiiKCUcAU=,iv:JH4PNft18KPC/pNhPjTVi1c4QlMvYh5oJw2TgQdKt1o=,tag:KMCVIB9ZReooP6En5jXpTA==,type:str]
sops:
    lastmodified: "2026-04-11T21:32:30Z"
    mac: ENC[AES256_GCM,data:TFIrOfpytSzK6H2bkGlagLcobopkpHHxwcrVLmXol1HsrwK6b2gVCUGYvbP+LGb8Hra9gBQtZN8BFgKZBBbmQQAam5j8B5bPILTxYo2hGjPCXslpXMHL2zKpgfELuEEVYhOeV6Vw0U5f+oV7CoTF28LyyZ0dfDM4Ex9oxgwJA44=,iv:bB/65xxr3IeFiWFvP7C1z5HduCnZMwOnzA+ng/BHTDI=,tag:RedFU8JMsLQiztH3TtuB7Q==,type:str]
    pgp:
        - created_at: "2026-04-11T21:32:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveAQ//Vy4nCJqa+cSZnXdwaE3TRZpwGuIcpXNTNAlnk1wzpC8Q
            BK96YugvKaL1Z9+SI+Fm4MBnQAiQXfvchVeqEUA1P/w/HllmDI8RdDd9YimT9/4h
            Og5IXC3uUY2mzKilgF6/truVGPN6wK1kog2cTgkQThdlW9qklJvmYk0KQJM8foYm
            zw3zYFjObE8bZ8osgf29Yx19c/W7t32OVb+Rbvg+aX7Qz2NYaqt2JNlZ0+IJMMwA
            vWiW6POA0BZji90p9Dr5UqGxqIvlTniSSrpAribiot9E9/R1G0lczysgQeaQpqMQ
            aU496zSvU6o+zl7D/os3dOkirXyHw6XtTCvIXFz7zGnuugiMYpBMA40KUTDuxC7z
            O/9Fwd57mjZUwI5E9WGYRR+9qJEjsl6CN0EdbtkWhmn9p9DdVeLUNgInFYPj/TUS
            D5QXPF/2yAwxZ9LJBH+yE24/WerREcWeApryZXsmlycG8q5JtXCqBb21zga00BV2
            9TLvaRIpd1+VyDv33d10P3yayDIsDjq/DUFqTUQYakJKvvGlNbNPlsSccpTqvfl+
            QKvt/xk0YZLF9Y+AVELdWZedl/lpyprqhLIjIRgHvnO6RZ9K9AM2rlio1yOW44Ye
            JsjAkZhoGMErEOjfJkuLW96t1NG48wMXMvpUde3G6PxmUBgOuQglyHMk8EuddKvU
            aAEJAhDEHtbGTA+Yj6go6wOzj8c6J3NhzEzBGmBQwIO3YJVj12PNXykhZYtYwRDN
            t6zd60Zc/cSEy/rXFfHJnlmdkfLUk0raMCdcRP2K3ers5b0JSNxhsai03tWzJcYw
            maCJKLURKX/z
            =TcTO
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
