---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-config
  namespace: home
  labels:
    app: frigate
data:
  config.yml: |
    mqtt:
      enabled: false

    auth:
      enabled: false

    ffmpeg:
      hwaccel_args: preset-vaapi

    detectors:
      cpu1:
        type: cpu

    go2rtc:
      streams:
        ottawa_cam:
          - rtsps://192.168.169.1:7441/YgigQ2PzZ1QwPCHW?enableSrtp#video=copy#audio=copy
          - "ffmpeg:ottawa_cam#audio=opus"

    cameras:
      ottawa_cam:
        ffmpeg:
          inputs:
            - path: rtsp://127.0.0.1:8554/ottawa_cam
              input_args: preset-rtsp-restream
              roles:
                - detect
        detect:
          enabled: false
          width: 1280
          height: 720
        record:
          enabled: false
        snapshots:
          enabled: false
        live:
          stream_name: ottawa_cam

    version: 0.17-0
