---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-config
  namespace: home
  labels:
    app: frigate
data:
  config.yml: |
    mqtt:
      enabled: false

    auth:
      enabled: false

    ffmpeg:
      path: "7.0"
      hwaccel_args: preset-vaapi

    detectors:
      cpu1:
        type: cpu

    go2rtc:
      webrtc:
        ice_servers:
          - urls: ["stun:stun.cloudflare.com:3478"]
          - urls: ["turn:openrelay.metered.ca:443?transport=tcp"]
            username: openrelayproject
            credential: openrelayproject
          - urls: ["turn:openrelay.metered.ca:80?transport=tcp"]
            username: openrelayproject
            credential: openrelayproject
      streams:
        ottawa_cam:
          - rtspx://192.168.169.1:7441/YgigQ2PzZ1QwPCHW#backchannel=0
          - "exec:/usr/lib/ffmpeg/7.0/bin/ffmpeg -re -fflags nobuffer -f s16be -ar 8000 -i - -vn -acodec libopus -ar 24000 -sample_fmt s16 -b:a 32k -f rtp rtp://192.168.169.66:7004#backchannel=1"

    cameras:
      ottawa_cam:
        ffmpeg:
          inputs:
            - path: rtsp://127.0.0.1:8554/ottawa_cam
              input_args: preset-rtsp-restream
              roles:
                - detect
        detect:
          enabled: false
          width: 1280
          height: 720
        record:
          enabled: false
        snapshots:
          enabled: false

    version: 0.17-0
