---
apiVersion: garage.rajsingh.info/v1alpha1
kind: GarageKey
metadata:
  name: mimir-key
spec:
  clusterRef:
    name: garage
    namespace: garage
  name: "Mimir Key"
  secretTemplate:
    name: mimir-s3
    accessKeyIdKey: AWS_ACCESS_KEY_ID
    secretAccessKeyKey: AWS_SECRET_ACCESS_KEY
  bucketPermissions:
    - bucketRef: mimir
      read: true
      write: true
      owner: true
