---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-anime-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ${STORAGECLASS_DEFAULT}
