---
apiVersion: v1
kind: Secret
metadata:
  name: bookorbit-postgres-superuser-creds
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: ${DEFAULT_PASSWORD}
---
apiVersion: v1
kind: Secret
metadata:
  name: bookorbit-app-secret
type: Opaque
stringData:
  jwt-secret: ${DEFAULT_PASSWORD}
