---
apiVersion: storage.keiretsu.ts.net/v1alpha1
kind: StorageStack
metadata:
  name: bazarr-anime-config
  labels:
    keiretsu.ts.net/location: ottawa
spec:
  name: bazarr-anime-config
  size: 5Gi
  storageClass: ceph-block-replicated
  s3Path: media/bazarr-anime-config
  schedule: 0 4 * * *
  restoreMode: restore
  copyMethod: Snapshot
