---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai

resources:
  - namespace.yaml
  - vllm.yaml
  - dsv4.yaml
  - dsv4-dockerfile.yaml
  - dsv4-kaniko-build.yaml
  - qwen38-build.yaml
  - qwen38.yaml
  - secret.yaml
  - probes.yaml
