---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: karmada-controller-manager
  namespace: karmada-system
  labels:
    app: karmada-controller-manager
spec:
  selector:
    matchLabels:
      app: karmada-controller-manager
  namespaceSelector:
    matchNames:
      - karmada-system
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
      scheme: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: karmada-scheduler
  namespace: karmada-system
  labels:
    app: karmada-scheduler
spec:
  selector:
    matchLabels:
      app: karmada-scheduler
  namespaceSelector:
    matchNames:
      - karmada-system
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
      scheme: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: karmada-descheduler
  namespace: karmada-system
  labels:
    app: karmada-descheduler
spec:
  selector:
    matchLabels:
      app: karmada-descheduler
  namespaceSelector:
    matchNames:
      - karmada-system
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
      scheme: http
