---
apiVersion: network.keiretsu.ts.net/v1alpha1
kind: ServiceEgress
metadata:
  name: keiretsu-test
  namespace: keiretsu-test
spec:
  endpoints:
  - name: ottawa-keiretsu-test
    fqdn: ottawa-keiretsu-test.keiretsu.ts.net
    ports:
    - name: http
      port: 80
  - name: robbinsdale-keiretsu-test
    fqdn: robbinsdale-keiretsu-test.keiretsu.ts.net
    ports:
    - name: http
      port: 80
  - name: stpetersburg-keiretsu-test
    fqdn: stpetersburg-keiretsu-test.keiretsu.ts.net
    ports:
    - name: http
      port: 80
  global:
    enabled: true
    name: keiretsu-test-global
    fqdn: keiretsu-test.keiretsu.ts.net
    ports:
    - name: http
      port: 80
  proxyGroup: common-egress
