---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./alertmanager.yaml
  - ./victorialogs.yaml
  - ./mimir.yaml
  - ./mimir-local.yaml
  - ./mimir-robbinsdale.yaml
  - ./mimir-ottawa.yaml
  - ./mimir-stpetersburg.yaml
