---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: loki-stpetersburg
spec:
  allowCrossNamespaceImport: true
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
  datasource:
    name: Loki-StPetersburg
    type: loki
    uid: loki-stpetersburg
    access: proxy
    url: http://loki-gateway.loki.svc.cluster.local
    jsonData:
      maxLines: 1000
      timeout: 60
      httpHeaderName1: "X-Scope-OrgID"
    secureJsonData:
      httpHeaderValue1: "talos-stpetersburg"
    editable: false