---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: infisical-backup
  namespace: velero-system
spec:
  schedule: "0 10 * * *"  # Daily at 10 AM
  template:
    ttl: 720h  # 30 days
    includedNamespaces:
      - infisical
    defaultVolumesToFsBackup: true