apiVersion: ENC[AES256_GCM,data:svk=,iv:QfwDpb1FuNfTXdLgHaNz37v+qtO1zTuOr1FO+6cyIrA=,tag:yag0nE8UL8emMeDffyJiOQ==,type:str]
kind: ENC[AES256_GCM,data:8n7c4ngS,iv:0HFFgDXi1EUcDPylqVJ3TYTqhgubxiOVXxYv10MvmB0=,tag:MqeGgr+woZlqBi1ugjyLYg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Wuc8JSvI3/JkAtr9p0rxe/ZAXbhk0mFk,iv:ESotl7GLqqVomRmiwUsqTWsFGOAw0HidFdwAE2NcW4I=,tag:qrW/xB/ivdo0J2TgphsRfA==,type:str]
    namespace: ENC[AES256_GCM,data:JGfFHmI=,iv:5fTmFa9+BDw92v6FnJa9lSBpuXY1sa20yPJl3rHDHfY=,tag:r3Br4aitf0pBmWR0AYhjyA==,type:str]
type: ENC[AES256_GCM,data:mhio4rDF,iv:jMeG8R7A0tJzvBhZG40SnzQuIYr3epGtsnt6LAZuDL4=,tag:dRXpHxU0iM6kqMUsUY/RqQ==,type:str]
stringData:
    COMICVINE_API_KEY: ENC[AES256_GCM,data:AbvpHNEHsCRWrI1U98N50Xft6bLi9mqO63y/m2eel0iiis5yrcZtEA==,iv:f5tCqnwcJ4/ZIT93omt9Tctm6FJ81ghMefcIGRjZghQ=,tag:Ke6Tp9vtSjn9+S2v4TQbVQ==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:S8uOVFVonu96FHNSD7cfD9NAKN2kC6cHYh+7NmLeH4/nSs0FaTxqi0HOVtvnktjy5QSvKiOBCaID28asXvNRtw==,iv:MZ/fiXClsdHs251MtshtplqlerSovPkxyBThhs97T0E=,tag:v9lI+DcnCrCWVzSJ3joXsg==,type:str]
sops:
    lastmodified: "2026-08-03T03:23:02Z"
    mac: ENC[AES256_GCM,data:9lzXSos01m23x2GBMF3/wJf2Fk4UxHRAPn+Y2Wm/QHtNSejkuyhF1IKUFljLGiufI0w5qVqMWskOLtadBQHTezT5QZCwxb4KmizeNUmbXIbewmHob6Kqe5PgQfGO8GNgVUyl5Cn/r60+zEPwooj7OFDXkGxW1TjrV1WMRshLXHc=,iv:b6pwlPjIeWEEVLYKCzhc60OVR+9AU2v4Golmwgemi+U=,tag:ZmITBbj2fyHNPFAFvJL0Ig==,type:str]
    pgp:
        - created_at: "2026-08-03T03:23:02Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveARAAgSHfO7ECTJMDFIk1TGtLt2xOskAWD9qxzrGnyqOhM1Sp
            RKGbJvjSec3DsXaMSqevLL8dp0txkig5U1XLPRe1dEbB6zSETZ7jNd8wtqF6R28u
            dehSYAu8JLaeEmjBgSYv+at+lWlSKIvvRo8boU6ZgM7NvXZdBj3nTA11Jn135zJw
            DHfeSj1x7WGgSgcUP/71fx3sDdcSG9Ql7VVzxy7wGnylbq0ykFXbj6dDCNc8Ed8w
            If9/mB2LFb6VGfCSJLIy6NmkiE0aIDOTUXmho+Aiwyqnv9q2pFBMmLH6LUCFgIeG
            iPrPCvgNYt3kfKmqYQaR8hgs8rPUg852AKfp4piwiJq8px442pxtO76XZm2XxWLr
            QYDGMRskce/PgLhsROjP1VH2RgV/S0iCWqzqhZKEiEI5hREwJzTBnqLXCeQaaddo
            r8MBCVni3KkiI8phrIVEkXqU88peh0EiiMOC2JvR3add1CjFVY9Yfj48NCcHC0HK
            vTDxT4QnrFSEUrx4C9eoHGorpQGGCkC7NwaAKZDztZMSvWsG5gTwo1XutwokyCli
            QKFqll3VNOCqcZdMQLrFOtC6wCUh50zUuPymr8DcHrVh+fCnNUN/sHr87ZTBgx26
            iZM2Zkuh8BSg64imlHpyoSj4k1SdqghfhnWY7ZrLc5cmfLp3wHwCn+umaWX4DX/S
            XgG+4UVufNuZeg96X1mOoWQNqh8Mvu2+aKtD5D18i5Ah93pJGIpUGrAcrqCuZidX
            Pq+BkPZzqgo/gppT22xqOSQbGXNVWCZhMfD5vPPxHVVF6xTo0KDNY8eU7E6Mqpc=
            =PQc2
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    unencrypted_suffix: _unencrypted
    version: 3.13.3
