apiVersion: v1
kind: Secret
metadata:
    name: omnibus-sensitive-secret
    namespace: media
type: Opaque
stringData:
    COMICVINE_API_KEY: ENC[AES256_GCM,data:BBd9YfmGhR1rRHbTYgVtQcz3COQamw2dTFleC2QV7s6CH7PZ9KHvyQ==,iv:h1uUWuMVf85Ovk+52jD5Z6oEPiqj4neXDEar/PoKuTo=,tag:sam5jO1IgHkWSRv0c1POAQ==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:QryrEyR/M5+VNhJWOXvhnvT2gaoo3TslF+41KwRyXAKdgjvu4m81rJ05tIRXdyVpdKsfh6/9/xbFTznAdlu4zw==,iv:9yd8d7MM0Gyi80QhkIgLG66NDnzPmN6PB1h/SFSYnb0=,tag:apNNCHB7m7NNfZerNkUo4Q==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T03:40:34Z"
    mac: ENC[AES256_GCM,data:L32ImpXW+pp3z5OsCCp07HeKijoApEjSL1oDt/KUmNehgUcN8+z+bB/HUqGrLAUVAFKNmXSwd3Wr1d4mytJjOGLh+5vOS9Hl6lECucrvJ/a3cn1rmNQkgHpf9Q844eAc4+N7k7vchlBImzp6xtrtULHtz/89NjtOlB+gi05cD/Y=,iv:DKV0gWabdFnMPHt06UlyoLlmvxYPF3RzWaQTyh3jH9A=,tag:7s7X4vbZorWXa7pr0nkatg==,type:str]
    pgp:
        - created_at: "2026-08-03T03:40:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveAQ//Vf4poX8HfWY0YT+rO+HyEi7k7yXr2htGatwZCz/mRUO0
            Kb9s/aY7mzjQ6zCyCVgSZP8PNG145S93OOxBpXJnCrS6LwCwJSFCuxyR/yXaYZd1
            o1fncB9SirWbz2ayCVVXIhJvjGYPZKyrxee3EO1N6X1n10N8F79K3Nn55rm1kZ7e
            UMGMsVy4dxJzEw2UMHhF/pu1A3VpyY8nAwIHsektY594ovR4ZbT+ogFxRnKNg11H
            RuphoP/2FPSMSpWuCVGQ/DZMd4pkSQjEdsNqnN7NUkIQkca/otcA0lPMC4BKPwBP
            CgQAQK/xKpWXONlVVrBYHL8YYrB+kNJNkAipgQbt6HQHizMP2uqFNUTgFp1mGqVV
            ILJXHekleCUwtjV0jHdzeC0smoyTI5LhIgI4MjCWEd0u2qo0L91IS3Krph1QFHbK
            h0TMUWyXTb/F+IVsS/yFgDASmtlc+qJ76vyTt+NnemAVDQc+W+fixfGeBYdKzNBT
            KmBSilLmbL5+rMQfTetXsJZuP1MzGQxYN4BQGNpFBIljLpY8Dnkt7sxRRv8Whlgp
            5td05XdckKFRv4BaRswhg+L/87XPfrgJWpPEX8c4KRiupSpnEE3fsn6NKr0n1JTs
            6dv1B82BsavyaEe3JFN5hNBxxcToKitRIqhXm7lpIm7Dam8ji4pWukwVGRIZ72bS
            XAHNKaeLvfiMnfujgfldoE7i+Ez1Y7idA2xv0LWfZ0uLCItXwOazh4XYTI8nRzGp
            NSKk9ma0SR3VLpHyhbeBhnvx2Emlgpl3MIBxYCZdga2ghW267shHfai73V1V
            =9XB8
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    version: 3.13.3
