---
apiVersion: network.keiretsu.ts.net/v1alpha1
kind: ServiceIngress
metadata:
  name: mimir
spec:
  hostname: mimir
  selector:
    app.kubernetes.io/name: mimir
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/component: gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  global:
    enabled: true
    hostname: mimir
    ports:
      - name: http
        port: 8080
