---
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: tsjustworks-egress
spec:
  hostnamePrefix: ${LOCATION}-egress
  tags:
    - tag:k8s
    - tag:${LOCATION}
  proxyClass: common-accept-routes
  type: egress
  tailnet: tsjustworks
  replicas: 2
---
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: tsjustworks-ingress
spec:
  hostnamePrefix: ${LOCATION}-ingress
  tags:
    - tag:k8s
    - tag:${LOCATION}
  proxyClass: common
  type: ingress
  tailnet: tsjustworks
  replicas: 2
