apiVersion: v1
kind: Secret
metadata:
    name: lobby-ts-oauth
    namespace: tailscale-up
type: Opaque
stringData:
    TS_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:8peuJzX4yWweBugBuZByMRg=,iv:ZlWKc2ySxRHAkm/4u5p3fQQwTtwoN9oopKYIkGmCVQo=,tag:DWA457OpW0APt4L2qe6ZiA==,type:str]
    TS_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:ns8oMfWHEFuZaUtZWwjmovI1f6EnNsvb4uqlHhr88r4FBQKH/0sVW9nsEC7kQg72yJn++1DRpFeLGHTAkCWnRQ==,iv:HW9akNPuuchhzGv7fhw5Kcdh33WHa3IPopHTHCWPDAA=,tag:JZ1ust8G6sLhZ3JSZpZeJg==,type:str]
    TS_API_KEY: ENC[AES256_GCM,data:I7v7AB2qRLLq4ovfEkOCsw7Mdk0cGwFVlPsBupyFaToEeGeT8J5eP0m/Nnjq+6+WmNXjqAxINTnugT7Ang==,iv:AEIAIlEJIGwvQBcdf7FjNHeqclDTmylL1i2o/31lICE=,tag:nZ9NufKh2IQ+7AbLphr+AQ==,type:str]
    TS_AUTHKEY: ENC[AES256_GCM,data:wmrq+ZcIIHfRxOqYK/Ctyww1Fcu+faKdckmNp4Yn4Ts9JomfWHHkWt/XAo3e2h568DD/bJFrvgIj7q6RXA==,iv:L6cr3aNNFp2Kd36yr25+TG7ctzGVqxF2ogkAZbpXXfg=,tag:yJvE6xC6HZsd0cBmAt0ehA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T19:05:27Z"
    mac: ENC[AES256_GCM,data:pwB4U1xdV6f516K/mgomiYRU5uqs3j0yDG2cRX/duTDMdYycY9luaQFveLPuve9jJ4+jshw5yBRY8Oj6nhTBfS6dcQTp0flMIyQevfDVJSNwvX8C4IL/UTs3IiHu9daKFsQGDNcJ6aromtQ8NrQacibVsFlnrC2UI6wElLhunsc=,iv:vSd6Tplxl7/eGT7Mm7KC/5HkMDBARq6RiTjsRnMAIJk=,tag:UOmdvfC3YzOrnebO0odXgA==,type:str]
    pgp:
        - created_at: "2026-08-15T19:05:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveAQ//XO1auru+T+867CDzFldy8/1mdm/brHUO8d36ZP4/0zn4
            H8u68+s2KAn8h/stINjEVg9KkK3fTlFXstY/O+4lVwDuRakLTvBNsUVhillKbMjI
            1CtzpGQcOS5HtKQ3Lsr5p0xcZ7ijz3wlb0gVx2ApiDp3IxDU1sv38izeW+x8/qzq
            midYphQoWG/Mthm8PxdbvMNaLOWjx77WcER6jPgI25j3uHO4d1NBmz5DsIRdb28Y
            l3q2YxEkMZ/OTu4h9+f7FKNxdo5HhVVDzoRMaqmE+ik/BehC2LLQKQsw5CW6fyMV
            YRzyQcYZ980wmgMHBwB4d1sL/FJ2Od6VKeTCw2gWVftydhvwdu3HxLAU2ey29vC3
            /8Ekpl8wa/90Ml4KIt5eoB3jMuQPAXoXXIRBuOx996SiFWmkb5OLK7fyvkORooXi
            Pk1ZwkcKtUVCcARr5qrHgaJP5Kiu0RY4geZR3KWSf1VvkEEC5bfaxNcVgrmHgUWO
            ZyUl5CTp57NS0xhju6IZd5QaPX2ZX9SKTl10ty7Lyka+3Czgk17sjd6Na6IHVIlg
            3TucLhTeWDYExqh63snJ2RGDD6OnnAlgLcT6TkHlPF82pQmfUaqzQLsm4pihAbqY
            nP1vmbU341EZFAB1V6JRWGaQdm4btSItE+n16QeA7Raa0AnXEsEqqpjIDFIpJV3U
            aAEJAhDM0ocwHvdjLT4ArSCG5p+LjBgV2uFRqCHksIzK4U/fynP/a/XOf6pRQiQ6
            b77FJUJZD08ytLQ9Xi4kut1cvabeX0kl9QPaFrY538KcFnMCCnG0NRusVGKHPl9C
            HjIF2sBEZ51M
            =7riY
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    version: 3.13.3
