apiVersion: v1
kind: Secret
metadata:
    name: lobby-ts-oauth
    namespace: tailscale-up
type: Opaque
stringData:
    TS_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:CNSzpBCo8DmTiA/fWtYW74U=,iv:VT9LJ8X1aS22lxhCLHWJrvLA0P+IjI9eJWTHx44vI/Y=,tag:WfIXWhv43Z0PDCr/mu37Fw==,type:str]
    TS_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:zOUtZNsnRj+BTUNPRKnA1OsAeEAsXFutact+aXM/TOsCl+kJGrJNU0ZEFNjegaHGNpdSnG+CkE67IVfeU8rPWA==,iv:CQSz99QBjnG2/9ElW/FB4jRt2tNdg7ebjIVxahuBXPE=,tag:6zQ1cC1vOF5f8CIJQ0pcgQ==,type:str]
    TS_API_KEY: ENC[AES256_GCM,data:q+OkLHnDCAuTENfRr9qJqiIrGBjcbmAUgAc+EJqEKbcaNUwygI+aKn91/yiPiUv5deqqxSyrzZmBbdPO4A==,iv:lcad7asuNc90+g0poro7Psd/+fW/DCNJjLlgZlISj9U=,tag:rlU4MtEcN4Z8ogBBlrejTg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T18:54:38Z"
    mac: ENC[AES256_GCM,data:xv8BIDmNtjeKMAV0Wsyb3FW0CVQAXeYVdHliWXAbeDqnahFKYbpoAbqZnaTvwjOlizsM96ycp/qeYpqS4pyxJWVTEtBPJIJbq/SAEoURjA+lcEiglzg2Lx7VGkaXWdbYikI0XTTy9uWBFDOz45mX72XUy9jOQUlJIwLnplF/nEk=,iv:dfkQRiiD2JvnNOzu/aBW1um8ERDJSmtcU63BtdVHIKk=,tag:QGOKUL9TnBtZlhVkNoSCOQ==,type:str]
    pgp:
        - created_at: "2026-08-15T18:54:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveAQ//c8E6nfLuvdbo3rpKfJOfD0ep3LD0oEt0vk90U2d6njwF
            FntyM3/Jga8rCd5NM+OkcwyxN4YN12OXMmFh3dqpNhKgROQM/gP7m0ep/6mNhXZ8
            Zi64kqL8JBhqMpbtqthxsBQ/+0NDEBgyxaoamPaVMpGjywAjsimLVBkfeestZFM9
            l1RciRtJHvvV50hzGF5p89R+r2iAlL4oD2+hs3uVWm/VPG1gNxWqb+8Buxci0CFa
            MAHxWBbLDvbhXTarW+AUpWDU5Y3/ljdD6WfT+axEvmQQtVWRfqx4RCUrlb+j+GL7
            8XJHnyvbXxznC6VlMpvmQDZVzvD/2J/4IYzMPqDpW0097mbbB/tgb86FNznSnKae
            eWsY6IXbhFst4DfGHECTU9CEzLhF/pLfqOthQiVh1Dy1Li0b6bPBZyJYciBoTkpv
            u1k0zaqJlvGxVaMwiKV4Lnc5uDA2Y0HB5On/7xywzbA86+UBmmVFQwrJYcjpJbjx
            OFBHOHqKmlhk4PgflxzoNseaJRCuyNz4gGOEEQ46j7d6Tymcy8ag7ut6qqiATL/a
            59opCFWutgJKZLw7kg0g1ejq/s2q5uDR7CE6d05En7RUTnZ3P++qoGrORcyciYle
            2r3EVs2xE5InD0R+/CsUA9Rmb+Qm1Vq65+FY7AwIWbByp1wWq2DcaGPNjyPrKUbU
            aAEJAhCmk7Mrs0eq0KfUqw0E1mUDSdbhFk01LNueNgJIJ5QyTpkXD7smU+v+vM4m
            kAeUDv8UtM4gtugDCy5wEITnysQAiLedK0WQ//6qRSGJoxBtIli87aLl81XA97dD
            I8xezNYHvZ+7
            =yOqS
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    version: 3.13.3
