apiVersion: v1
kind: Secret
metadata:
    name: lobby-ts-oauth
    namespace: tailscale-up
type: Opaque
stringData:
    TS_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:OO5+Ym1bK8zOA/EeF+eekPk=,iv:DtVP6NBIYSFRNRwgEd5fRQOhzHoI1XYNLpK5vy5HYc4=,tag:dJGaR5sQl72ApMaHau8TQA==,type:str]
    TS_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:pbBXHc7vyXWBboPReZvX0iZdHFacgmYXnEFBX1nKakvL1mtDivExsm79bo3Wl+M9cZfZZZl+k6pZ3l1Pg3MX,iv:E4NwptJqvBcspffNHXddxGIhq0rF/vSkOUutQArAo9w=,tag:unMIXEKUaqgfbdd2hQMaow==,type:str]
    TS_API_KEY: ENC[AES256_GCM,data:OjTeicvxQBdYQCXoakIPkKQnuGPzEJ7A4NIhUJnwEB6S47LkbfmWWITnfY56fT0ed/NGjvcScSCm0c1e,iv:HFtjZVCmzu9kleJi/zQsS6doPXVLuHzXZkABbFDWGxA=,tag:8woRWtuG53pdFgyCEAEeJA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T03:49:29Z"
    mac: ENC[AES256_GCM,data:m6pa103WoDIlPdz1y+EIeuYkvBZ9+DCwNd3gVzz50mw+KdHZBXUpIik+MLWGsXdguD0XhMD2B+XskdsXe0N2K5+jo7YvnQbnO85+NKXbq+0QVSWsEExYxUhMlDqiUHTZUgfGgHEmM/XEW9grMbMwB2IUQsss/3WhHbSHl3votfw=,iv:ciJi1RXUKBsOx8GW8vm0q8guZe9xixHHjPdKjAKQtG0=,tag:idkfo/fymq73uFtgRebLnA==,type:str]
    pgp:
        - created_at: "2026-08-10T03:49:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveAQ/9GqV91+Mju0T8luArNZWn8FxKVTrjr/yrdA8eIu93+xiO
            ohv5ZeHig2uv81D2JFnD5V/AW5FnWmbIbC1gqrOSV8zd1gxe4p3wL5qbmlLqHL+t
            cLcrSFwsADLKpg4dK752mtxy45of4snq52f/Q6sC5/3fndyki5KeQ1LuETvzhIH1
            I8C6aqDVAEixQlbnryYlDjv+ZJpSjPteUOOJAVUCWhh70Dwh97EmKSVImUMXpFXV
            ZQJfWtDdkH4JzaOJDKCG7z/SpTGlmeAYGTGVaCkWY+NN0Ywws7PdbbNyXiay7LmR
            JlfEnQtZ5SAXyyxLJgnIUn5+loQGFbHo94DdsuFFGSm0zEMyppasoGe1CavLt41j
            kHmRalTTlOxV94tbl48S8/HpTlcNGGnnDiNNbIC+Gv7FUMoSgtdlNhQA8ce0HE/z
            x50Jsv8u/2YA8HHp4XVm8eix+h4SykcWdkxcytm6FgBepTCq5720xls49rD8Sbhv
            VdHiu4fY+5zjKWOSQ5EECnZB/zJG0he2Tza19FMi677ehU9TojJLt89Xx0WkYjMo
            vxRuTG6caT+6CJowey46hJQtJ++n10t0wJk8ojuFAtT4C0GHGEBHcfvOvpLfA0de
            +X+V0Z0UkqFf4QJPlmntIKt/7djzl26y0gKeAnuMw323WOhpbL4K8jIYdyIpyL7U
            aAEJAhC56vdHeVYiyyaWg7VUjVqWM0WzflezLCGBMsPGTH2LSmIoWPikM463/KNX
            Anl2ZTk4Nd88wepoQB8/v7VzV+0jyfIHePvjDiBcHAa7C+MGgCxhIsRsbcds4PQ0
            FkedsbWjvGd8
            =8gXn
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    version: 3.13.3
