apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lobby
  namespace: tailscale-up
  labels:
    app.kubernetes.io/name: lobby
spec:
  serviceName: lobby
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: lobby
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lobby
    spec:
      terminationGracePeriodSeconds: 35
      containers:
        - name: lobby
          image: ghcr.io/rajsinghtech/tailscale-up-lobby:0.1.1
          imagePullPolicy: IfNotPresent
          args:
            - -state-dir=/var/lib/lobby
            - -tailnet-name=sheep-adder
          env:
            - name: TS_TAILNET
              value: "-"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: lobby-postgres-app
                  key: uri
            - name: TS_OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: lobby-ts-oauth
                  key: TS_OAUTH_CLIENT_ID
            - name: TS_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: lobby-ts-oauth
                  key: TS_OAUTH_CLIENT_SECRET
            - name: TS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: lobby-ts-oauth
                  key: TS_API_KEY
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: lobby-ts-oauth
                  key: TS_AUTHKEY
          volumeMounts:
            - name: ts-state
              mountPath: /var/lib/lobby
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 256Mi
      securityContext:
        fsGroup: 10001
        fsGroupChangePolicy: OnRootMismatch
  volumeClaimTemplates:
    - metadata:
        name: ts-state
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: ceph-block-replicated
        resources:
          requests:
            storage: 2Gi
