---
apiVersion: v1
kind: Service
metadata:
  name: robbinsdale-jellyfin
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: merge
    tailscale.com/tailnet-fqdn: robbinsdale-jellyfin.keiretsu.ts.net
    tailscale.com/proxy-group: common-egress
spec:
  externalName: placeholder
  type: ExternalName
  ports:
    - name: http
      port: 8096
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ottawa-jellyfin
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: merge
    tailscale.com/tailnet-fqdn: ottawa-jellyfin.keiretsu.ts.net
    tailscale.com/proxy-group: common-egress
spec:
  externalName: placeholder
  type: ExternalName
  ports:
    - name: http
      port: 8096
      protocol: TCP
