---
apiVersion: storage.keiretsu.ts.net/v1alpha1
kind: StorageStack
metadata:
  name: musicassistant-data
  labels:
    keiretsu.ts.net/location: stpetersburg
spec:
  name: musicassistant-data
  size: 20Gi
  storageClass: local-path
  s3Endpoint: garage-gw.keiretsu.ts.net:3900
  s3Path: music-assistant/data
  schedule: "0 12 * * *"
  copyMethod: Direct
  restorePaused: true
  restorePrevious: 1
