---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: REPLACE_APP_NAME
  namespace: REPLACE_NAMESPACE
  labels:
    app: REPLACE_APP_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: REPLACE_APP_NAME
  template:
    metadata:
      labels:
        app: REPLACE_APP_NAME
    spec:
      containers:
        - name: REPLACE_APP_NAME
          image: REPLACE_IMAGE # e.g. twinproduction/gatus:v5.35.0
          ports:
            - containerPort: REPLACE_PORT
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /
              port: REPLACE_PORT
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: REPLACE_PORT
            initialDelaySeconds: 10
            periodSeconds: 30
      volumes:
        - name: config
          configMap:
            name: REPLACE_APP_NAME-config
