---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: REPLACE_APP_NAME
  namespace: REPLACE_NAMESPACE
spec:
  propagateDeps: true

  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: REPLACE_APP_NAME
    - apiVersion: v1
      kind: Service
      name: REPLACE_APP_NAME
    - apiVersion: v1
      kind: ConfigMap
      name: REPLACE_APP_NAME-config

  placement:
    clusterAffinity:
      clusterNames:
        - talos-ottawa
        - talos-robbinsdale
        - talos-stpetersburg

    clusterTolerations:
      - key: cluster.karmada.io/unreachable
        effect: NoExecute
        operator: Exists
        tolerationSeconds: 60
      - key: cluster.karmada.io/not-ready
        effect: NoExecute
        operator: Exists
        tolerationSeconds: 60

    replicaScheduling:
      replicaSchedulingType: Duplicated

  failover:
    application:
      decisionConditions:
        tolerationSeconds: 60
      purgeMode: Graciously
      gracePeriodSeconds: 120

---
apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: REPLACE_APP_NAME-namespace
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Namespace
      name: REPLACE_NAMESPACE
  placement:
    clusterAffinity:
      clusterNames:
        - talos-ottawa
        - talos-robbinsdale
        - talos-stpetersburg
