---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karmada-agent-creds
  namespace: karmada-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubernetes-ottawa-karmada
  target:
    name: karmada-agent-creds
    creationPolicy: Owner
  data:
    - secretKey: caCrt
      remoteRef:
        key: karmada-system-karmada-cert
        property: server-ca.crt
    - secretKey: crt
      remoteRef:
        key: karmada-system-karmada-cert
        property: karmada.crt
    - secretKey: key
      remoteRef:
        key: karmada-system-karmada-cert
        property: karmada.key
