---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-workspace
  namespace: comfyui
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-ollama
  namespace: comfyui
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 30Gi
