---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: agents-hermes-team-a
  namespace: flux-system
spec:
  targetNamespace: agents
  commonMetadata:
    labels:
      app.kubernetes.io/name: agents-hermes-team-a
  path: ./kubernetes/apps/base/agents/agents-hermes-team-a
  prune: true
  dependsOn:
    - name: agents
  sourceRef:
    kind: GitRepository
    name: kubernetes-manifests
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: common-settings
      - kind: Secret
        name: common-secrets
      - kind: ConfigMap
        name: cluster-settings
        optional: true
      - kind: Secret
        name: cluster-secrets
        optional: true
