---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tailvoy-policy
  namespace: envoy-gateway-system
data:
  policy.yaml: |
    tailscale:
      hostname: "tailvoy-ottawa"
      ephemeral: true
    discovery:
      envoyAdmin: "http://127.0.0.1:19000"
      envoyAddress: "127.0.0.1"
      pollInterval: "5s"
      proxyProtocol: v2
