---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tailvoy-policy
  namespace: envoy-gateway-system
data:
  policy.yaml: |
    tailscale:
      hostname: "tailvoy-ottawa"
      ephemeral: true
    listeners:
      - name: default
        protocol: tcp
        listen: ":80"
        forward: "127.0.0.1:8080"
        proxy_protocol: v2
        l7_policy: true
    l4_rules:
      - match:
          listener: default
        allow:
          any_tailscale: true
    l7_rules:
      - match:
          listener: default
          path: "/raj/*"
        allow:
          users: ["rajsinghtech@github"]
      - match:
          listener: default
          path: "/kartik/*"
        allow:
          users: ["kbpersonal@github"]
    default: deny
