---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageKey
metadata:
  name: velero-key
  namespace: velero-system
spec:
  clusterRef:
    name: garage
    namespace: garage
  name: "Velero Backup Key"
  secretTemplate:
    name: velero-credentials
    accessKeyIdKey: AWS_ACCESS_KEY_ID
    secretAccessKeyKey: AWS_SECRET_ACCESS_KEY
    additionalData:
      endpoint: "http://${COMMON_S3_ENDPOINT}"
      region: garage
      cloud: |
        [default]
        aws_access_key_id=GK92298b3a23ac1e55f0a6dd23
        aws_secret_access_key=eccd15f344b40bc5acb1a22ca70531ac2e54f47acb46c4821e925e8019a00421
  bucketPermissions:
    - bucketRef:
        name: velero
        namespace: garage
      read: true
      write: true
      owner: true