---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      hostname: jellyfin
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin:10.11.8
          resources:
            requests:
              gpu.intel.com/i915: "25"
            limits:
              gpu.intel.com/i915: "25"
          ports:
            - name: http
              containerPort: 8096
              protocol: TCP
          volumeMounts:
            - name: media
              mountPath: /media-share
            - name: config
              mountPath: /config
            - name: transcode
              mountPath: /config/transcodes
          env:
            - name: PUID
              value: "0"
            - name: GUID
              value: "0"
            - name: TZ
              value: ${TIMEZONE}
            - name: JELLYFIN_PublishedServerUrl
              value: jellyfin.${CLUSTER_DOMAIN}
            - name: JELLYFIN_FFmpeg__probesize
              value: "50000000"
            - name: JELLYFIN_FFmpeg__analyzeduration
              value: "50000000"
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media-share
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-config
        - name: transcode
          emptyDir:
            medium: Memory
            sizeLimit: 4Gi
