---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cilium-mesh-secrets
  namespace: flux-system
spec:
  targetNamespace: kube-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/base/kube-system/cilium-mesh-secrets
  prune: true
  dependsOn:
    - name: external-secrets-config
  sourceRef:
    kind: GitRepository
    name: kubernetes-manifests
  wait: true
  healthChecks:
    - apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      name: cilium-root-ca
      namespace: kube-system
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cilium
  namespace: flux-system
spec:
  targetNamespace: kube-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/base/kube-system/cilium-stpetersburg/app
  prune: true
  dependsOn:
    - name: cilium-mesh-secrets
  sourceRef:
    kind: GitRepository
    name: kubernetes-manifests
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cilium-config
  namespace: flux-system
spec:
  targetNamespace: kube-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/base/kube-system/cilium-stpetersburg/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubernetes-manifests
  dependsOn:
    - name: cilium
  interval: 30m
  retryInterval: 1m
  timeout: 5m
