---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./core-dns.yaml
  - ./csi-secrets-store.yaml
  - ./cilium.yaml
  - ./irqbalance.yaml
  - ./memory-request-floor.yaml
  - ./priority-classes.yaml