---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./monitoring
  - ./clickhouse-operator-system
  - ./clickhouse
  - ./loki
  - ./mimir
  - ./cloudflare
  - ./cnpg-system
  - ./fluent-bit
  - ./dragonfly-operator-system
  - ./gvisor
  - ./kube-system
  - ./border0
  - ./gatus
  - ./speedtest
  - ./garage-operator-system
  - ./garage
  - ./spegel
  - ./volsync
  - ./zot
  - ./agent-sandbox-system
  - ./immich
  - ./tailgate-operator-system
  - ./home
