---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app ocm
  namespace: flux-system
spec:
  targetNamespace: open-cluster-management
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./clusters/${CLUSTER_NAME}/apps/ocm/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubernetes-manifests
  interval: 30m
  retryInterval: 1m
  timeout: 10m
