---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: clickhouse
resources:
  - clickhousecluster.yaml
  - service-ts.yaml
  - egress.yaml
  - httproute.yaml
  - probes.yaml
  - grafana-dashboard.yaml
  - service-monitor.yaml
---
