---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: media-autobrr-config
spec:
  sourcePVC: autobrr-config
  trigger:
    schedule: "0 14 * * *"
  restic:
    pruneIntervalDays: 14
    repository: restic-media-autobrr-config
    retain:
      hourly: 1
      daily: 3
      weekly: 4
      monthly: 2
      yearly: 1
    copyMethod: Direct
---
apiVersion: garage.rajsingh.info/v1alpha1
kind: GarageKey
metadata:
  name: volsync-media-autobrr-config-key
spec:
  clusterRef:
    name: garage
    namespace: garage
  name: "Media Autobrr Config Volsync Key"
  secretTemplate:
    name: restic-media-autobrr-config
    namespace: media
    accessKeyIdKey: AWS_ACCESS_KEY_ID
    secretAccessKeyKey: AWS_SECRET_ACCESS_KEY
    includeEndpoint: false
    includeRegion: false
    additionalData:
      RESTIC_REPOSITORY: "s3:http://${COMMON_S3_ENDPOINT}/keiretsu/${LOCATION}/media/autobrr-config"
      RESTIC_PASSWORD: "${COMMON_RESTIC_SECRET}"
  bucketPermissions:
    - bucketRef: keiretsu
      read: true
      write: true
