---
apiVersion: v1
kind: Secret
metadata:
  name: transmission-movies-secret
type: Opaque
stringData:
  WIREGUARD_PRIVATE_KEY: ${TRANSMISSION_MOVIES_WIREGUARD_PRIVATE_KEY}
  WIREGUARD_PUBLIC_KEY: ${TRANSMISSION_MOVIES_WIREGUARD_PUBLIC_KEY}
  WIREGUARD_ENDPOINT_IP: ${TRANSMISSION_MOVIES_WIREGUARD_ENDPOINT_IP}
  UPDATER_PROTONVPN_EMAIL: ${QB_PROTONVPN_EMAIL}
  UPDATER_PROTONVPN_PASSWORD: ${QB_PROTONVPN_PASSWORD}
