---
apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: unifi
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  bgpInstances:
    - name: unifi
      localASN: ${CILIUM_ASN}
      peers:
        - name: udm-ottawa
          peerASN: ${UNIFI_ASN_OTTAWA}
          peerAddress: ${UNIFI_GATEWAY_OTTAWA}
          peerConfigRef:
            name: cilium-peer
        - name: udm-robbinsdale
          peerASN: ${UNIFI_ASN_ROBBINSDALE}
          peerAddress: ${UNIFI_GATEWAY_ROBBINSDALE}
          peerConfigRef:
            name: cilium-peer
        - name: udm-stpetersburg
          peerASN: ${UNIFI_ASN_STPETERSBURG}
          peerAddress: ${UNIFI_GATEWAY_STPETERSBURG}
          peerConfigRef:
            name: cilium-peer
---
apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer
spec:
  timers:
    holdTimeSeconds: 9
    keepAliveTimeSeconds: 3
  ebgpMultihop: 4
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: bgp
---
apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-advertisements
  labels:
    advertise: bgp
spec:
  advertisements:
    - advertisementType: "Service"
      service:
        addresses:
          - ClusterIP
          - ExternalIP
          - LoadBalancerIP
      selector:
        matchExpressions:
          - { key: somekey, operator: NotIn, values: ["never-used-value"] }
    - advertisementType: "PodCIDR"
