---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app monitoring
  namespace: flux-system
spec:
  targetNamespace: monitoring
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/base/monitoring/monitoring-common/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubernetes-manifests
  interval: 30m
  retryInterval: 1m
  timeout: 15m
  patches:
    - target:
        group: helm.toolkit.fluxcd.io
        version: v2
        kind: HelmRelease
        name: kube-prometheus-stack
      patch: |-
        - op: replace
          path: /spec/values/kubeEtcd/enabled
          value: true
        - op: add
          path: /spec/values/kubeEtcd/endpoints
          value:
            - 192.168.73.248 # orin-0
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app config
  namespace: flux-system
spec:
  targetNamespace: monitoring
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: monitoring
  path: ./kubernetes/apps/base/monitoring/monitoring-common/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubernetes-manifests
  interval: 30m
  retryInterval: 1m
  timeout: 5m
