---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: jellystat-s3-store
  namespace: media
spec:
  configuration:
    destinationPath: s3://jellystat-postgres/${LOCATION}/
    endpointURL: http://${COMMON_S3_ENDPOINT}
    s3Credentials:
      accessKeyId:
        name: jellystat-s3-backup
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: jellystat-s3-backup
        key: AWS_SECRET_ACCESS_KEY
  instanceSidecarConfiguration:
    env:
      - name: AWS_DEFAULT_REGION
        value: garage
  retentionPolicy: "30d"