---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
    tailscale.com/tailnet-fqdn: cilium-mesh-api-ottawa.keiretsu.ts.net
    tailscale.com/proxy-group: common-egress
  name: ottawa
spec:
  externalName: placeholder   # any value - will be overwritten by operator
  type: ExternalName 
  ports:
  - name: https # any value
    port: 2379
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
    tailscale.com/tailnet-fqdn: cilium-mesh-api-stpetersburg.keiretsu.ts.net
    tailscale.com/proxy-group: common-egress
  name: stpetersburg
spec:
  externalName: placeholder
  type: ExternalName
  ports:
    - name: https
      port: 2379
      protocol: TCP
