apiVersion: v1
kind: Secret
metadata:
    name: hermes-secrets
type: Opaque
stringData:
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:xz/aE7Q1Vo5RYI+o5+DB4B/ZvfkJ/KzXgjoYR5seygWwVwlg6iTQV95SbHNVSVBpoRcbd9Bu26Uc9AdyAWbaNUH/pviJjI7o,iv:lj5d9S2KCT1cjHg/hqkcpeU6+3ywCNCzkoppxACL4v4=,tag:zz/F5FlsRsuyc+kK9myvUA==,type:str]
    GH_TOKEN: ENC[AES256_GCM,data:WBU20jTNGHSdBOMkjB2eZx23BrGqrJA/qqt1hXGlAeaXbswY38Ce+w==,iv:4WGtrbaFREwRWVfJY7Hl+1bFUsvYrcOjZDv+fwMMwL0=,tag:WP++J3tBkDhB/aPBxREZLA==,type:str]
    API_SERVER_KEY: ENC[AES256_GCM,data:p/93ut96iYk/wiqP1MHddp/xCNclhc3kX5DyHP3SpqZuVMis3ujsMBrGuoKu4Ybrp/VrhgyldIjg6KYceKidHw==,iv:LKAGNP7KywEz5NFgnLuNFOH8J86O1TLofRPiPcQNiOo=,tag:YK9mvhp8uqfIIRTo4WygKQ==,type:str]
sops:
    lastmodified: "2026-04-18T08:12:57Z"
    mac: ENC[AES256_GCM,data:dxM8wA/FkZKITB5TmLg/5FqOjfslPNdEJxwC+JGS7tQy+qOjVa5K22sFLK8AdiLhpRh2WuOBHyWqA6UISFWPR8gmzbfdNnUzCzjNQStUYFMKp/FGbPq8vIUKasOzymFFD3BsqerGRmmJUlfCxHJQyH+ac4wdhMwsuhLYfqPc5Vo=,iv:SqvW1Q0fnEYFExf9INpsLTITl8ArlScWRK3w13Y7jGk=,tag:NRVpDWZN6nRb1E0XbpsInQ==,type:str]
    pgp:
        - created_at: "2026-04-18T08:12:57Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveAQ//RSqeqvy5ut5lmzZKQcu5eHRCZU49WOgK1mIMACcjo/XH
            W57QjCmR5rTti31s9/NHljVvycLFV/hwV7D6ZAfcZAqh+s2/VoHLC5bmim3DsQzp
            Np+zmBQcD8Mvj+wi2azgZcJeG2QnYaagyMhX53gKdd6zAqUVYrsq1wcGh792N+WZ
            QaSI7UO+QW9HJK3irtzmlqib5sXz8Ms48tLOoN+GzbBI1FNfivX5Rs7GwFSGZDjQ
            Mp3wZBikZ6LG3bc/ph8zLH4yCAEZcOzbde2fKQ4zifdRjw5QJB/rasFNrQTABDUX
            nDNs8MXAEW2UhQ7E+OEnFeTRnX6NJmvTYCHnyH25KLjgniA+hiq5+Dema3M4BvwN
            LFMjUvQ4ph/Q/d9SpFzH7XyHO8kOF0giCl3tf4CwPF6IYgY4aiC9cbHdOXAB2pNq
            8GOWFDFvMFoMP+9u99U6vAX2e7iIEyOc7rFh/Ehd492E1NNaMZG3o5gZPLpISgr8
            TwpQAYlFKNAL22jEu3sB2XFQpDUN5CirJ4iXYq5jbvsFqE51N6+gkviKAcnhejBS
            ZJqA7qB7C3yTq0E17OS4wp1kqF1dHDaLaAEAVZAyXOAzcKG5aGTaWXysr6z4kAvG
            BQjHOZysZvpBlXd/EQD4+/iLG7QPPB8XODg23iUECXyOnNIMaBFvYKl7Rx9zG23U
            aAEJAhBfGm2/En7Cx3Rjlek6hmttvNeCsFCEE6bS2QMDd4PJLA1kxE81B2djVZIG
            J/hvVODyCp9NRXkayMqicxldIUiqxDNmTQRn3lmHjtRZHOdJ/dRtkHLUdCK3GWCd
            Jz1zXAMyV8q1
            =SJFR
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
