apiVersion: v1
kind: Service
metadata:
  name: ocm-grpc-mesh
  namespace: open-cluster-management-hub
spec:
  type: ClusterIP
  selector:
    app: cluster-manager-grpc-server
  ports:
    - name: grpc
      port: 443
      targetPort: 8090
      protocol: TCP
---
apiVersion: multicluster.x-k8s.io/v1beta1
kind: ServiceExport
metadata:
  name: ocm-grpc-mesh
  namespace: open-cluster-management-hub
