---
apiVersion: storage.keiretsu.ts.net/v1alpha1
kind: StorageStack
metadata:
  name: sonarr-1080p-config
  labels:
    keiretsu.ts.net/location: robbinsdale
spec:
  name: sonarr-1080p-config
  size: 5Gi
  storageClass: ceph-block-replicated-nvme
  s3Path: media/sonarr-1080p-config
  schedule: 0 4 * * *
  restoreMode: restore
  restorePaused: false
  copyMethod: Direct
