apiVersion: v1
kind: Secret
metadata:
    name: tailvoy-bridge-credentials
    namespace: tailvoy-bridge
type: Opaque
stringData:
    keiretsu_client_id: ENC[AES256_GCM,data:jGBGmq04sXAgQca76Ds+2/I=,iv:xE/5pJ8bDdGewDzFaN3nemYlYrkgk0921kSC9BVvqt8=,tag:+AKsFXDZcGmez6EXGi2kVw==,type:str]
    keiretsu_client_secret: ENC[AES256_GCM,data:y5riyjp1uQ8eeivmNgxMJv3SDbGjMlIOfCtmt7L/Ob1WALJvnmWr0k6MbeHtzyndVr/sUZ+wdw83COJtlXps,iv:VH4b/DOu4Nhfu/KgR55gmI0D4aSShWQziswl0UtKXOU=,tag:9Zup1ejG7NB451XQMf3Eng==,type:str]
    tsjustworks_client_id: ENC[AES256_GCM,data:5RbxSsY/A/bWSwLi2o+Gm9k=,iv:ad2MjpMCdsosN6CjPitkuZYoJoXAGRmd18Dx+qHwPqg=,tag:dHpcOfIHAWf1wtbBc7oKZA==,type:str]
    tsjustworks_client_secret: ENC[AES256_GCM,data:6sz81BDFaq2EqHkC1eU3v2EYoERW4rlvWLHPDPIR0sPfE+1Izzx+9e7ZehwbJefa1UWq1fkB2btWNiW5cY02,iv:EZeiH1I6M3BtsrfQZ3Wd0wtUSPNeMtKvgLrX60vylB4=,tag:ikB+20TAOu2rBl/nYo2YLA==,type:str]
sops:
    lastmodified: "2026-03-21T05:20:26Z"
    mac: ENC[AES256_GCM,data:KLB4YXQm+Tqbdoq1pW58fVyWiTyOo2mEr9olMBk2Ude7jpihBTsuH+5urZ712EjBimc0SMNXELQBR8vjWiLtiA1aWSZoE3hz8o96sqnIWFfQdY244xxv5nhzmXR/5cVaI/59RKnR5rsQrYUwadjzWrgH9PagGhi7YsV4oO71fvM=,iv:wFgkE7ymqn2wIAUG5nNgqFARTPZIEBA49HM4VLrVrXM=,tag:BYGTEEDpVVTmWp3e7mkaOA==,type:str]
    pgp:
        - created_at: "2026-03-21T05:20:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveAQ//fTj2fPOISwgFf246eHgNbSIulsbx43vfiOLOh0mKIH6s
            uAbZRCAY/k61dPXshi9W2e+r0MA8FW9I1ElRBFOwMQUUc97lkIAkMwrwktWmA3gW
            CMHG440LT56z74ylOr6GQhVjaY5YGCHco+Bn+APnw5GmKC2tgSSz50swlQr82ttA
            75I5Spc9P+4b5UjfbFXsCWLrZl6XGxClwevgrnjpqiMOBAx+3UBFGUGenLlX/KC/
            bsPTwCAYxy/1VyqanHyc1CBPX14hmlurvljihFoMjiALY6d7drUXEn3KGEHcQWCu
            tpgPfP3C9NDfA1MKZGL/ncubXT9QqHxAx/ygJYMHCySDnTnLw3ZENBnvsZ3yx2CW
            HeejA7nRsJwyOKk404PfairFm9fZk+tOeiYPFbJBJ2osWmXrTVEBNDp+1ktbooX+
            wV1nQm4z13241xAPCRLMXSoLT2B2Msc0E9MQ8rfh7kAB/fUSRohDclOm0hVivUET
            s9ZsaNNAY/hVexAHHTSzIvRozjK8BgFKUtoHt9uZ7qjTi4CUGrAefh2USH3/jeyg
            DFh2Jufz2uORwVeheOBg6pa/TV6jHWzdlOlC63l5r0Nv8kgrgDHeEJIjcK6Zq2bB
            fKyeRYwozwABeBzCakitn1QHjMwHF7DJ0Tq0qd1aGihxASOxQTD1uVMcrt9/KiTU
            aAEJAhApcUclRLRx2IgkoJ2EMPloP72kNwXUS7wxNRx7pxNDAlNNXJRe5HhWx4Hq
            RkKP+I4XGlucL8tr/1b0bMTwQcvAO5/0wtD8tj6A+eSKMMfp+jP9p95fF+7ZRUDr
            sn20SoFDHqNA
            =wCvr
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
