---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: woodpecker-postgres
spec:
  inheritedMetadata:
    labels:
      app: woodpecker-postgres
  instances: 2
  bootstrap:
    initdb:
      database: woodpecker
      owner: woodpecker
      dataChecksums: true
      postInitApplicationSQL:
        - ALTER USER woodpecker WITH PASSWORD '${WOODPECKER_DB_PASSWORD}';
  storage:
    size: 10Gi
    storageClass: ceph-block-replicated
  monitoring:
    enablePodMonitor: true
