apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace-nix-cache
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block-replicated
  resources:
    requests:
      storage: 64Gi
