---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageBucket
metadata:
  name: teaspoon-web
spec:
  clusterRef:
    name: garage
    namespace: garage
  globalAlias: teaspoon-web
  quotas:
    maxSize: 1Gi
    maxObjects: 10000
  website:
    indexDocument: index.html
    errorDocument: error.html
  keyPermissions:
    - keyRef:
        name: teaspoon-s3-key
      read: true
      write: true
      owner: true