---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: speedtest
resources:
  - ns.yaml
  - job.yaml
  - pvc.yaml
  - job-smb.yaml
  - pvc-smb.yaml
  - job-s3.yaml
  - pvc-s3.yaml
