---
apiVersion: v1
kind: Service
metadata:
  name: k8sgpt-mcp
  namespace: k8sgpt
spec:
  selector:
    app.kubernetes.io/name: k8sgpt-mcp
  ports:
    - name: mcp
      port: 8089
      targetPort: mcp
      protocol: TCP
