---
apiVersion: media.keiretsu.ts.net/v1alpha1
kind: ArrApp
metadata:
  name: bazarr-4kremux
  namespace: media
spec:
  name: bazarr-4kremux
  image: lscr.io/linuxserver/bazarr
  # renovate: datasource=docker depName=lscr.io/linuxserver/bazarr
  tag: "1.5.6"
  port: 6767
  hostname: bazarr-4kremux
  homerName: "Bazarr 4K Remux"
  homerSubtitle: "Subtitle Management"
  homerLogo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/svg/bazarr.svg"
  configStorageSize: 5Gi
  configStorageClass: ceph-block-replicated-nvme
  mediaClaimName: media-share
  mediaMountPath: /media-share
  volsyncCopyMethod: Direct
  volsyncManualTrigger: "first"
  volsyncPaused: false
  s3Endpoint: "${COMMON_S3_ENDPOINT}"
  s3Location: "${LOCATION}"
  resticPassword: "${COMMON_RESTIC_SECRET}"
  clusterDomain: "${CLUSTER_DOMAIN}"
