# All setec resources float together as a unit
---
apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: setec
spec:
  propagateDeps: true

  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      labelSelector:
        matchLabels:
          karmada.io/app: setec
    - apiVersion: v1
      kind: Secret
      labelSelector:
        matchLabels:
          karmada.io/app: setec

  placement:
    clusterAffinity:
      clusterNames:
        - talos-ottawa
        - talos-robbinsdale
        - talos-stpetersburg
    clusterTolerations:
      - key: cluster.karmada.io/unreachable
        effect: NoExecute
        operator: Exists
        tolerationSeconds: 120
      - key: cluster.karmada.io/not-ready
        effect: NoExecute
        operator: Exists
        tolerationSeconds: 120
    spreadConstraints:
      - maxGroups: 1
        minGroups: 1
        spreadByField: cluster
    replicaScheduling:
      replicaSchedulingType: Divided
      replicaDivisionPreference: Weighted
      weightPreference:
        dynamicWeight: AvailableReplicas

  failover:
    application:
      decisionConditions:
        tolerationSeconds: 120
      purgeMode: Gracefully
      gracePeriodSeconds: 300
---
# Propagate namespace
apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: setec-namespace
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Namespace
      name: setec
  placement:
    clusterAffinity:
      clusterNames:
        - talos-ottawa
        - talos-robbinsdale
        - talos-stpetersburg
