apiVersion: v1
data:
    mac.key: ENC[AES256_GCM,data:OWWtKaOuW9v7NqHIowI84yahCNzGN5kgrOFEDhmMs/IxigwCa1EtvICz9s0=,iv:omSAynyCKzLjIP/9sJtOi/4i0BagNo5vu48yYNltyq8=,tag:raSZam1ZKfobSVpGBZEyKw==,type:str]
kind: Secret
metadata:
    name: spurfire-alpha-broker-mac
    namespace: spurfire
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T10:41:50Z"
    mac: ENC[AES256_GCM,data:feSe8D5GFFogWaidTxPyWKBauTp+P6yOO8bupoDvwaNNlbmFs77M+5aXdBRP5i3aDu+RF6i8kP3XwMsRe9vKrSAMotrTd2rZtYyqGuU1lSh/7VT2bLKbsGWs1vrW2WkM9ayM9YekSKRotiwZDVW8rmYSB2b7tdBbkpatD5Vyrb8=,iv:32Fnh2sCkFiPrQpPM+oSnSTkm1Y2X7VRALQSuwv2CYA=,tag:6uxeD4Zqkaa+hR0l1FKO5w==,type:str]
    pgp:
        - created_at: "2026-07-22T10:41:50Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveARAAlNdmtPppCgOeroWVmYaLQUNILF0IvRZWlmAUWZYCoeXa
            klTclN9Ms0tb/5A7x1jrZLaw7JzPTPWkRSSfwuoj/rIr6D4DRuyokyWpAiyEbISm
            G3Xz19gKvne0+Tf5cdmA4yx4HgWAby9Fqqp8xsdvmpOjgrg43R6AbqUIZ4y6mDA8
            5ZxK57/wShbu9WUgd4eXwzqLvNbkpqU9FMuTimU3qxN2uisgxtyYY4r7ovw8h8Dz
            a+CftlUw1Kl+QKPMj2BHMU7D0n2VTNUGyZivOUqH1uAZncsdLfHvEFoaXIELiA06
            4EX5PYJz0ffFMCV33us9/3b7Jlp77vq/OFXNVIj/W5nKPRzhhQqV16RhL+8YlJFj
            Dk+fJgOT+1fhNOzRXWNbEXNl2b1YZwFh1hGtaPO2bzzNgbV5zhQJ96Qb5NDbsFZr
            nyouUABXnfOtWl6AdK2iwzIyL88294J7fU/R96PTLhLtsDl7R3ZKmlwlSRzR7UrU
            tYkA6cEFrDj1M4FWOJjz/s6lL1QYhdaduFOipTkDzQNI0nSlQNMfR8iPxFssHZPp
            2+JTr+3jIlUaMDridVgTvvWW49ovjDgWp0EnEiLKQXMZe3LjMWJQLkbq5r+3bQbR
            Un7/k852n+PLp+bKMrzcVsfxuYmoCBRHe8v9yvPep2CRW8iR5mo9oo4PQXPCS2PU
            aAEJAhADAmQTYNVerp+Rp1JmkYAGfAn05u0KzFX4pgKqfVvr3k2LJ6wm+IHEBhj5
            UDCMAc70LKUnxcp8wFjWdwuOXgz9XNl5edglRJjLo4fove3jgxIxiLDe4iF4t3mt
            FqHSJUJT5cuT
            =Sii7
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    version: 3.13.2
