---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: spurfire
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: "0.2.0-main.36.1.sha-32eed847693f"
    digest: "sha256:27b48f5d5e2f8702464f32d1f8138715fe169c55d025d4c0b364a6a9b09cc7ce"
  url: oci://ghcr.io/rajsinghtech/charts/spurfire-control
