---
apiVersion: media.keiretsu.ts.net/v1alpha1
kind: GluetunApp
metadata:
  name: qbittorrent
  namespace: media
spec:
  name: qbittorrent
  clientImage: lscr.io/linuxserver/qbittorrent
  # renovate: datasource=docker depName=lscr.io/linuxserver/qbittorrent
  clientTag: "5.1.4"
  clientPort: 8080
  clientPeerPort: 6881
  # renovate: datasource=docker depName=ghcr.io/qdm12/gluetun
  gluetunTag: "v3.41.1"
  enablePortSync: true
  # renovate: datasource=docker depName=ghcr.io/bjw-s-labs/gluetun-qb-port-sync
  portSyncTag: "0.0.4"
  vpnSecretName: qbittorrent-secret
  vpnCountry: "Netherlands"
  vpnPortForwarding: true
  podCidr: "${CLUSTER_POD_CIDR}"
  serviceCidr: "${CLUSTER_SERVICE_CIDR}"
  hostname: qbittorrent
  homerName: "qBittorrent"
  homerSubtitle: "Torrent Client"
  homerLogo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/svg/qbittorrent.svg"
  downloadsClaimName: media-share
  configStorageSize: 5Gi
  configStorageClass: ceph-block-replicated-nvme
  volsyncCopyMethod: Direct
  volsyncManualTrigger: "first"
  volsyncPaused: false
  s3Endpoint: "${COMMON_S3_ENDPOINT}"
  s3Location: "${LOCATION}"
  resticPassword: "${COMMON_RESTIC_SECRET}"
  clusterDomain: "${CLUSTER_DOMAIN}"
  timezone: "${TIMEZONE}"
