---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission-tv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission-tv
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: transmission-tv
    spec:
      containers:
      - name: transmission-tv
        image: linuxserver/transmission
        env:
        - name: WEBUI_USERNAME
          value: "admin"
        - name: WEBUI_PWD
          value: "placeholder"
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        ports:
        - name: http
          containerPort: 9091
          protocol: TCP
        volumeMounts:
        - name: data-volume
          mountPath: /downloads
        - name: config-volume
          mountPath: /config
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: transmission-tv-data-unas
      - name: config-volume
        persistentVolumeClaim:
          claimName: transmission-tv-config-unas
