---
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: ottawa-store
  namespace: rook-ceph
spec:
  preservePoolsOnDelete: false
  zone:
    name: ottawa
  gateway:
    port: 80
    instances: 1
    placement:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - rook-ceph-rgw
              topologyKey: kubernetes.io/hostname
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 1Gi
