---
apiVersion: ceph.rook.io/v1
kind: CephObjectZone
metadata:
  name: ottawa
  namespace: rook-ceph
spec:
  zoneGroup: keiretsu
  preservePoolsOnDelete: false
  metadataPool:
    failureDomain: host
    enableCrushUpdates: true
    replicated:
      size: 3
      requireSafeReplicaSize: true
  dataPool:
    failureDomain: host
    enableCrushUpdates: true
    replicated:
      size: 3
      requireSafeReplicaSize: true
