---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8gb
  namespace: k8gb
spec:
  interval: 30m
  chart:
    spec:
      chart: k8gb
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: k8gb
        namespace: flux-system
  values:
    k8gb:
      imageRepo: ghcr.io/rajsinghtech/k8gb
      imageTag: exposed-hostnames
      clusterGeoTag: "${LOCATION}"
      extGslbClustersGeoTags: "${K8GB_EXT_GEO_TAGS}"
      dnsZones:
        - parentZone: "keiretsu.top"
          loadBalancedZone: "cdn.keiretsu.top"
          dnsZoneNegTTL: 30
        - parentZone: "keiretsu.top"
          loadBalancedZone: "ts.keiretsu.top"
          dnsZoneNegTTL: 30
      edgeDNSServers:
        - "1.1.1.1"
      nsRecordTTL: 30
      reconcileRequeueSeconds: 60

      exposeMetrics: true
      serviceMonitor:
        enabled: true

    coredns:
      replicaCount: 3
      serviceType: LoadBalancer
      service:
        loadBalancerIP: "${CLUSTER_LOAD_BALANCER_CIDR%.*.*/*}.10.53"

    extdns:
      enabled: false

    gatewayapi:
      enabled: true
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: ConfigMap
              name: k8gb-coredns
            patch: |
              - op: replace
                path: /data/Corefile
                value: |
                  (k8gbplugins) {
                      errors
                      health
                      reload 30s 15s
                      ready
                      prometheus 0.0.0.0:9153
                      forward . /etc/resolv.conf
                      k8s_crd {
                          filter k8gb.absa.oss/dnstype=local
                          negttl 30
                          loadbalance weight
                      }
                  }
                  cdn.keiretsu.top:5353 {
                      import k8gbplugins
                  }
                  ts.keiretsu.top:5353 {
                      import k8gbplugins
                  }
