apiVersion: v1
kind: Secret
metadata:
    name: litellm-secrets
    namespace: litellm
type: Opaque
stringData:
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:E1zvSmzRuQjExmIEG6HMqfzs3yCqV+r06ZeDr7z21Ne5P7I3Bw0Xt1qQTWTo3MtGcOgOZSgODAC4OL7K603+d4vbCA==,iv:4zLqdftfGA65OVJ7hcuzbmPAe1FHSoQgrvLwQumSTl0=,tag:Kb7gTJuHTtPJgLKnt6dQdA==,type:str]
    LITELLM_SALT_KEY: ENC[AES256_GCM,data:jDclHp6H/VGXj+W7VfbBG94jS0u7+c4ofAG9ejh9VSDkVohv01PrON51LQn7BIc9t+Y3W+4z6B1kW1SJox1V39LbrjjlfrxvGjoJ9kmJqbRSPImlN0k=,iv:kBaLChkVCmxasQmhLAJKi/98a7LCClSWhEHXCzWpF4I=,tag:m2dIo3cP7yUGmHZc++oE+A==,type:str]
    CLIPROXY_API_KEY: ENC[AES256_GCM,data:brEXGjXjoz/p2Ys/lTTHg4l1jt4wGATdvXX0HuQCo4EYJo3179rncJY9L5G8RqAXoNwDkIIiSeMXbn92JM4zvA==,iv:xyOoJRZFJFre1qQ9/c5/gMaXTwHCCXkTbKk/S399GuU=,tag:fnIymPvrOebJdgMYX/CXgg==,type:str]
    DRAGONFLY_PASSWORD: ENC[AES256_GCM,data:/UqJ2e1+h6X2I38Ur7zTyFNOtQfrSyi8qVSWDx23nfEnrqfAflkmLmn2lVOvXEyuNHOpQIK3iEie7MBCa0y4pw==,iv:thtoaM3Et6pzMtKwnRTtsFwj2pkQGbIygXxRBx7oAmA=,tag:x231IAi/M8FoZ1JXrHQ7Sw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T17:30:40Z"
    mac: ENC[AES256_GCM,data:3cL5zGvN4EfqhRf09mJc/EU0aOj6WYQ/xisb2fHKrPa/b77Zuv6tt+yZsoN1uBsGtPdyyynEtffU197zg0+IMADqnKfg4RK7p1yRpIPuoiG6gNDyxqWLR5KdWNsy02GWwmYyPsBROnODlA+E36Rzh6adW3mytzzLW19iwlaUgU0=,iv:a6el+ewf6x27EaKLf2/Lz4GXC9XXJx6H5iuXbRFOpIM=,tag:BAslR2hk/fikL0l3Syi/RQ==,type:str]
    pgp:
        - created_at: "2026-09-25T17:30:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveARAAhm5GQ3962KLou58INc4d+U5KcDHcIDl1gy9uHsQB5L+G
            TXUEaqlDGhzJlXuMFUY700eXaVAJzy1Zey25GbD39gQ5JJC7DPZ9zYzdDw67933A
            yhqvLJt4YA6FOx+G5dSEjmprKu2QRRz1W12SzV/5ZeLMh6gI5wRqCGaJpq5qQhy/
            KuHK9fYw2zra1cfdq85KjynCz/JvpIrT91mTQVKPJ8p5QTj4yCT/I7ACeUqbuOy0
            eoXiAyo9OHo4LI9Jc3KcJSitsULMbzkU62AJ4AVzkh1NKlGdmwgd374r9LigPnh9
            UxP+al5BN/BEiwUP6jvWKC4B1srqBTTSDbeIJM+HztzjLVmEKQ3m2o9kxj/vUj8g
            VDLwVNZE5lpjyeENHHUgGFytyOXanEwuRyU1ZbJe+eq+AUDKDpuIMHRzGLYHclIe
            QtmpaJHxSnVi3A5ia/hRXVBxapY/9MRQYndttKaWLaQkeEAPDjHhWXH89z/WzZkd
            Ip3cf2LcH7vYrbpGcryRs/02IBNBNNZNKhUv30HUOtoSOzRenuvpD9KUdoLwaWBy
            uLEDmpO4+I8iE6kPV9dTTYP99T+vf5h85bzppg49d0L3MCFZhyp+imYWI5pLZmVq
            b88LLdv9GbZkVNKIcZslkvTZsv9eImIncWcv+pfJZHYfv+uLbz+nO9wdroKpUJ3S
            XAFTRuqP7j2nBXPCYeMq6COiUr9Tsht5H1zldHts40a6WQoQYAq7ePfeoEAlTK99
            qdBfOxvkjUh2l6+cHOenxfXkWw9mj4c9P4X2z4jeKL76N5oO5tZ+kU+X+1fA
            =3aBA
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    version: 3.13.3
