apiVersion: v1
kind: Secret
metadata:
    name: cartography-secrets
type: Opaque
stringData:
    #ENC[AES256_GCM,data:l5+8N3MEjYopieiyIuPpLBh4nncABcwM9rmR8iY6iY+ikXy3g5rFN/gQ3Y4=,iv:ahZ9SEux27NulfyUgHV5D5aygd+Jg4oA3o+78F/Pzy0=,tag:iuruAJCT3ieJC/0e176kXw==,type:comment]
    #ENC[AES256_GCM,data:gCbal1jatAO8Q4JeJiX1MHVDe0bFS+sJzKWGo6mSDGCZGZJDgI+8tu2gmxdqYiXwUGIRp74suHaBqjrBebprjjo+FFDsjA==,iv:DjjbmY1qooG7lzX6wxVum0Ln7btD5kt7S7UkjgEZc0Q=,tag:JtXqQz+YjUYn0co07QXl+w==,type:comment]
    #ENC[AES256_GCM,data:QPWR21YVm4MG,iv:tALSAI0ChgndHP80CP8wAciYl9Im9zH+ojsBchDTbO4=,tag:zEbpN04QpFU5XdTwyD86Dw==,type:comment]
    #ENC[AES256_GCM,data:hDzLBtyNTpg7PwSfdU1jTzU3Me83MamVlDrpQ4B7G9WhSdwEkjcCDmSwFGwTCoPEvxvcAyp9PRFWIvKxgOKfnLGuarVTPag+8I1vOkHal8KRSY8A47lfF39LFewe/Jax4HBvIM3UUNhu,iv:4PYhwnJOIC1GMYRq+EXFNz7zsVCpdDCep5ncyXibFiA=,tag:2sb9NHv1WWqto5rpTAbkHQ==,type:comment]
    #ENC[AES256_GCM,data:I3EpkawaV5gIOLW7Fw==,iv:ag0LZEgUis7sYnweTGqPCCX3RdaOJp4EHi1tLrAUJrg=,tag:btmyejOyDR5LyeoFXudvIA==,type:comment]
    GITHUB_CONFIG: ENC[AES256_GCM,data:I86XpbyyH7Em91+zLiDPM81C5H9EeLA9umseTyJXsGw=,iv:X1SMLvUyTVQ1qBvU899FzDuDAnp2k+d70Slv03Wc7qY=,tag:oG+xjSn0ZIRevQHeVUS/Pg==,type:str]
    #ENC[AES256_GCM,data:XNJPon371fyWKoTtepYfvGotCal1nkwLghBvWdkqVw76kY+XZFT49NSQL5GgWA==,iv:NQ/RSnR87dmloDy1oFseWVN2/VVd1eLGowo6VaAsIVY=,tag:2y9wRHFgvyyLLQs4t4BSzA==,type:comment]
    #ENC[AES256_GCM,data:f99vtNzeW+hYYrFcb+mv6GkIjUzlXj8uv3Gz3Qynq31M2ajDikKqKAm2oW11xcYvvg==,iv:3zAqneXK/NuAUW42gzb5hqBvlsQ5s743xTgAGCyPgZA=,tag:+xZFOjVV2CkjwcGo4EwVaw==,type:comment]
    #ENC[AES256_GCM,data:+Og3Yw4RbYCUIQXJi3gjjm9LgUUBRWSwoqAxWjNE66XKBahYrLOYp72ozmbfDTAOc0DHLFI2H8kGeiIe,iv:toFpwKOXf3yLhFZkDevCePfi1wP5/Nn7fHAn+xaTomk=,tag:Hc+VC1bcARPrwUY2nqAjBA==,type:comment]
    #ENC[AES256_GCM,data:ppuc4wRMzeYN+ptGjx1dqs4tiSg6SHgeBeQYSaXV+vLW1cb3P3pNkzebMtveeO27zpUcoQ78WRhu,iv:O3wlEFGSe48e+GS5CVzs2wWY6yBQKwGUQc7R6632FAY=,tag:xU4YqNttbXy8MhLBr1fBzw==,type:comment]
    #ENC[AES256_GCM,data:hTf4VigSLpatN3oonG/3LRVSWCQk+PWFvFpmK5m0WuhMSKtrzk/ZEasR9hOVsAUKBpb6HbqFVUa4PsY=,iv:x9SebgKJGNEAl/XCDBcG+ECRkIw3IhgJsgQoFYeFwpE=,tag:trreyKtCjsmZI/lORmR1TQ==,type:comment]
    #ENC[AES256_GCM,data:c5CY+asNYQkD6JbxmmK0QCMKUoJoa8DaMHjR5sfr/dC6jAC3p+pOKXwDgV922dtM4+1QaQ==,iv:3+1B9gxmQMqANaGNStdxwxNVwyUHtT3wX3CD3yn7aZ8=,tag:uJqNV1w0kma/ICSQm0S2tg==,type:comment]
    TS_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:o/74I17Tog4pTLwU7EZskhRzRlTv3uVTN46xP7lG,iv:DNRvafxYSMK8+jp2keWqivoIvyibTz2/sjPKa3/FyPw=,tag:Vzhj1L0x2xnf4dYqppATHg==,type:str]
    TS_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:4GunrTNsxtWjbAbw1OYvAaEen9SaNPSZYjB6qOwV2keNEw==,iv:0lnbsoxvO0IgtJlL9qWzUAY0JVsPlQsI6wvTPcn5DiM=,tag:rn8D08q/9b7HUDRvZX2M5Q==,type:str]
sops:
    lastmodified: "2026-05-06T21:05:49Z"
    mac: ENC[AES256_GCM,data:5LRyuWjBh4/1S43eh39eg9PqfyqxjCHT4hPtDy74QE4gdqkH7QB8XsrRyEJW943E1lz168UxYzTHlBIkS7HWp2pfaicWICRFSB8blfy+RYwUHWBuB6ySE2OJa0Cnxn2isVhKzG0EHO1HWMC9nzoxrrB1g3jwGhTJ2njSXIpVy04=,iv:RXN1uz8SxLn2d2be/yDFVd2igJb45HiFMrRpmVkZXi4=,tag:/eG8EKJHqHMeI/c9V3aILA==,type:str]
    pgp:
        - created_at: "2026-05-06T21:05:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveAQ/7BSAiU1wASUN6Myah5oUabQkEtbR+KGuplpq3FcxflNnv
            8KjtJnAR3Ih5Q3VU7TTPh7D6hmFhEzUTc2Ui/bQm3dHsJwdndiv+bRMqrSz0Re/H
            6f3wzOJE9StWKsyTMZH4KmRuokNX+Jav7K1ZT36nW1nPS7blF3tOofsY54XLEYOI
            C41itzBOowZXkx9IUBvXRS6f9f4WerGzi4IXpAXnIOdW3XUFA4i30DmGdDxYM7+B
            iWMHwBCj6xSuDMJyrbfy0lYq4mLx1N68nkjmgoNnJSl6EBKJs2u/d+wm/Sl5+CHP
            ppNm1aJNpRBAut2qX3CBqvjuD9cx6lc3E5oVoVhRtnajbZ5BVQHVInC5Xiq8oVGa
            sErk1BWEGQKWuRJ6iIZ1P6b4hAEFayzDSl/TBNjLeZrY7YaYVS5fUL05Y8z9MYL5
            REC8cVNiRJ2i7QXe2npEmPgqraE6BSvFDOGqDCnPMCGgPq7PJN4ZDUgF8TuNMeU6
            Xz9CGYMORQN7rqcFAhauaCqyoGsoreXGAyj6r7hisb3VounW7HhJTc39P0NY/95F
            jY2mrBM7SbBi46lWUrsAaajiVcjjDBpQZcU3H9fslV4OJDh1HyWlUi4XEpiyU/La
            YyS+RoEJueC2n+WLriGHh0DlN+0GFlAIC/dtZn3n7G/KPOB+2KOQz4FTkmo32rzU
            aAEJAhCT7CLLf/lEQ6wW+oH2xbGnldHRt8Pan+lXR0LEq8f4ppPcG5gRkzSLjWvI
            lPra5EhjqMxZ1L7DklpPCCip4mcyS6idN5bk5t7knd1hoDDOXygkmfEMleiHug+U
            QzZ07fO8jvaV
            =2PtC
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
