---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: app-garage-local
spec:
  jobName: blackbox
  module: tcp_connect
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - garage.garage:3900
        - garage.garage:3903
      labels:
        service: garage
        target: local
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: app-garage-cross-cluster
spec:
  jobName: blackbox
  module: tcp_connect
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - ottawa-garage.garage:3900
        - ottawa-garage.garage:3903
        - robbinsdale-garage.garage:3900
        - robbinsdale-garage.garage:3903
        - stpetersburg-garage.garage:3900
        - stpetersburg-garage.garage:3903
      labels:
        service: garage
        target: cross-cluster
