---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageReferenceGrant
metadata:
  name: garage-bucket-to-lobby-postgres-key
  namespace: tailscale-pam
spec:
  from:
    - kind: GarageBucket
      namespace: garage
  to:
    - kind: GarageKey
      name: lobby-postgres-key
