---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageReferenceGrant
metadata:
  name: bhaiya-postgres-bucket
  namespace: bhaiya
spec:
  from:
    - kind: GarageBucket
      namespace: garage
  to:
    - kind: GarageKey
      name: bhaiya-postgres-key
