---
apiVersion: apps.keiretsu.ts.net/v1alpha1
kind: App
metadata:
  name: maintainerr
  namespace: media
spec:
  image: ghcr.io/maintainerr/maintainerr
  # renovate: datasource=docker depName=ghcr.io/maintainerr/maintainerr
  tag: "3.4.1"
  port: 6246
  configMountPath: /opt/data
  runAsUser: 1000
  fsGroup: 1000
  hostname: maintainerr
  clusterDomain: "${CLUSTER_DOMAIN}"
  homerName: "Maintainerr"
  homerSubtitle: "Media Library Cleanup"
  homerLogo: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/maintainerr.svg"
  configStorageSize: 5Gi
  configStorageClass: ceph-block-replicated
  backupEnabled: true
  freshInstall: true
  s3Endpoint: "${COMMON_S3_ENDPOINT}"
  s3Location: "${LOCATION}"
  resticPassword: "${COMMON_RESTIC_SECRET}"
