---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageKey
metadata:
  name: raj-trades-s3-key
spec:
  clusterRef:
    name: garage
    namespace: garage
  name: "raj-trades S3 Key"
  allBuckets:
    read: true
  secretTemplate:
    name: raj-trades-s3
    accessKeyIdKey: AWS_ACCESS_KEY_ID
    secretAccessKeyKey: AWS_SECRET_ACCESS_KEY
    additionalData:
      AWS_ENDPOINT_URL: "http://${COMMON_S3_ENDPOINT}"
      AWS_ENDPOINT_URL_S3: "http://${COMMON_S3_ENDPOINT}"
      AWS_REGION: "garage"
      AWS_DEFAULT_REGION: "garage"
