---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kopiur-ottawa-repo
  namespace: flux-system
spec:
  dependsOn:
    - name: kopiur
    - name: garage-kopiur-ottawa-bucket
  commonMetadata:
    labels:
      app.kubernetes.io/name: kopiur-ottawa-repo
      app.kubernetes.io/part-of: kopiur
  path: ./kubernetes/apps/base/kopiur/kopiur-ottawa
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubernetes-manifests
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 10m
