---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageKey
metadata:
  name: infisical-postgres-key
  namespace: infisical
spec:
  clusterRef:
    name: garage
    namespace: garage
  name: "Infisical Postgres Backup Key"
  secretTemplate:
    name: infisical-s3-backup
    accessKeyIdKey: AWS_ACCESS_KEY_ID
    secretAccessKeyKey: AWS_SECRET_ACCESS_KEY
  bucketPermissions:
    - bucketRef:
        name: infisical-postgres
        namespace: garage
      read: true
      write: true
      owner: true