---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tailscale-recorder-key.yaml
  - tracearr-postgres-key.yaml
  - immich-postgres-key.yaml
  - tailscale-logs-key.yaml
  - mimir-key.yaml
  - bookorbit-postgres-key.yaml
  - omnibus-postgres-key.yaml
  - bhaiya-postgres-key.yaml
