---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: transmission-music-pvt
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: transmission-music-pvt
#   strategy:
#     type: Recreate
#   template:
#     metadata:
#       labels:
#         app: transmission-music-pvt
#     spec:
#       containers:
#       - name: gluetun
#         image: ghcr.io/qdm12/gluetun:v3.41.1
#         securityContext:
#           capabilities:
#             add:
#             - NET_ADMIN
#           allowPrivilegeEscalation: false
#         env:
#         - name: VPN_SERVICE_PROVIDER
#           value: protonvpn
#         - name: VPN_TYPE
#           value: wireguard
#         - name: WIREGUARD_PRIVATE_KEY
#           valueFrom:
#             secretKeyRef:
#               name: transmission-music-pvt-secret
#               key: WIREGUARD_PRIVATE_KEY
#         - name: WIREGUARD_PERSISTENT_KEEPALIVE_INTERVAL
#           value: 14s
#         - name: WIREGUARD_MTU
#           value: '1410'
#         - name: HEALTH_VPN_DURATION_INITIAL
#           value: "10s"
#         - name: HEALTH_VPN_DURATION_ADDITION
#           value: 5s
#         - name: VPN_PORT_FORWARDING
#           value: "on"
#         - name: PORT_FORWARD_ONLY
#           value: "on"
#         - name: SERVER_COUNTRIES
#           value: "Netherlands,Poland"
#         - name: DOT
#           value: "off"
#         - name: HEALTH_TARGET_ADDRESS
#           value: "1.1.1.1:443"
#         - name: FIREWALL_INPUT_PORTS
#           value: "9091"
#         - name: FIREWALL_OUTBOUND_SUBNETS
#           value: ${CLUSTER_POD_CIDR}
#         - name: UPDATER_PERIOD
#           value: "24h"
#         - name: UPDATER_PROTONVPN_EMAIL
#           valueFrom:
#             secretKeyRef:
#               name: transmission-music-pvt-secret
#               key: UPDATER_PROTONVPN_EMAIL
#         - name: UPDATER_PROTONVPN_PASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: transmission-music-pvt-secret
#               key: UPDATER_PROTONVPN_PASSWORD
#         - name: LOG_LEVEL
#           value: info
#         volumeMounts:
#         - name: gluetun-config
#           mountPath: /gluetun
#       - name: transmission
#         image: lscr.io/linuxserver/transmission
#         ports:
#         - name: http
#           containerPort: 9091
#           protocol: TCP
#         volumeMounts:
#         - name: config-volume
#           mountPath: /config
#         - name: downloads-volume
#           mountPath: /downloads
#         env:
#         - name: PUID
#           value: "1000"
#         - name: PGID
#           value: "1000"
#         - name: TZ
#           value: ${TIMEZONE}
#       volumes:
#       - name: config-volume
#         persistentVolumeClaim:
#           claimName: transmission-music-config-unas
#       - name: downloads-volume
#         persistentVolumeClaim:
#           claimName: transmission-music-data-unas
#       - name: gluetun-config
#         emptyDir: {}
