---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: home-frigate-config-ceph
spec:
  sourcePVC: frigate-config-ceph
  trigger:
    schedule: "0 5 * * *"
  restic:
    pruneIntervalDays: 14
    repository: restic-home-frigate-config-ceph
    retain:
      hourly: 1
      daily: 3
      weekly: 4
      monthly: 2
      yearly: 1
    copyMethod: Snapshot
    volumeSnapshotClassName: csi-rbdplugin-snapclass
---
apiVersion: garage.rajsingh.info/v1alpha1
kind: GarageKey
metadata:
  name: volsync-home-frigate-config-ceph-key
  namespace: garage
spec:
  clusterRef:
    name: garage
  name: "Home Frigate Config Ceph Volsync Key"
  secretTemplate:
    name: restic-home-frigate-config-ceph
    namespace: home
    accessKeyIdKey: AWS_ACCESS_KEY_ID
    secretAccessKeyKey: AWS_SECRET_ACCESS_KEY
    includeEndpoint: false
    includeRegion: false
    additionalData:
      RESTIC_REPOSITORY: "s3:http://${COMMON_S3_ENDPOINT}/keiretsu/${LOCATION}/home/frigate-config"
      RESTIC_PASSWORD: "${COMMON_RESTIC_SECRET}"
  bucketPermissions:
    - bucketRef: keiretsu
      read: true
      write: true
