---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./monitoring.yaml
  - ./grafana-dashboard-prune.yaml
  - ./kromgo.yaml
  - ./unpoller.yaml
  - ./blackbox-exporter.yaml
  - ./blackbox-exporter-robbinsdale.yaml
  - ./smartctl-exporter.yaml
